### ISSUE TITLE
[TRANSLATIONS] Translators please subscribe to be notified of changes

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gnome-shell-extension-gsconnect#1]
This is a thread for discussion of translations and notification of changes to translatable string. If you are a translator, please subscribe to this issue to be notified of changes.

**Comment by andyholmes** [comment]
Sorry about that, I've changed the text domain to org.gnome.Shell.Extensions.GSConnect in git, but I usually wait until a release to update the wiki. You can use these commands:

    ninja org.gnome.Shell.Extensions.GSConnect-pot
    ninja org.gnome.Shell.Extensions.GSConnect-update-po

The change in text domain shouldn't change anything on your side, and I won't be changing it again. I also plan on putting some simple instructions for translating the WebExtension but let me know if your interested now.

**Comment by Arquanite** [comment]
Ok, if better instructions will be available I will make a pull request. For now I have translated po file, some other files were generated by this commands but extension still is in english.

**Comment by andyholmes** [comment]
Okay, I've updated the Wiki to be a little clearer about all the steps.

https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Translating

Let me know if you need more help getting the translation working.

**Comment by andyholmes** [comment]
I'm about ready to release v8, let me know if you'd like me to wait to get your translation included.

**Comment by Arquanite** [comment]
I've just created pull request. I'm sorry that it took so long, I had some issues with my laptop (gnome was half polish half english :o)

**Comment by andyholmes** [comment]
No problem, I think that was GSConnect causing that :/

**Comment by shiba89** [comment]
Are we supposed to fork master or v10? If it's master, po/* files are missing the gsettings.js and preferences.js merge (and the first ninja commands fail).

**Comment by andyholmes** [comment]
@shiba89 Sorry about that. I've sort of broken a lot of things on the way to v10 and a few commits were pushed before I made a new branch. Currently the next version is not ready to be translated and won't be until I sort some things out.

Sorry about the delayed reply.

**Comment by mkey-cdx** [comment]
Ok, let me know when things are ready. I'd be happy to provide you with a French translation.

**Comment by andyholmes** [comment]
Hello translators. I have be in conversation with the reviewers Gnome Extensions website and I'm planning a v9 bugfix release that will be distributed fairly soon (under a week).

There will still be many translation changes in v10, however the version to be released on the official website will be around for a fair amount of time, so if you would like to submit a new/updated translation please let me know so I can hold off before releasing.

**Comment by mkey-cdx** [comment]
Hello @andyholmes. As I said, I'll be able and happy to give you a French translation. This should be done within a week.

**Comment by amivaleo** [comment]
Hi! I've just updated the italian translation. ;)

**Comment by andyholmes** [comment]
@mkey-cdx sounds good, i'll let the extension reviewer know when they get back to me.

@amivaleo thanks again!

**Comment by piotrdrag** [comment]
`intltool-update -m` is reporting these two files missing from POTFILES:

```
data/debug.ui
src/service/plugins/contacts.js
```

The first one looks like a false positive, but the second indeed looks missing.

**Comment by andyholmes** [comment]
Ah thanks, fixed. Yep, `debug.ui` I think shouldn't be translated since users (usually) shouldn't use that.

**Comment by andyholmes** [comment]
Sorry, everyone! Seems like a lot of strings in the Glade files were not marked as translatable.

**Comment by ricvelozo** [comment]
Still some strings are missing / not getting translated:

* The extension description in about dialog
* To device / from device (clipboard sync)
* Items from Menu (Connect LAN, Unpair, Connect to..., etc)

**Comment by andyholmes** [comment]
Okay, hopefully I have fixed the menus being translated now. The About dialog I'll have to fix for next release. Right now it's automatically taken from metadata.json which doesn't get translated.

**Comment by L0sted** [comment]
Do Not Disturb toggle in menu and DnD duration popup are also untranslateble

**Comment by andyholmes** [comment]
Should be fixed now, but you have to re-pull and restart gnome shell.

**Comment by ricvelozo** [comment]
Nice! All right here.

**Comment by andyholmes** [comment]
Hi everyone, I think we're about ready to release v15 which has a few new and changed strings (v14 was a very minor release that isn't reviewed on e.g.o yet). @amivaleo your translation should already be up to date, so nothing to do for you.

The changes are pretty minor so release date will be **Monday, November 5th**, unless someone needs more time.

**Comment by andyholmes** [comment]
Sorry guys, we made a little mistake with one or two "pluralized" strings that may require an update on your part. As usual, feel free to ask for more time if you need us to hold back release.

**Comment by ricvelozo** [comment]
@andyholmes Some strings turned comments after update from POT... Can you check if is ok? PR https://github.com/andyholmes/gnome-shell-extension-gsconnect/pull/302

**Comment by ferdnyc** [comment]
I answered @ricvelozo 's question over at #302, but for the group:
> The commented strings are ones that we removed from the source, or changed their (English) meaning since the last time the master `.pot` file was generated. They're stored in comments that way to make it clear that was intentional. (And also so any translations provided for those strings will be preserved, in case they're put back into the code at a later date.)

**Comment by Vistaus** [comment]
@ferdnyc I always use Poedit, so I never see any commented strings anyway lol

**Comment by andyholmes** [comment]
Hi everyone, I've just merged the new Messaging UI and between that and some other changes, there are a number of new and changed strings. I've already realigned the POT and everything for you. Here's a  preview:

![screenshot from 2018-11-19 11-31-27](https://user-images.githubusercontent.com/1265208/48730418-25e0ca00-ebef-11e8-81eb-99a031472e3b.png)

I think this should be all for this coming release (v17) and I'm not in a rush so you have lots of time :)

**Comment by andyholmes** [comment]
Quick update, I just "fixed" the translations to use proper quotations, except for the ones who were already doing so. So if you had _very_ recently pulled you may want to do so again, otherwise I'll just fix it up when you submit your PR.

**Comment by piotrdrag** [comment]
I can see you put a lot of work into it, so it pains me to say that maybe it was a bad idea. Every language has different rules for quotations, and I'm pretty sure at least German is wrong. It would have been best to change just the quotations in code early in the next release cycle and let translators fix their translations.

**Comment by andyholmes** [comment]
oh no, you're right 😟 I think i see the German error I made (and with french) hopefully, translators will fix my fixes.

**Comment by ricvelozo** [comment]
@andyholmes What will the release date be?

**Comment by ferdnyc** [comment]
^ (I don't think I've ever been involved in a GitHub project where I haven't _eventually_ typed "#1" in an issue comment, and accidentally created a reference to the repo's first issue. So at least that's **that** tradition out of the way. 🙄)

**Comment by DeadMetaler** [comment]
Hi. I've made a 100% translation but some string stayed in english. Why it may happend?

![2018-12-19 14-07-08](https://user-images.githubusercontent.com/10463702/50216801-d3363180-0397-11e9-9e13-11d76a72d1fc.png)
![2018-12-19 14-04-46](https://user-images.githubusercontent.com/10463702/50216802-d3363180-0397-11e9-817a-a144d4331230.png)

**Comment by andyholmes** [comment]
> Hi. I've made a 100% translation but some string stayed in english.

Thanks! The first screenshot looks like Firefox/Chrome, so I have to update the extension on those websites before the translation will show.

The second one is actually sent by KDE Connect Android, and *our* translated version only get shown in some fallback situations (very rare). I've asked the KDE Connect team where they do their translations, so I'll link you when they get back to me if you want to add the translations for that too :)

**Comment by amivaleo** [comment]
Uh!
I'll help with the italian translation. :)

**Comment by andyholmes** [comment]
Cool, I'll let you know what I find out :)

**Comment by DeadMetaler** [comment]
> Thanks! The first screenshot looks like Firefox/Chrome, so I have to update the extension on those websites before the translation will show.
> 
> The second one is actually sent by KDE Connect Android, and _our_ translated version only get shown in some fallback situations (very rare). I've asked the KDE Connect team where they do their translations, so I'll link you when they get back to me if you want to add the translations for that too :)

First screenshot from Nautilus right-click menu.

**Comment by ferdnyc** [comment]
@DeadMetaler :
> > Hi. I've made a 100% translation but some string stayed in english. Why it may happend?
> 
> First screenshot from Nautilus right-click menu.

The Nautilus extension code picks up its translation files from the Gnome Shell extension's install location in your user data directory:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/398457c079ea62c9002fb7c3bc0486a833761a35/src/nautilus-gsconnect.py#L24-L30

(Typically that's `$HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/locale`.)

So if the correct `xx.mo` file is present there for the locale `xx`, it should be picked up. Note that it's probably only checked/loaded once when the extension is started, so may have to kill and restart at least Nautilus, if not Gnome Shell, for the extension to re-load the translations. (Or log out and log in again.)

**Comment by andyholmes** [comment]
Hi everyone, over the last couple days I have been trying to setup Crowdin for GSConnect.

For some languages this seems to work well, but for others there may be some difficulties. Currently Belarusian and Estonian are setup and working.

If you have used Crowdin before and/pr would like me to setup your language, please let me know and I will add it for you. The link for it is here: https://crwd.in/gsconnect

**Comment by amivaleo** [comment]
Here I am!
Let me deal with the italian translation. :)

**Comment by Vistaus** [comment]
I've dealt with translations on Crowdin before, but I really dislike the interface and the way translation fixes aren't deal with because they are easily overlooked. So I'd rather translate the old-fashioned way or prefer an alternative site like Weblate or Transifex.

**Comment by L0sted** [comment]
I want to help with russian translation

**Comment by piotrdrag** [comment]
Please count me in as well.

**Comment by Madis0** [comment]
Since some of you seem to be quite confused about Crowdin, let me do a quick comparison between it's and PoEdit's best features. Main thing to highlight is in bold, meaning GSConnect can stop accepting git PRs and PoEdit users can still use the tool they like.

Crowdin:

* Continuous integration - every string you translate can be pushed to release right away
* Concept of none/translated/approved - in Crowdin, _translators_ can translate and _proofreaders_ can freeze phrases that already have the "best" translation
* Contexts, comments and issues - contexts are meant to aid the translation, comments are made to discuss the translation (with other translators mainly) and issues are about the problems of translation or original (with the project managers mainly)
* Mainly online - has a nice responsive design for even mobile usage, and lets people directly collaborate on specific strings, although *files can be downloaded/uploaded* for offline if so allowed by manager
* Glossary file (if added), global/language terms (if added), spell check (if available), project translation memory, global translation memory, machine translation suggestions
* Translation mode and voting/proofreading mode - you can either deal with translation string-by-string or see the original and translation both at once
* Search and advanced filters
* Find and replace
* Keyboard shortcuts

PoEdit:

* Commit-based integration - strings are pushed as soon as you say so
* Concept of none/fuzzy/translated - in PoEdit, everyone can translate everything and they can mark their translations as fuzzy or have changed ones marked as fuzzy
* Static comments - everyone can comment on something and it will stay so until someone else changes it
* Mainly offline - meant for single-person usage whenever they have time, comments are seen by others when you push them
* Global translation memory, spell check
* Search and some filters
* Find and replace
* Keyboard shortcuts

---

> translation fixes aren't deal with because they are easily overlooked

Counter-arguments:

-  since there is no concept of "fuzzy", users are more forced to re-translate than just re-accept (even with the help of translation memory)
- as written above, Crowdin has live commenting/issue system so problems can be discussed with managers and others right away, instead of commiting your version and hoping someone notices your comment

> and seem like they have the potential to do some percentage of the translating for us, basically — how large a percentage, I have no idea

It is similar to PoEdit - even though there are more variations of suggestions, they must always be selected individually by a translator. There is even a search filter for reviewing translations done by it, to prevent machine translation abuse.

**Comment by Vistaus** [comment]
@Madis0 I'm not against working in teams or discussing or anything, like I said, I do a lot of translation work on Transifex and Weblate also so I know exactly how this works. I just don't like Crowdin, I have bad experiences with it.

**Comment by Vistaus** [comment]
> > and the screenshot-based context feature is a neat idea.

Weblate has that as well, so it's neat, but not unique.

**Comment by Faenriis** [comment]
My two bits: Crowdin uses ICU locales and locale definitions.
GSConnect is based on Gnome libraries, thus uses locales and locale definitions as defined in glibc.
And they do differ. And it does cause problems (translating free software for about a decade).
Interface might deceivingly be easer for beginners, though I'd rather take a good translation over an easy one anytime, as I'm sure all end users do.
Therefore, I'd appreciate if translating the way it was done so far still remains an option. Thank you.

**Comment by vincegre** [comment]
Possible to add French ? I would be happy to do all french translations ;)

**Comment by andyholmes** [comment]
Hi everyone, I thought I'd let you know v20 is getting ready to be released in the next few days maybe, although I'm in no rush. For those not using crowdin, there have been a few string changes since last release, but nothing too big.

As usual let me know if you need some time to get around to it and I'll be happy to wait until you're ready.

**Comment by zalanlevai** [comment]
@andyholmes I would love to help out with a Hungarian translation using Crowdin.

**Comment by BathoryPeter** [comment]
@zalanlevai Hungarian translation is almost complete, I'm just working on the latest update.

**Comment by welaq** [comment]
@andyholmes Hey, I'd love to help out with Lithuanian translation. Please add Lithuanian language to Crowdin.

**Comment by LethalEthan** [comment]
@andyholmes Hi, could you add Danish to crowdin? I would like to translate it :smile:

**Comment by andyholmes** [comment]
@LethalEthan all added, should be good to go :)

**Comment by BodilessSleeper** [comment]
I wanna add a Serbian translation if you don't mind :D

**Comment by iblader** [comment]
@andyholmes I would like to add Chinese translation to GSConnect, could u please add Simplified Chinese (中文简体) to crowdin?

**Comment by andyholmes** [comment]
Sorry guys, my memory is terrible and I forgot to cross-post my comment from the release notes.

There were quite a few string changes and additions in v25/26, but I got caught off guard by a protocol change in KDE Connect and had to push out a release before I could review them or update the translation template.

I hope to do this either today or tomorrow and I'll mention this issue in the commit, so hopefully you get pinged if you're not on crowdin.

**Comment by andyholmes** [comment]
Sorry for the delay for everyone, apparent `xgettext` has a major regression parsing template literals in JavaScript with the 0.20.1 update, which ironically claimed:

> "JavaScript: xgettext now parses template literals correctly"

I was up late last night trying to get the template file updated, but I'm going to have to figure something else out; either build an older version of gettext from source or remove all template literals from translatable files.

**Comment by laichiaheng** [comment]
@andyholmes I would like to translate it to Traditional Chinese, how to add a language in crowdin?

**Comment by ferdnyc** [comment]
@laichiaheng I've just added Chinese Traditional to the Crowdin project.

Crowdin also offers three additional options:
* Chinese Traditional, Hong Kong
* Chinese Traditional, Macau
* Chinese Traditional, Singapore

Let me know if you'd like any of those enabled in addition to / instead of "Chinese Traditional".

**Comment by ferdnyc** [comment]
I've also added a `zh_TW.po` translation file to the repo, and merged all outstanding translation PRs. As soon as I've double-checked to be sure I'm not screwing anything up, I'm also going to update the translation master, because it looks like there have been a number of string changes since the last update.

**Comment by andyholmes** [comment]
@ferdnyc thanks for updating the POT file, I was fighting with xgettext until 3AM last night. Just to be sure, are you running `gettext <= 0.19.8.1` (you should unless you're on Fedora31/Ubuntu 19.10/etc)? See my last note on bug [50920](https://savannah.gnu.org/bugs/?50920).

**Comment by ferdnyc** [comment]
@andyholmes Yeah, I saw that. Still safe here:

```console
$ gettext --version
gettext (GNU gettext-runtime) 0.19.8.1
Copyright (C) 1995-1997, 2000-2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

**Comment by ferdnyc** [comment]
@andyholmes  I do have a question about the translation file names. As you can see from my (edited) comment above, Crowdin sent through the Chinese Traditional translations as `zh-TW.po` instead of `zh_TW.po`, so I went with it and adopted the `zh-TW` name for the files, in `LINGUAS`, etc..

I see in deaeeed0 you renamed the `ar-SA.po` file to `ar.po` (went the other way on that, in other words), but looking at #638 new translations still seem to be coming in from Crowdin as `ar-SA.po`. (So, now both `ar.po` and `ar-SA.po` exist, and are out of sync because when I rebuilt the translations only `ar.po` was updated.)

How should we handle that?

**Comment by andyholmes** [comment]
@ferdnyc As far as I've been been told, in general the two letter form is preferred (eg. `fr` which will work for France and Quebec) unless it's actually significantly different such as `pt` and `pt_BR` (Portugal Portuguese and Brazilian Portuguese) or someone wants do both to such as our Netherlands/Netherlands Netherlands/Belgian...Dutch (?) translator.

I'm more confused now that I try to think about it, but I think gettext translations are separated with an underscore (`_`) while Crowdin requires a hyphen (`-`) (except some languages like Serbian that have Latin and Cyrllic forms and need an `@latin`), which is why we have the mappings in `crowdin.yml`. Then the WebExtension has its own form, which is why I wrote a script so I didn't have to remember :confused: 

I don't know, usually @piotrdrag tells me when I get mixed up :sob:

**Comment by ferdnyc** [comment]
Aha!! `crowdin.yml` was the piece I'd missed.

> I think gettext translations are separated with an underscore (`_`)

I wonder if it actually cares? I'd added `zh-TW` to `po/LINGUAS`, not noticing that there was a way to remap Crowdin's names, and AFAICT gettext seems to be fine with using and updating `zh-TW.po`.

What **does** seem to care is GlibC. As a test I tried to open Totem with `LANG=en-GB` (after `LANG=en_GB totem` opened fine; I don't have a lot of supported languages installed on my system), and I got this:
```
$ LANG=en-GB totem
(totem:7839): Gtk-WARNING **: 02:17:58.649: Locale not supported by C library.
	Using the fallback 'C' locale.

(totem:7839): Clutter-WARNING **: 02:17:58.698: Locale not supported by C library.
Using the fallback 'C' locale.
```
(Which is a bummer, because Qt applications open the same translations whether the language name is specified as `lang_locale` or `lang-locale`.)

So, I guess I'll go rename that file now, and add a mapping in `crowdin.yml`. :roll_eyes:

**Comment by Faenriis** [comment]
Problem is (and I mentioned it before) that Crowding bases their locales and locale definitions on ICU (libicu), while Gnome and everything that depends on gnome libs uses locales and locale definitions as defined in GNU C library (glibc). Which makes the choice to use Crowdin a very questionable one. 
You simply can't use ddifferent locale definitions other than those that the core library on which the program is based is coded.
On top of it, Gnome provides no "user friendly" way of switching translations for a single program. Locale needs to be set for the entire session, and if gsconnect translation is not using the proper locale code which Gnome session expects, it will not be used.

I still strongly suggest to everyone to create/upate translations via git and submit merge requests.
Sure, Poedit and similar localization programs may not have as idiot proof interface as what Crowdin offers, but it is the only way to guarantee that submitted translation files will be working and used as expected.

**Comment by Faenriis** [comment]
P.S. Chinese locales as per glibc are:

#zh_CN.GB18030 GB18030  
#zh_CN.GBK GBK  
#zh_CN.UTF-8 UTF-8  
#zh_CN GB2312  
#zh_HK.UTF-8 UTF-8  
#zh_HK BIG5-HKSCS  
#zh_SG.UTF-8 UTF-8  
#zh_SG.GBK GBK  
#zh_SG GB2312  
#zh_TW.EUC-TW EUC-TW  
#zh_TW.UTF-8 UTF-8  
#zh_TW BIG5  
#zu_ZA.UTF-8 UTF-8

zh_TW is the correct one in your case.

**Comment by ferdnyc** [comment]
> Which makes the choice to use Crowdin a very questionable one.
> You simply can't use ddifferent locale definitions other than those that the core library on which the program is based is coded.

\*shrug* That strikes me as overly alarmist.

I mean, Crowdin is _built_ by the `poedit` developers, and they're fully integrated with each other. Heck, there's a "What is Crowdin?" link on the `poedit` welcome screen, if you launch it without loading a translation file. Once you authenticate you can even use it to retrieve and update translation files directly from Crowdin. Far from being in competition with / alternatives to each other, they seem very much designed to work in concert. It needn't be an either/or.

Plus, `gettext` doesn't really have any concept of locale — as I noted, it was perfectly happy to update `zh-TW.po` when the file was named that (and generate a `locale/zh-TW/LC_MESSAGES/org.gnome.Shell.Extensions.GSConnect.mo` file from it) — it'll use whatever names are defined in the `LINGUAS` file it works from. I think you're giving `poedit`/`gettext` too much credit for managing the translation locales more intelligently, when there's no evidence I can see that that's actually the case.

Even when translations are prepared in Crowdin, they're submitted via git PRs, so it's not like we've ceded control of the translations or anything. Believe me, I could make a mess of this stuff just as easily _without_ Crowdin as I can with it, I don't need its help to screw up. :wink:

**Comment by amivaleo** [comment]
Why do I keep getting notifcations for the chinese translation? 🙈
I barely understand english!

😂

**Comment by Faenriis** [comment]
@ferdnyc It is not alarmist, it simply is the way it is. Crowin does not let you select all locales that Glibc (and thus Gnome) uses. Them being Poedit developers means nothing, Poedit works with whatever you tell it to work with. On the other hand, Gsconnect expect Gibc locale codes. Again,it is not alarmist, it is simply a matter of a fact.

**Comment by piotrdrag** [comment]
gettext indeed doesn’t care what language codes you feed it, but GNOME expects glibc locales and won’t work with anything else. So installing `ar-SA.mo` is pointless (and even `ar_SA.mo` won’t work for any ar_ locale other than the Saudi Arabian, as far as I know). As I see it, it doesn’t matter what codes Crowdin uses as long as the result is .mo files recognized by glibc-based systems.

By the way, this being a GNOME Shell extension, it might be a good idea to peek at what the shell does wrt. language codes when adding new languages: https://gitlab.gnome.org/GNOME/gnome-shell/tree/master/po

**Comment by andyholmes** [comment]
> gettext indeed doesn’t care what language codes you feed it, but GNOME expects glibc locales and won’t work with anything else. So installing ar-SA.mo is pointless (and even ar_SA.mo won’t work for any ar_ locale other than the Saudi Arabian, as far as I know)

Yes, I fiddled with crowdin for a bit, but gave up because the Arabic translator hasn't actually submitted any strings yet. For some reason the `ar-SA: ar` mapping is the only one which is not working correctly. If it's not doing harm we could leave it or just remove it and wait for them to appear again.

> By the way, this being a GNOME Shell extension, it might be a good idea to peek at what the shell does wrt. language codes

:+1: Also a good idea, thanks :)

I'm going to go fiddle with crowdin and see if I can get the conflicts resolved now :)

**Comment by laichiaheng** [comment]
@andyholmes I'm deeply sorry. Could you update the translations again? I have corrected lots of wrong translations today, lots of them had been translated by Simplified Chinese users, so I had to find them and correct them to Traditional Chinese, some of them included two %s in one sentence, and I didn't know that the order of them must be the same, because the order of them in Chinese are reverse.

**Comment by andyholmes** [comment]
@laichiaheng no problem, all merged :) Let me know if the translations still aren't working after a rebuild.

**Comment by andyholmes** [comment]
@ferdnyc Do you still have `gettext-0.19.1`? If so, would you mind regenerating the POT file?

**Comment by ferdnyc** [comment]
@andyholmes Whoops, just saw this sorry. I do still have 0.19.8.1 (which I assume you meant), I'll take care of it now if it's not already updated.

**Comment by ferdnyc** [comment]
Done, and the Crowdin PR is resyncing now.

**Comment by rffontenelle** [comment]
@andyholmes Would it be possible to add Brazilian Portuguese (pt-BR) ?

**Comment by andyholmes** [comment]
Hi translators,

For the first time in awhile there are some new strings. We now have [AppStream](https://en.wikipedia.org/wiki/AppStream) metadata that distributions who package GSConnect may choose to include.

More importantly, some initial work has begun to annotate GUI elements for accessibility (eg. screen readers for visually impaired). Some of these may not be commented yet, but do your best :)

**Comment by amivaleo** [comment]
So we're gonna get some new cool stuff. 😎

Thanks!

**Comment by andyholmes** [comment]
Codename for v40 is "boring" :wink:. It's going to be a release of bug fixes, performance improvements, memory reduction and code refactors.

*Next* release, well that might be [big](https://invent.kde.org/network/kdeconnect-android/-/merge_requests?state=merged&search=mms). :slightly_smiling_face:

**Comment by vancha** [comment]
Hello, i have added the frisian translation to crowdin, I hope it can be included in an upcoming version of gsconnect :) thank you for your work.

**Comment by fr3nchalp4a** [comment]
Is this still used by translators? If yes, can an admin pin this (or someone ref it in the README) ? If not this should be closed.
