### ISSUE TITLE
GSConnect not sending tel:// - Links to phone ("No device found") – although Connection ist established and working

### ISSUE THREAD

**Issue by uditarenos** [GSConnect/gnome-shell-extension-gsconnect#1041]
**Describe the bug**

When clicking on a "tel:" Link in Firefox, GSConnect doesnt find the device, although the phone is paired. I can see it in my GSConnect settings. Most moduls work fine. Except: I cant send files to the phone. Sending files from phone to Laptop works fine. 

**Steps To Reproduce:**

1. Go to a phone number in Firefox.
2. Click on the phone number "tel:+????????"
3. Popup window "Select a Device" says: No Device Found.

**Expected behavior**

Laptop sends the phone number to the phone.

**System Details (please complete the following information):**

GSConnect ver. 43
installed from Extensions Website
GNOME 3.36.4 (Ubuntu 20.04 LTS)

**Comment by andyholmes** [comment]
Thanks for reporting. PR #1043, that should fix this, is ready for testing.
