### ISSUE TITLE
Not finding any devices, not connect with ip either

### ISSUE THREAD

**Issue by survivor303** [GSConnect/gnome-shell-extension-gsconnect#1042]
GSConnect: 44 (user)
GJS:       16601
Session:   x11
OS:        Ubuntu Hirsute Hippo (development branch)

**Comment by andyholmes** [comment]
Can you confirm that you can ping the device?

**Comment by survivor303** [comment]
sorry for late reply, but yes, i can ping it.
also, when restarting gnome, it give me that "port is used by other application" but when i trying to check what application use it, the system dosnt find any.

**Comment by andyholmes** [comment]
Sounds like a local networking problem then. If GSConnect can't bind to the default port it won't be able to open or accept connections. If `lsof -i UDP:1716` is not indicating another application using the port, then there is probably some security policy preventing it.

**Comment by ElonSatoshi** [comment]
I'm getting this issue on Fedora 33. Do you have any idea what this local networking problem might be?

**Comment by andyholmes** [comment]
Closing since this seems to have been caused by KDE Connect being installed at the same time as GSConnect. Feel free to reopen if the problem persists with a current version of GSConnect.
