### ISSUE TITLE
Unable to send files to the computers: "Failed sending file to COMPUTERNAME"

### ISSUE THREAD

**Issue by papanito** [GSConnect/gnome-shell-extension-gsconnect#1048]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Sending files to the Computer does not work and I get an error immediately `Failed sending file to COMPUTERNAME`. Sending files from the computer to the mobile works fine

**Steps To Reproduce:**

1. Go to 'Android FIle Manager'
2. Select file and "Send to KDE Connect"
3. Select COMPUTERNAME
4. See error `Failed sending file to COMPUTERNAME` 

**Expected behavior**

File will be successfully send to COMPUTER

**Screenshots**

N/A

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 44 (user)
GJS:       16602
Session:   x11
OS:        Manjaro Linux
--------------------------------------------------------------------------------
-- Journal begins at Thu 2021-01-14 04:22:55 CET, ends at Thu 2021-02-04 13:16:52 CET. --
-- No entries --
```

**System Details (please complete the following information):**

 - **GSConnect version:**  `4`
   - **Installed from:** `Package Manager, ...`
 - **GNOME/Shell version:** `3.38`
 - **Distro/Release:**  `Manjaro`

**GSConnect environment (if applicable):**

 - **Paired Device(s):** `Galaxy S10+`
 - **KDE Connect app version:** `1.16`
 - **Plugin(s):** `N/A`

**Additional Notes:**

Sending files to the Mobile, works fine

**Comment by papanito** [comment]
Seems a firewall issue. I've ensured the proper service is assigned to the zone
![gsconnect_firewalld_services](https://user-images.githubusercontent.com/15034009/107347434-1ac32e80-6ac6-11eb-9b44-2253c6c76a21.png)
![gsconnect_firewalld_zones](https://user-images.githubusercontent.com/15034009/107347437-1bf45b80-6ac6-11eb-93a4-59174c31258f.png)

**Comment by pabloab** [comment]
In my case upgrading Android app did the trick. Also maybe [this](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#firewall-or-iptables-blocking-port).

**Comment by shu7bh** [comment]
I too have this problem. The problem occurred after my WiFi had stopped for a minute.
Files were properly being shared from my phone to my laptop (Manjaro-Gnome) before this.
After I was connected to WiFi again, and my phone and laptop were both showing connected in KDE Connect, I tried multiple times to share files and was unable to do so. I was also unable to share the files from the KDE Connect app on my phone.

I have faced this same issue a couple of times before (usually when I need fast transfers 😂 😢) and I was able to pinpoint the error this time.

**Comment by andyholmes** [comment]
> Edit: Should I open a new issue?

Probably, although there's a 99.9% chance this a local networking problem. Reports like this a very common and to be honest they're just always local networking problems.

I'd recommend you look through the [Wiki](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help). KDE Connect also has a [Wiki](https://userbase.kde.org/KDEConnect#Troubleshooting) with some tips. If none of those help, it *could* be an issue in GSConnect, but you'd need to provide an error log showing where it happens so it can be fixed.

**Comment by bloodykheeng** [comment]
this works
 I found out that right clicking on the kde connect icon at taskbar on windows, then choosing the device and then clicking at the option to send files does work. It's a weird workaround.
