### ISSUE TITLE
Runcommand plugin only works with android application

### ISSUE THREAD

**Issue by R1tschY** [GSConnect/gnome-shell-extension-gsconnect#1051]
**Describe the bug**

The `kdeconnect.runcommand` network packet is send in the wrong format. The value to the `commandList` key in the `kdeconnect.runcommand` network packet is a string and not a JSON object. The android app is permissive and accepts the JSON object. Other clients like KDE Connect / Sailfish Connect do not support this.

See also:
https://invent.kde.org/network/kdeconnect-kde/-/blob/master/plugins/runcommand/runcommandplugin.cpp#L89
https://invent.kde.org/network/kdeconnect-kde/-/blob/master/plugins/remotecommands/remotecommandsplugin.cpp#L33
https://invent.kde.org/network/kdeconnect-android/-/blob/master/src/org/kde/kdeconnect/Plugins/RunCommandPlugin/RunCommandPlugin.java#L89

**Steps To Reproduce:**

Connect a device with a client other than KDE Connect Android.

**Expected behavior**

GSConnect accepts and sends `kdeconnect.runcommand` packets in KDE Connect format.

**Support Log**

```
Feb 10 20:32:09 gjs[75864]: JS ERROR: GSConnect Tower: Error: Expected type utf8 for Argument 'label' but got type 'undefined'
                            _handleCommandList@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/runcommand.js:166:18
                            connected@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/runcommand.js:85:14
                            _triggerPlugins@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:1019:24
                            setChannel@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:330:14
                            _onChannel@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:225:20
                            channel@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/home/richard/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**System Details (please complete the following information):**

 - **GSConnect version:** 43 (code not changed to newest version)
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.4
 - **Distro/Release:** Ubuntu 20.04

**Comment by andyholmes** [comment]
Thanks for reporting, that's a strange thing to do so I never noticed it :)
