### ISSUE TITLE
GSConnect doesn't detect phone or vice/versa despite going through every troubleshooting step

### ISSUE THREAD

**Issue by GitThisBugOff** [GSConnect/gnome-shell-extension-gsconnect#1055]
`
GSConnect: 44 (user)
GJS:       16601
Session:   wayland
OS:        Ubuntu 20.10
--------------------------------------------------------------------------------
-- Logs begin at Sat 2020-10-17 15:54:52 AST, end at Sat 2021-02-13 01:54:23 AST. --
Feb 13 01:54:00 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=01:00:5e:00:00:01:40:0d:10:aa:2f:b0:08:00 SRC=192.168.0.1 DST=224.0.0.1 LEN=36 TOS=0x00 PREC=0xC0 TTL=1 ID=65233 PROTO=2 
Feb 13 01:54:00 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=01:00:5e:7f:ff:fa:40:0d:10:aa:2f:b0:08:00 SRC=192.168.0.1 DST=239.255.255.250 LEN=36 TOS=0x00 PREC=0xC0 TTL=1 ID=59465 PROTO=2 
Feb 13 01:54:01 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=01:00:5e:7f:ff:fa:9c:d6:43:c4:bc:c0:08:00 SRC=192.168.0.110 DST=239.255.255.250 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2 
Feb 13 01:54:04 systemd[2836]: gnome-terminal-server.service: Succeeded.
Feb 13 01:54:04 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=30:9c:23:df:13:2a:8a:fe:69:01:19:1f:08:00 SRC=192.168.0.25 DST=192.168.0.3 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21155 DF PROTO=TCP SPT=45182 DPT=1716 WINDOW=65535 RES=0x00 SYN URGP=0 
Feb 13 01:54:05 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=01:00:5e:00:00:fb:64:52:99:9c:cb:26:08:00 SRC=192.168.0.8 DST=224.0.0.251 LEN=32 TOS=0x00 PREC=0x00 TTL=1 ID=50837 PROTO=2 
Feb 13 01:54:06 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=30:9c:23:df:13:2a:8a:fe:69:01:19:1f:08:00 SRC=192.168.0.25 DST=192.168.0.3 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21156 DF PROTO=TCP SPT=45182 DPT=1716 WINDOW=65535 RES=0x00 SYN URGP=0 
Feb 13 01:54:07 systemd[1]: Starting Download data for packages that failed at package install time...
Feb 13 01:54:07 systemd[1]: update-notifier-download.service: Succeeded.
Feb 13 01:54:07 systemd[1]: Finished Download data for packages that failed at package install time.
Feb 13 01:54:08 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=30:9c:23:df:13:2a:8a:fe:69:01:19:1f:08:00 SRC=192.168.0.25 DST=192.168.0.3 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21157 DF PROTO=TCP SPT=45182 DPT=1716 WINDOW=65535 RES=0x00 SYN URGP=0 
Feb 13 01:54:08 anacron[1213]: Job `cron.daily' started
Feb 13 01:54:08 anacron[13379]: Updated timestamp for job `cron.daily' to 2021-02-13
Feb 13 01:54:08 cracklib[13411]: no dictionary update necessary.
Feb 13 01:54:09 systemd[2836]: tracker-extract.service: Succeeded.
Feb 13 01:54:12 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=30:9c:23:df:13:2a:8a:fe:69:01:19:1f:08:00 SRC=192.168.0.25 DST=192.168.0.3 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21158 DF PROTO=TCP SPT=45182 DPT=1716 WINDOW=65535 RES=0x00 SYN URGP=0 
Feb 13 01:54:16 gjs[13284]: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
Feb 13 01:54:20 kernel: [UFW BLOCK] IN=enp34s0 OUT= MAC=30:9c:23:df:13:2a:8a:fe:69:01:19:1f:08:00 SRC=192.168.0.25 DST=192.168.0.3 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21159 DF PROTO=TCP SPT=45182 DPT=1716 WINDOW=65535 RES=0x00 SYN URGP=0 
Feb 13 01:54:22 anacron[1213]: Job `cron.daily' terminated
Feb 13 01:54:22 anacron[1213]: Normal exit (1 job run)
Feb 13 01:54:22 systemd[1]: anacron.service: Succeeded.
Feb 13 01:54:23 gjs[13284]: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed`

Have reinstalled GSConnect, deleted all settings related folders including kdeconnect folders, have reinstalled the android app, have tried connecting directly thru IP address, etc...

running pidof gives me 21739

running lsof -i UDP:1716
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gjs     21919 admin   18u  IPv6 269403      0t0  UDP *:1716

kdeconnec doesn't seem to appear in lsof despite being installed?

**Comment by andyholmes** [comment]
GSConnect probably won't work if KDE Connect is installed, you should either use KDE Connect or GSConnect on your desktop, not both.

It seems like UFW is complaining a lot. Are you sure you have allowed ports 1716-1764 for TCP & UDP?

**Comment by GitThisBugOff** [comment]
> W is complaining a lot. Are you sure you have allowed ports 1716-1764 for TCP & UDP?

I managed to fix this by manually adding a rule for port 1716!
