### ISSUE TITLE
Notification toasts do not persist onscreen for long enough to read

### ISSUE THREAD

**Issue by OMG-PIMA** [GSConnect/gnome-shell-extension-gsconnect#1061]
Notification toasts do not persist on screen long enough to be useful, especially if there are several toasts to show

**Steps To Reproduce:**

1. Set up gsconnect to receive text notifications from a smartphone
2. Send at least 3 texts in rapid succession to the phone

**Expected behavior**
A toast should be shown for each text with time to read the toast
Instead the toast appears for any time between <1s to 10s
Be nice if the toast show times were configurable (e.g 5s per)

**System Details (please complete the following information):**

 - **GSConnect version 44
 - **Installed from: GNOME Extensions Website
 - **GNOME/Shell version: 3.38.3
 - **Distro/Release: Pop!OS 20.10

 - **Paired Device(s): Pixel 4a

**Comment by andyholmes** [comment]
This behaviour is controlled by GNOME Shell, so can't be fixed in GSConnect. Sorry about that.
