### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by gabrc52** [GSConnect/gnome-shell-extension-gsconnect#1063]
**Describe the bug**

The same notification sometimes appears more than once. It has bugged me for some time, but I'm still not sure about the steps to reproduce.

**Steps To Reproduce:**

1. Receive a notification on your phone, and don't dismiss it
2. Lose the connection between the phone and GSConnect somehow, for instance, disconnect and reconnect from the network in either device
3. The notification may appear again

**Expected behavior**

A notification that already appeared once should not reappear more than once.

**Screenshots**

No screenshots, but if you need additional info to reproduce, I could make a screen recording, do some more testing and clarify the steps.

**Support Log**

I attempted to reproduce it manually to no avail, but if there's any way of having GSConnect generate a log all the time, I could post it, since there may be minutes or hours between the duplicate notifications.

**System Details (please complete the following information):**

 - **GSConnect version:** 44
   - **Installed from:** GNOME extensions website
 - **GNOME/Shell version:** 3.38.3
 - **Distro/Release:** Pop!_OS (Ubuntu) 20.10

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Redmi Note 8 (LineageOS)
 - **KDE Connect app version:** 1.16.0 
 - **Plugin(s):** Notification sync

**Additional Notes:**

The time it took for a duplicate notification to appear is the same time that it took to attempt to get a support log and fill in the system details, and GSConnect environment (about 5 minutes), but the last time the notification appeared was about 20-30 minutes ago.

Sometimes the duplicate notifications appear without switching the network connection. Device doze/battery saving measures may cause a disconnection between KDE Connect on the phone and GSConnect on the computer.

**Comment by andyholmes** [comment]
Duplocate of #789
