### ISSUE TITLE
kdeconnect.photo.request doesn't do anything ('Photo' menu option/shortcut)

### ISSUE THREAD

**Issue by GitGangGuy** [GSConnect/gnome-shell-extension-gsconnect#1066]
**Describe the bug**

After triggering the 'Photo' plugin (to shoot a picture remotely via the Camera app), nothing happens, regardless of how I start it (over the menu, a shortcut, etc). It logs that a `kdeconnect.photo.request` has been sent, but it appears to do nothing. Is this feature not ready yet?

**Steps To Reproduce:**

1. Open the GSConnect menu in the panel
2. Click on 'Photo'
4. Nothing happens on my smartphone

**Expected behavior**

1. Opens my default camera app (Google Camera)
2. Shoots a photo when Google Camera is open
3. Saves that photo to my `~/Pictures`

**Support Log**
```
GSConnect: 44 (user)
GJS:       16602
Session:   wayland
OS:        Arch Linux
--------------------------------------------------------------------------------
-- Journal begins at [...] --
[...] org.gnome.Shell.Extensions.GSConnect[2391]: [/service/device.js:sendPacket:446]: Pixel 5: {
    "id": 1615984269029,
    "type": "kdeconnect.photo.request",
    "body": {}
}
[...]
```

**System Details (please complete the following information):**

 - **GSConnect version:** 44
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.38.4
 - **Distro/Release:** Arch Linux (rolling release)

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Google Pixel 5 running a de-googled ROM (CalyxOS) with microG (Google Framework replacement layer)
 - **KDE Connect app version:** 1.16
 - **Plugin(s):** Photo plugin / `kdeconnect.photo.request`

**Comment by andyholmes** [comment]
It looks like GSConnect is doing everything it's supposed to here. You may want to report a bug upstream at https://bugs.kde.org.

**Comment by andyholmes** [comment]
Closing, since GSConnect seems to be doing everything correctly.

For reference, upstream issue is here: https://bugs.kde.org/show_bug.cgi?id=437995
