### ISSUE TITLE
Bump metadata.json for gnome-shell 40

### ISSUE THREAD

**Issue by jnsh** [GSConnect/gnome-shell-extension-gsconnect#1069]
GSConnect seems to work in gnome-shell 40 without issues (based on short and noncomprehensive testing), but it should also be included in the supported `shell_version` list in `metadata.json`.

**Comment by andyholmes** [comment]
There's probably nothing broken, I would guess.

What I used to do at this time was branch off `gnome-3-38`, leaving `master` for GNOME 40. Likewise a new CI should be added for `gnome-3-38` and the image for master updated to `fedora:34`.

**Comment by xeu100** [comment]
Should be noted that this does not work for Fedora 34 on a fresh installation due to an issue with missing ciphers.

**Comment by andyholmes** [comment]
> Should be noted that this does not work for Fedora 34 on a fresh installation due to an issue with missing ciphers.

Can elaborate on that? Is there something Fedora users need to install (other than openssl) that fixed this for you?

**Comment by xeu100** [comment]
> > Should be noted that this does not work for Fedora 34 on a fresh installation due to an issue with missing ciphers.
> 
> Can you elaborate on that? Is there something Fedora users need to install (other than openssl) that fixed this for you?

I haven't been able to find a fix, I'll attach a debug log when I can. I researched the issue and didn't see anything to fix it, might be a change in F34 that was missed.

**Comment by lverissimo** [comment]
I confirm that it is not working on Fedora 34.

**Comment by jnsh** [comment]
Sorry I may be missing something, but I don't understand what the F34 issue has to do with this. I opened a bug just to notify about bumping the `metadata.json` version, although discussions about any GNOME 40 update related matters would surely be appropriate.

However the Fedora problem sounds like something completely unrelated ti this, and 100% distribution specific. Perhaps it should be reported and discussed in a separate issue?

**Comment by andyholmes** [comment]
> However the Fedora problem sounds like something completely unrelated to this, and 100% distribution specific. Perhaps it should be reported and discussed in a separate issue?

Opened as https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1071

**Comment by sonnyp** [comment]
done in https://github.com/GSConnect/gnome-shell-extension-gsconnect/commit/8b8b1c9d9006fefaf2aafc96295bb9438de7981c

@andyholmes thanks for the tips!

> What I used to do at this time was branch off gnome-3-38, leaving master for GNOME 40.

So you wouldn't try and support both versions on the same branch?

I imagine eog support parallel versions and that's why you would use different branches?

> Likewise a new CI should be added for gnome-3-38 and the image for master updated to fedora:34.

I found https://github.com/andyholmes/gsconnect-ci 

Is a separate repository necessary? I was thinking of copying the Dockerfile to ` GSConnect/gnome-shell-extension-gsconnect`.

**Comment by sonnyp** [comment]
I just realized branches are used in gsconnect-ci as well so it makes sense to keep it separate.

Would it make sense to move gsconnect-ci to GSConnect org or should I send a PR?

**Comment by andyholmes** [comment]
> So you wouldn't try and support both versions on the same branch?
> I imagine eog support parallel versions and that's why you would use different branches?

Not in the past no :) GSConnect has a *lot* of dependencies other than gnome-shell so it can be be quite annoying. So usually what I would do is branch `gnome-3.38` right now then move forward with GNOME 40 stuff on `master`.

> Is a separate repository necessary? Would it make sense to move gsconnect-ci to GSConnect org or should I send a PR?

I'm okay with either. If you move it or make a new repo, dockerhub will have to be updated though.
