### ISSUE TITLE
Extension doesn't work after updating gjs to 1.68.0

### ISSUE THREAD

**Issue by Noobsai** [GSConnect/gnome-shell-extension-gsconnect#1073]
After updating gjs to 1.68.0 the extension doesn't work. Device list is disappeared (stuck in a searching) and cannot connect to phone.
Downgrade back to 1.66.2 is resolved the problem.
Event log:
```
JS ERROR: TypeError: this._instance is undefined
_init@/gsconnect@andyholmes.github.io/service/utils/dbus.js:69:20
_exportDevice@/gsconnect@andyholmes.github.io/service/manager.js:295:26
_loadDevices@/gsconnect@andyholmes.github.io/service/manager.js:266:18
start@/gsconnect@andyholmes.github.io/service/manager.js:453:14
vfunc_startup@/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```
Maybe this gjs PR broke something: https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/591

**Comment by KonstantMan** [comment]
I think every one who uses GNOME with up to date distros like Arch has the exact same issue , kde connect works just fine so it's not a firewall problem

**Comment by daniellandau** [comment]
I'll try to get that fixed this weekend.

**Comment by daniellandau** [comment]
Indeed that PR seems to be related. If I remove the CONSTRUCT_ONLY flag on line 46 of dbus.js it starts working again.

@andyholmes did you have a specific reason to add that flag?

Probably anyways the correct fix would be to figure out the naming clash or whatever in detail, but I think the priority should be to get a fix out, so if there's no pressing reason to have that parameter be CONSTRUCT_ONLY I think that's the fix I'll go with.

**Comment by andyholmes** [comment]
> Probably anyways the correct fix would be to figure out the naming clash or whatever in detail, but I think the priority should be to get a fix out, so if there's no pressing reason to have that parameter be CONSTRUCT_ONLY I think that's the fix I'll go with.

Well it can only be set at construction, but we're not exactly publishing a library here so probably doesn't matter :)

It might be because I named the variable `_instance` while the property name is `g-instance`, thus maybe the variable should have been named `_g_instance`?
