### ISSUE TITLE
[RFC] GSConnect as a standalone app

### ISSUE THREAD

**Issue by sonnyp** [GSConnect/gnome-shell-extension-gsconnect#1081]
I would like to turn GSConnect into a standalone app. Here is a proposal. Any feedback welcome.

What it would be like:

* The current settings window/process and service would become the standalone app
* It would be a standard GNOME/gjs app - [see examples](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Home.md#standalone-applications)
* The default packaging system would be flatpak
* The default distribution channel would be flathub
* The GNOME Shell extension would be an "addon" just like the Firefox, Chrome and nautilus integrations

Of course packagers would be free and invited to continue distributing as they please.

Why:

* Discoverability - by being available on the various app centers we can increase visibility for this great project
* No breaking changes (on the app) when upgrading GNOME Shell / gtk / gjs
* Ease of development/maintenance
* Open usage outside of GNOME Shell (for features that do not require the extension) - including phosh, xfce, ...
* It's easier to increase the number of features in the app than in the shell panel which is becoming crowded
* gsconnect architecture is already pretty much setup for this!
* That's personal, but I'd rather have all the UI in a dedicated window/app than in the Shell (I'm not removing this though)

Challenges:

* The app will have to stay backward compatible with older versions of the GNOME Shell extension
* flatpak sandbox/permissions might be too restrictive - if so let's default to running on host - or try to get xdg portals to support our use cases - TBD
* list features and dependencies (should be easy to understand)

Future opportunities:

* Use a different language than JavaScript for the app or service (I'm happy with JavaScript for now though) see also [mconnect](https://github.com/bboozzoo/mconnect) and [gconnect](https://github.com/getzze/gconnect)
* Adapt the extension panel UI for the app
* First time run - install Chrome / Firefox / Shell extensions
* snap, flathub, elementary appcenter, ...
* Additional compositor integrations
* Possibly replace https://github.com/b4j4/indicator-kdeconnect (I don't use indicator myself)

See also https://github.com/hannesschulze/conecto/

**Comment by daniellandau** [comment]
Sounds exciting! What are the features that do require a shell extension?

**Comment by sonnyp** [comment]
I don't have an exhaustive list ATM. I added `* list features and dependencies (should be easy to understand)` to Challenges.

@daniellandau BTW did you get the dockerhub invitation ?

**Comment by daniellandau** [comment]
No I haven't done or gotten anything related to dockerhub, but let's maybe move that conversation to another issue or the Matrix channel.

**Comment by andyholmes** [comment]
Just an FYI: https://source.puri.sm/Librem5/phosh/-/issues/514

**Comment by Mannshoch** [comment]
I would propose to split it into a CLI and GUI (GUI depends on CLI) I'm looking for a good CLI app to use it for SmartHome purpose. I'm not able to use the current KDE-Connect application because of that limitation.
Things I wish to do with this tool:
 - deliver some message or questions on my phone/desktop (SmartHome with node-red)
 - Set SmartHome settings from Desktop 
 - Scan a connected Phone for new Pictures and import it into Shotwell
 - Sync Pictures that contain certain tags between phone and Shotwell

**Comment by sonnyp** [comment]
@Mannshoch it sounds really out of scope for this issue - perhaps even for GSConnect but feel free to open a separate issue.

**Comment by sonnyp** [comment]
Turns out @andyholmes has already started work on a standalone KDE Connect GTK app. https://github.com/andyholmes/valent .

There would be too much overlap so I will close this and contribute to Valent instead of working on this.

One possible outcome would be to reduce GSConnect scope to become the GNOME Shell integration of Valent.

**Comment by Mannshoch** [comment]
@sonnyp why is an application with CLI and GUI separated out of scope?

**Comment by andyholmes** [comment]
I assume he meant using a KDE Connect client as a smart home node.

The KDE Connect protocol is geared towards point-to-point connections, not really being part of a larger network. In any case, all the features you requested would have to be discussed upstream with KDE Connect team, then become a part of the protocol and finally implemented in GSConnect.

**Comment by Mannshoch** [comment]
I do not need any extra feature in KDE Connect. I only need a way to use it from a CLI that do not need any UI dependencies, so I'm able to Install it on a Raspbian without graphical environment. 
The most important part is the ability to send a Message to/from phone. 
May in future I'm interested in sending/receiving files and setup commands which I could use on phone.

**Comment by sonnyp** [comment]
A CLI interface is out of scope for the current (and now closed) issue `[RFC] GSConnect as a standalone app #1081` because it's unrelated.

Again, feel free to create a separate issue if you want to discuss this further.
