### ISSUE TITLE
GSConnect: TypeError

### ISSUE THREAD

**Issue by chandanvp** [GSConnect/gnome-shell-extension-gsconnect#1090]
I get a dialogue saying above error pop-up. When I click to show "Technical Details" its shows this error:

/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

get@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

I tried reinstalling the gnome-extension. Tried installing from a different browser as well as using the zip file from Releases page. Nothing seems to work. Any solutions for this?

**Comment by daniellandau** [comment]
Can you give us the system details as mentioned in the bug report template?

**Comment by chandanvp** [comment]
I couldn't find the bug report template. Anyways System Details are as follows:
OS - Pop_OS based on Ubuntu 20.10
DE - GNOME
WM - Mutter
Processor - Intel i5 quad core

**Comment by andyholmes** [comment]
What version of openssl do you have?

**Comment by chandanvp** [comment]
~ > openssl version                                                                                                                                                              
OpenSSL 3.0.0-alpha11 28 jan 2021 (Library: OpenSSL 3.0.0-alpha11 28 jan 2021)

Am having this version

**Comment by andyholmes** [comment]
Sorry, GSConnect doesn't support the output of OpenSSL 3.0.

I wouldn't expect support for that until a stable release of OpenSSL 3.0 is available, unless you want to contribute support yourself.

**Comment by chandanvp** [comment]
Which version of OpenSSL does GSConnect support ? I'll try to remove alpha and install a stable version on my machine.

**Comment by andyholmes** [comment]
As far as I know, most distributions should be using openssl-1.1.1. This appears to be what Ubuntu 20.10 is shipping as well.

**Comment by chandanvp** [comment]
My distro is also based on Ubuntu 20.10 But don't know why it has upgraded to Alpha version. Do you know any method to degrade the version?

 I tried googling some guides, but openssl is core component, Gnome and many other important things depend on it. I know its a little off-topic, If you know guide me. Else I'll have to wait untill support for alpha version is added

**Comment by andyholmes** [comment]
I'm don't know how off hand, but I'm sure if you google how to downgrade with `apt` you can find something. As far as I know `openssl-3.0` isn't in Ubuntu 20.10, so I'd guess it came from a PPA or other place.

**Comment by chandanvp** [comment]
Thanks for the information. I'll check to downgrade it with apt and will close the issue
