### ISSUE TITLE
Fingerprint verification is no longer accurate.

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gnome-shell-extension-gsconnect#1091]
Since a few months ago, KDE Connect stopped using a pair of SHA1 fingerprint hashes to confirm pairing, and now uses a SHA256 hash of the combination of both certificates.

This is unfortunate since it means any older version of KDE Connect or GSConnect connecting to an Android device will appear to be fraudulent. The affects all versions of GSConnect up to v46.

See:

* https://invent.kde.org/network/kdeconnect-kde/commit/e7518493df7398f27f7dffbfc3f79750bc1fda50
* https://invent.kde.org/network/kdeconnect-android/commit/d09ad45e112bf5ce5e50ab4bb0ed651dccdc8775

**Comment by Seplx** [comment]
Th fingerprints didn't match when I looked at the encryption info. Not sure if this is related or not.

**Comment by andyholmes** [comment]
Yup, that's one half of the issue.

**Comment by andyholmes** [comment]
Closed by #1493
