### ISSUE TITLE
Adjust Wiki: openssl not preinstalled in Fedora 34

### ISSUE THREAD

**Issue by Alexmitter** [GSConnect/gnome-shell-extension-gsconnect#1092]
https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Error#openssl-not-found only mentions Fedora Silverblue, but Fedora 34 Beta also does not ship openssl by default, it needs a `sudo dnf install openssl`

**Comment by sonnyp** [comment]
fixed https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Error#openssl-not-found

Many thanks for reporting.
