### ISSUE TITLE
Command edition is broken

### ISSUE THREAD

**Issue by SirHautdesrables** [GSConnect/gnome-shell-extension-gsconnect#1099]
Hello,

The Command panel is broken: clicking for edition of an existing command doesn't show any effect, as the '+' button for new command definition.
Already defined command seems to keep working, as the button for removing them. Unfortunately, Iremoved my only command, so I can't make more tests.

Here are the logs of some tries. Errors comes from GJS. The first happen when reaching the command menu, other ones while trying to add a function.

`
GSConnect: 46 (user)
GJS:       16800
Session:   wayland
OS:        Arch Linux
--------------------------------------------------------------------------------
-- Journal begins at Sun 2019-10-27 14:44:44 CET, ends at Mon 2021-04-12 21:08:00 CEST. --
Apr 12 21:07:32 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21
Apr 12 21:07:48 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21
Apr 12 21:07:50 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21
Apr 12 21:07:53 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21
Apr 12 21:07:55 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21
Apr 12 21:08:00 gjs[6374]: JS ERROR: TypeError: this.get_root is not a function
                           _onEditCommand@/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
                           @/home/etienne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21`

**Comment by andyholmes** [comment]
Thanks for reporting, this was already reported as #1095 and closed in #1096. You can grab a ZIP from the [CI artifacts](https://github.com/GSConnect/gnome-shell-extension-gsconnect/actions/runs/734221460) if you don't want to wait for a release.

**Comment by SirHautdesrables** [comment]
Sorry, I didn't noticed first report. 
Thank you for answering that fast. It works well :-)
