### ISSUE TITLE
Media player control issue - VLC seek playback

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [GSConnect/gnome-shell-extension-gsconnect#1106]
**Describe the bug**

When try to seek the playback via VLC via button, seek to forward works, but seek back will cause replay the whole video/audio again.

**Steps To Reproduce:**

1. Play video/audio via VLC
2. Open Media Player Control
3. Select the player (for me VLC)
4. Seek back the video via buttons (<<) icon

**Expected behavior**

Expect to seek the playback.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
It won't log anything
```

**System Details (please complete the following information):**

 - **GSConnect version:** 43
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.7
 - **Distro/Release:** Ubuntu 20.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** SM-J500H
 - **KDE Connect app version:** 1.16.0
 - **Plugin(s):** Media Playback

**Comment by andyholmes** [comment]
You will have to provide logs to get help with this problem. Please see [Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) in the wiki if you need help generating a log.

**Comment by AmirHosseinKarimi** [comment]
Hi @andyholmes , I tried to produce it when looking to log but it does not generate anything.
At least I described how to produce this issue, I think it can be produce every time, so if logging issue is from my side anyone produce it on their environment can generate log.

**Comment by andyholmes** [comment]
Without logs, I can only assume this is a error in VLC's MPRIS implementation.

Feel free to re-open if you can provide logs showing GSConnect doing something incorrect.
