### ISSUE TITLE
Port already in use at EVERY boot

### ISSUE THREAD

**Issue by tr1p0p** [GSConnect/gnome-shell-extension-gsconnect#1114]
Hi everyone.

So i stop using Gsconnect because it causing memory leak and seem to not work at every boot. And i mean : EVERY boot.

So after 4 months after uninstalling this extensions, i wanna try again : and it's seem thay're still this bug.

Steps To Reproduce:

1.Boot Pop OS LTS
2:Have the error that say port already in use
3.Solve it by follow the instructions from wiki.
4.Reboot your system.
5.Do that again and again during infinity

Expected behavior

Having instructions that actually SOLVE this issues and not just put bandage for the next reboot

**System Details (please complete the following information):**

 - **GSConnect version:** Last
   - **Installed from:** Gnome Manager Extension
 - **GNOME/Shell version:** 
 - **Distro/Release:** POP OS 20.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Redmi 8
 - **KDE Connect app version:** Last

**Comment by andyholmes** [comment]
Do you have KDE Connect installed?

**Comment by tr1p0p** [comment]
So.. Yeah i was dumb on this one it's seem KDE Connect was installed on my system. I was taking him for GSConnect  and for me it was a conflict between the two same process.

But it's weird, i don't have KDE, and i don't have any remember of installing KDE Connect in my computer. Was on GS Connect and suddenly this appear, always install with Gnome Extensions. Maybe i put too quick a sudo apt install from the web or something like that.

Anyways thanks ! Was worried if uninstalling KDConnect will create issues with GSConnect but now everything work great !
