### ISSUE TITLE
SFTP mount not working after losing connection

### ISSUE THREAD

**Issue by tamas646** [GSConnect/gnome-shell-extension-gsconnect#1115]
**Describe the bug**

Most of the time I cannot mount my phone's storage. I click on the "Mount" icon but nothing happens.

I discovered that the issue can be caused by a connection losing.

I also discovered that rebooting my android phone is solving the problem.

**Steps To Reproduce:**

1. Attach android phone with gsconnect (mounting works)
2. Turn off wifi on android
3. Turn wifi back on
4. Wait for gsconnect to find the phone
5. Click on the phone icon on the notification bar
6. Click "Mount"

**Expected behavior**

The app should mount the phone's storage.

**Support Log**

```

GSConnect Version: 28
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.30.2
 - **Distro/Release:** Debian 10

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Moto G(6) Plus
 - **KDE Connect app version:** 1.17.0

**Additional Notes:**

I also checked the android app's log via adb, but it gave me only these lines:

```
05-17 19:04:51.221 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:04:53.565 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:04:55.812 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:05:02.849 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:05:07.700 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:05:16.925 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
05-17 19:05:16.930 19556 19687 I ConnectivityReport: signalStrength of #1 updated to 1
05-17 19:05:24.165 19556 19687 I ConnectivityReport: signalStrength of #2 updated to 1
```

It seems that really nothing happens when I click the "Mount" button. :D

Could it be related to https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/478?

**Comment by andyholmes** [comment]
Sorry, but the version of GSConnect you are running is far too old to expect updates. I'd recommend you update your distribution and then GSConnect to see if the problem is resolved.

Feel free to re-open if the issue persists with a current version of GSConnect.

**Comment by tamas646** [comment]
@andyholmes I'm using the newest stable Debian distribution, therefore I cannot update it.
I think Debian is a very common linux distribution. Why is it not supported? :(

**Comment by andyholmes** [comment]
I made a short PSA about that on [Discourse](https://discourse.gnome.org/t/gsconnect-is-dropping-support-for-older-versions-of-gnome/2023) in 2019:

> Due largely to an increasing amount of problems especially with GNOME 3.28 it has become obvious that it is time to drop support for older versions of GNOME. Firstly, the disk space to keep their VMs running and the time to properly support them are both unrealistic (at least for me).
> 
> It has also meant we’ve been avoiding newer language features and libraries going back over two years now. Aside from awkward JS and GJS polyfills, we’ve had to maintain a number of pure JS implementations of GLib/Gio functions written in C that have been in wide circulation for years.
> 
> So the situation is that unless a volunteer offers to maintain support and field bug reports for older versions of GNOME, GSConnect will drop support for them in v28. Please message here or visit Github if you are interested and can commit the necessary time.

The simple fact is it's more work than one person could do and no volunteers came forward.

**Comment by tamas646** [comment]
I see. I'm sorry to hear that.

**Comment by alexanderadam** [comment]
I'm using GSConnect 45 on Gnome 3.38.5 / Ubuntu 21.04.
Is this also too old?

So far I always had this issue (I _though_ I mentioned it at one point but maybe I'm simply mistaken :laughing: ?).

The fix I'm always doing is clicking `Turn Off` and `Turn On` again from GSConnect menu.
This works reliably for me.

I believe this happens after my machine's going to sleep/suspend/hibernate and waking it up again.

**Comment by andyholmes** [comment]
Most of the SFTP connection is done by GVfs; all we really do is pass it the IP, port and TLS certificate. It will probably take some [debugging](https://wiki.gnome.org/Projects/gvfs/debugging) on your end to find out what's going wrong.

**Comment by alexanderadam** [comment]
Can I somehow enforce the things that are happening when clicking `Turn Off` and `Turn On` again via command line interface?
This way I'd be able to simply add this as a cronjob.

**Comment by andyholmes** [comment]
There's no way to replicate restarting the service without actually doing it, if that's what you're asking.

**Comment by alexanderadam** [comment]
> There's no way to replicate restarting the service without actually doing it, if that's what you're asking.

Okay. It seems that it stopped working anyway. I cannot get my devices to mount any more. Neither via the `Mount` menu entry nor by turning GSConnect off and on again.
It's also not working after a restart neither.
Debugging didn't help. Various applications can successfully mount and their debug info will appear in the log but GSConnect won't write a single entry. :man_shrugging: 

Functionality like messaging works flawlessly though.

**Comment by andyholmes** [comment]
As mentioned before, all GSConnect does is pass the information to GVfs to handle the mounting. You'll likely have to [debug GVfs](https://wiki.gnome.org/Projects/gvfs/debugging) to get any information related to the actual SFTP connnections.

**Comment by alexanderadam** [comment]
> You'll likely have to [debug GVfs](https://wiki.gnome.org/Projects/gvfs/debugging) to get any information related to the actual SFTP connnections.

Sorry that I forgot to answer.

When I'm starting `gvfs` with log output:

```bash
GVFS_SMB_DEBUG=10 GVFS_DEBUG=1 $(find /usr/lib* -name gvfsd 2>/dev/null) --replace 2>&1 | tee gvfsd.log
```

And I click `Mount` in the menu of `GSConnect` nothing appears in the log.
Also `Generate Support Log` doesn't seem to add new log entries after clicking `Mount`.

Would it be possible to get the mount command somehow?

**Comment by andyholmes** [comment]
> And I click Mount in the menu of GSConnect nothing appears in the log.

You might want to just drop the `2>&1 | tee gvfsd.log` and let it run into a terminal. That way you can watch the output in real time.

> Would it be possible to get the mount command somehow?

There is no mount command in GSConnect, since it's done programmatically via Gio APIs. If you can get the host and port from the log you can try something like:

    $ gio mount sftp://kdeconnect@192.168.0.100:1739

That command will basically call the same DBus APIs GSConnect does.

**Comment by alexanderadam** [comment]
> You might want to just drop the `2>&1 | tee gvfsd.log` and let it run into a terminal. That way you can watch the output in real time.

I did that but it still doesn't show anything when I click on `Mount`.

So GSConnect claimed in its settings that it is connected but when I did `gio mount sftp://kdeconnect@192.168.0.100:1739` (I used the correct IP) I saw

```
Identity Verification Failed
Verifying the identity of “[192.168.0.100]:1739 ([192.168.0.100]:1739)” failed, this happens when you log in to a computer the first time.

The identity sent by the remote computer is “SHA256:…”. If you want to be absolutely sure it is safe to continue, contact the system administrator.
[1] Log In Anyway
[2] Cancel Login
Choice: 1
Authentication Required
Enter password for “kdeconnect” on “192.168.0.100”:
Password:
```

And I got exactly the same message when I tried to enter `sftp://192.168.0.100:1747/` in Nautilus (it's also asking for credentials here).


I don't know the password though. I think I read some time ago a comment from you that the password is random anyway, right?

I also tried to unpair and pair again but it didn't help.
It's also interesting that another device works perfectly and I also checked for file expose permission.

**Comment by andyholmes** [comment]
The password should be in the same debug log you got the IP and port for, although if it's asking for a password there's something else going wrong. GSConnect uses public key authentication so the Android SFTP server shouldn't be asking for it, unless the app is very old or there is a bug.

Unfortunately unless GSConnect is throwing an actual error, there's not much to be fixed here. We just take what KDE Connect Android gives us and hand it off to Gvfs.

**Comment by alexanderadam** [comment]
> The password should be in the same debug log you got the IP and port for

I didn't get these infos from a log. I took the command you provided above and checked for the IP manually.
Where could I get the debug log from? On the mobile phone or from GSconnect?

**Comment by andyholmes** [comment]
[Help/Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) :slightly_smiling_face:

**Comment by alexanderadam** [comment]
> [Help/Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) :slightly_smiling_face:

It doesn't show any useful information to me :disappointed: 

This seems to be the complete log (even after clicking `Mount`).
I don't see any credentials in that.

```

GSConnect: 45 (user)
GJS:       16702
Session:   x11
OS:        Ubuntu 21.04
--------------------------------------------------------------------------------
-- Journal begins at Thu 2021-05-13 10:24:41 CEST, ends at Sun 2021-09-26 11:24:15 CEST. --
Sep 26 11:24:08 gjs[840208]: Theme parsing error: gtk.css:6342:10: 'height' is not a valid property name
Sep 26 11:24:09 dbus-daemon[3026]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.1238' (uid=1000 pid=840208 comm="gjs /home/user/.local/share/gnome-shell/e" label="unconfined")
Sep 26 11:24:09 systemd[1]: Starting Hostname Service...
Sep 26 11:24:09 dbus-daemon[3026]: [system] Successfully activated service 'org.freedesktop.hostname1'
Sep 26 11:24:09 systemd[1]: Started Hostname Service.
Sep 26 11:24:15 dbus-daemon[5665]: [session uid=1000 pid=5665] Activating service name='org.gnome.gedit' requested by ':1.5037' (uid=1000 pid=840208 comm="gjs /home/user/.local/share/gnome-shell/e" label="unconfined")
Sep 26 11:24:15 dbus-daemon[5665]: [session uid=1000 pid=5665] Successfully activated service 'org.gnome.gedit'
Sep 26 11:24:15 gedit[840244]: Theme parsing error: gtk.css:6342:10: 'height' is not a valid property name
Sep 26 11:24:15 gnome-shell[5972]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x30001ac
```

**Comment by andyholmes** [comment]
Hmm, that sounds like the Android phone is not responding to requests to mount. Have you tried force closing the app?
