### ISSUE TITLE
"Transfer Failed" when sending files from GSConnect to KDE Connect (TLS SNI support missing)

### ISSUE THREAD

**Issue by ziadloo** [GSConnect/gnome-shell-extension-gsconnect#1136]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

I have a desktop with Manjaro-Gnome on it and a laptop with Manjaro-KDE. When I send a file from KDE to Gnome, it is sent without an issue but when I send a file from Gnome to KDE, it fails. Of course, on Gnome I have the GSConnect and on KDE I have KDE Connect. I've disabled firewalls on both machines to make sure that it's not blocking the connection.

It is worth mentioning that I can send files from both machines to my Android device without any problems. Also, when I send the file from Gnome to KDE, the notification appears on the KDE with a progress bar as if it's preparing the process but it doesn't get anywhere. And the failed error message has already been shown on the Gnome side.

**Steps To Reproduce:**

1. Go to GSConnect
2. Select a **computer** to send a file to and make sure it's a KDE Linux with KDE Connect on it
3. Click on "Share file"
4. See error "Transfer Failed. Failed to send ...."

**Expected behavior**

The file to be sent to to the other computer

**Screenshots**

Not applicable

**Support Log**

```
GSConnect: 45 (system)
GJS:       16801
Session:   x11
OS:        Manjaro Linux
--------------------------------------------------------------------------------
-- Journal begins at Wed 2021-06-02 13:36:36 EDT, ends at Mon 2021-06-28 17:38:00 EDT. --
Jun 28 17:37:36 gnome-shell[7184]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c00064
Jun 28 17:37:57 dbus-daemon[618]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.212' (uid=1000 pid=7529 comm="gjs /usr/share/gnome-shell/extensions/gsconnect@an")
Jun 28 17:37:57 audit: BPF prog-id=43 op=LOAD
Jun 28 17:37:57 audit: BPF prog-id=44 op=LOAD
Jun 28 17:37:57 audit: BPF prog-id=45 op=LOAD
Jun 28 17:37:57 systemd[1]: Starting Hostname Service...
Jun 28 17:37:57 kernel: audit: type=1334 audit(1624916277.324:553): prog-id=43 op=LOAD
Jun 28 17:37:57 kernel: audit: type=1334 audit(1624916277.324:554): prog-id=44 op=LOAD
Jun 28 17:37:57 kernel: audit: type=1334 audit(1624916277.324:555): prog-id=45 op=LOAD
Jun 28 17:37:57 dbus-daemon[618]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jun 28 17:37:57 systemd[1]: Started Hostname Service.
Jun 28 17:37:57 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 28 17:37:57 kernel: audit: type=1130 audit(1624916277.350:556): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 28 17:37:59 org.gnome.Shell.Extensions.GSConnect[7529]: [/service/device.js:_readLoop:338]: Galaxy S8: {
                                                              "id": 1624915915795,
                                                              "type": "kdeconnect.battery",
                                                              "body": {
                                                                "currentCharge": 86,
                                                                "isCharging": false,
                                                                "thresholdEvent": 0
                                                              }
                                                            }
Jun 28 17:38:00 org.gnome.Shell.Extensions.GSConnect[7529]: [/service/backends/lan.js:_handshake/</<:595]: Delbar: Error performing TLS handshake: A disallowed SNI server name has been received.
                                                            _handshake/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:595:44
                                                            @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**System Details (please complete the following information):**

 - **GSConnect version:** 45
   - **Installed from:** Pacman Package Manager - Official community repository
 - **GNOME/Shell version:** 40.1.0
 - **Distro/Release:** Manjaro

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Manjaro KDE
 - **KDE Connect app version:** kdeconnect 21.04.1
 - **Plugin(s):** 

**Additional Notes:**

Just to reiterate, the problem is only one way. I can successfully send files from KDE to Gnome but when I try to send files from Gnome (GSConnect) to KDE, it fails. This is while the same GSConnect can send files to my Galaxy S8 (on the same network) without any issues.

Also, the other functionalities like ringing or sharing the clipboard work both ways.

**Comment by andyholmes** [comment]
This seems like a rare problem that comes up once in awhile. The effective cause is this:

```
Error performing TLS handshake: A disallowed SNI server name has been received.
```

Apparently glib-networking, which provides the underlying TLS support in GSConnect, does not support server side [SNI](https://www.cloudflare.com/en-ca/learning/ssl/what-is-sni/). The Upstream bug report can be found here: [GNOME/glib-networking!24](https://gitlab.gnome.org/GNOME/glib-networking/-/issues/24).

If you're looking for a workaround that doesn't require that bug to be fixed, I would try to find out why SNI is required in your local network configuration. The linked article by Cloudflare above might be able to help with that. The only common reason I know of this being used on desktops is when running inside a VM.

**Comment by andyholmes** [comment]
Closing, since this is an upstream bug that can't be fixed in GSConnect.

**Comment by lili2012** [comment]
I used proxy on my computer and showed this failure. It transferred successfully after I turn of proxy.

**Comment by andyholmes** [comment]
Thanks for checking back! I always wondered why this error was occurring for some and not others,

**Comment by ziadloo** [comment]
As the original issue reporter, I can confirm that for me this had nothing to do with VPN/proxy since I didn't have any. Right now, I don't have a Gnome desktop to verify if this is still happening or not. In fact, one of the reasons why I stopped using Gnome was this problem.
