### ISSUE TITLE
[Feature Request] Retain Reply Button in Notification List (Make it easier to use Signal et al)

### ISSUE THREAD

**Issue by msoose** [GSConnect/gnome-shell-extension-gsconnect#1137]
**Is your feature request related to a problem? Please describe.**
When using Signal or other "proprietary" messengers who use their own database or don't offer/use an API or similar, messages can not be initiated, however they can be replied to:

* Message from Signal arrives on mobile device
* Notification is displayed on endpoints running GSConnect / KDEConnect
* Can **only** reply to message once using the short-lived Gnome notification popup, once this is gone, Replying isn't possible (?)
* Can not reply again until notification is dismissed / marked as read, and the other party sends a new message

**Describe the solution you'd like**
In the standard GSConnect Gnome "Notification Popup" with "Mark read" and "Reply", messages from Signal and other proprietary messengers can be sent and conversations can be held. Is it feasible/possible to leave the "Reply" button in the Gnome notification list for messages that have not be dismissed? This would allow fairly seamless conversations:

* Message from Signal arrives on mobile device
* Notification is displayed on endpoints running GSConnect / KDEConnect
* Can reply to message once using the short-lived Gnome notification popup
> *  Can this timeout be adjusted?
* Notification popup times out, and message is in the notification list, **with** existing "Mark read" and "Reply" buttons
* Notification stays in the notification list until it is dismissed, so more messages can be sent, instead of waiting for the other party to reply

**Describe alternatives you've considered**
Since there will likely be no full integration for apps (like Signal) who use encrypted databases for reading and writing data to, this is clearly a hacky/ugly/kludgy workaround for allowing some semblance of "integration" with other messengers.

**System Details (please complete the following information):**
N/A

**Additional context**
Input requested!

**Comment by rohmishra** [comment]
This is a limitation of work on gnome notification. There was some work done by gnome to revamp notifications but it seems work on it has been stalled.

**Comment by andyholmes** [comment]
It should also be pointed out that it is quite impossible to have a persistent "reply" entry for these notifications. Each repliable notification is tied a specific UUID corresponding to a particular event/message on the remote device. It's simply not possible to send arbitrary responses by this mechanism.

Going to go ahead and close this one up, since it's just not possible to fix here, sorry.
