### ISSUE TITLE
Clipboard not send from android to fedora

### ISSUE THREAD

**Issue by rungis86** [GSConnect/gnome-shell-extension-gsconnect#1152]
**Describe the bug**

Hello, sorry for my english level.
When I copy something in the clipboard on my fedora, I can use in Android, it's OK.
But when I copy something on my Android device (Pixel 5), it's not in my clipboard on my fedora.

I have activate the option in GSConnect.

I don't know if I can find logs in Android or Fedora to help developers.

Thanks

Rémi

**System Details (please complete the following information):**

 - **GSConnect version: 47 installed from GNOME Extensions Website (not sure for the installation)
 - **GNOME/Shell version: 40.3
 - **Distro/Release: Fedora 34

**GSConnect environment (if applicable):**

 - **Paired Device(s): Pixel 5 (Android 11)
 - **KDE Connect app version: 1.17

**Comment by ferdnyc** [comment]
@rungis86 

A [permissions change was made](https://developer.android.com/about/versions/10/privacy/changes#clipboard-data) starting with Android 10:

> #### Limited access to clipboard data
> Unless your app is the default input method editor (IME) or is the app that currently has focus, your app cannot access clipboard data on Android 10 or higher.

Since KDE Connect is basically never the foreground app (and, certainly, is _never_ the foreground app when you copy text), it can no longer capture and share the clipboard.

**Comment by rungis86** [comment]
Thank you @ferdnyc 
I didn't know this privacy change... It was so usefull...

**Comment by ferdnyc** [comment]
@rungis86 

Yeah, it is too bad. But I definitely understand why they did it. (If KDE Connect can spy on your clipboard, then any app can spy on your clipboard, and considering how often people copy/paste sensitive things like passwords, credit card numbers, etc...)
