### ISSUE TITLE
Not getting notifications from the computer on the phone

### ISSUE THREAD

**Issue by ricardofunke** [GSConnect/gnome-shell-extension-gsconnect#1153]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

The notifications from the computer are not shown on the phone, just in the opposite direction.

**Steps To Reproduce:**

(not applicable?)

**Expected behavior**

With the notification plugin installed on both sides and all notifications sharing enabled, the expected behavior is to see on the phone all the notifications from the computer

**Screenshots**

(not applicable)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

Couldn't see any related message in the logs
```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 45
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.38.5
 - **Distro/Release:** Kali GNU/Linux 2021.2

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Xiaomi POCO X3
 - **KDE Connect app version:** 1.17.0
 - **Plugin(s):** built-in notification plugin

**Additional Notes:**

I'm not sure if it's about a bug, environment particularity, or settings, please I beg your pardon, I just want to notify you about it, I ask your guidence

**Comment by andyholmes** [comment]
Please check the settings in the Android app to confirm you have **Receive notifications** enabled.

![Screenshot_20210819-124007](https://user-images.githubusercontent.com/1265208/130133637-a1cd87e4-943b-4670-b4ce-3631b8b2ce76.png)

**Comment by andyholmes** [comment]
Closed due to lack of activity
