### ISSUE TITLE
PulseAudio Not Found

### ISSUE THREAD

**Issue by xpseudonym** [GSConnect/gnome-shell-extension-gsconnect#1154]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Bug description as per link provided by GSConnect error notification/ pop-up here:
[PulseAudio Not Found](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Error#pulseaudio-not-found)

**Steps To Reproduce:**

1. Installed v47 as per instructions here:
[Install to /usr/local](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1049#issuecomment-774782684)
(After removing v28)

**Expected behavior**

No bug as above.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 47 (system)
GJS:       16602
Session:   wayland
OS:        PureOS
--------------------------------------------------------------------------------
[0;1;39mHint: You are currently not seeing messages from other users and the system.[0m
[0;1;39m      Users in groups 'adm', 'systemd-journal' can see all messages.[0m
[0;1;39m      Pass -q to turn off this notice.[0m
-- Journal begins at Sun 2021-08-15 14:54:06 BST, ends at Wed 2021-08-18 18:47:42 BST. --
-- No entries --
```
I'm not sure this is very relavent - the error is thrown on login prior to being able to 'take any steps necessary to reproduce the problem'.

**System Details (please complete the following information):**

 - **GSConnect version:** 47
   - **Installed from:** As above, zip and local build as per [Install to /usr/local](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1049#issuecomment-774782684)
 - **GNOME/Shell version:** 3.38.5
 - **Distro/Release:** PureOS 10

**GSConnect environment (if applicable):**

 - n/a

**Additional Notes:**

Thanks!

**Comment by andyholmes** [comment]
Unless you have a good reason, you should really just install extensions from extensions.gnome.org.

Otherwise you should read the [Packaging](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Packaging) page in the Wiki and then consult the documentation for your distribution to ensure that you are passing the correct values for each option.

**Comment by xpseudonym** [comment]
Thanks @andyholmes,
Um, I followed your install instructions here: [Install to /usr/local](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1049#issuecomment-774782684).  Is that not correct?

**Comment by andyholmes** [comment]
That's how you tell `meson` to install to `/usr/local`. It's still your responsibility to ensure all other libraries and runtime paths are correctly set as described on the [Packaging](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Packaging) page.

**Comment by xpseudonym** [comment]
Hmm, okay.  Research :)

**Comment by andyholmes** [comment]
Out of curiosity, what is the reason you are installing to the system instead of from the website?

**Comment by xpseudonym** [comment]
It's not packaged for PureOS for some reason.  There's a whole raft of other gnome-extensions packages, see attached.
[extensions.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/7019278/extensions.txt)
I can't install from the website - web install is broken for flatpak and that's all that's all that's available from PureOS as far as WebExtensions enabled browsers go, [see here.](https://www.reddit.com/r/gnome/comments/nbxb09/flatpak_firefox_doesnt_recognize_chromegnomeshell/?sort=new).  I would use `gnome-extensions` if it would install to `/usr/local`, but even if it did I suspect it would suffer the same problems that `gnome-shell-extension-installer` did, see [here](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1049#issuecomment-774801783).

**Comment by andyholmes** [comment]
Why is it necessary to install to `/usr/local` though? Just download the [release and install it](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip):

    gnome-extensions install --force gsconnect@andyholmes.github.io.zip

This is exactly what happens when you install from the website. You can even just use `unzip`:

    unzip gsconnect@andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io

Or if you're brave just install a build of [Annex](https://github.com/andyholmes/annex), which works in a flatpak.

**Comment by xpseudonym** [comment]
> Why is it necessary to install to /usr/local though?

Because I have more than one user and the idea of having to do separate installs for each user is just plain ugly.  `/usr/local` is made for the job, so I'd like to be able to use it... :-)

**Comment by andyholmes** [comment]
Ah gotcha, well good luck then.

**Comment by xpseudonym** [comment]
:o)
Thx
