### ISSUE TITLE
Recursive notifications

### ISSUE THREAD

**Issue by Netherquark** [GSConnect/gnome-shell-extension-gsconnect#1156]
SUMMARY
    KDE Connect creates a recursive loop of notifications
This issue is using GSConnect, but it is platform agnostic, so I am creating an issue here.

Whenever I get a notification on my desktop, like "Discord: phantom_bug sent you a message", the notification is mirrored on my phone. But, then, KDE Connect mirrors its own notifications. This means, on my desktop, I see "Discord: phantom_bug sent you a message", and "KDE Connect: Discord: phantom_bug sent you a message". Ocassionally, GSConnect/KDE Connect on PC mirrors this notification to my phone too, which repeats the whole loop. In my opinion, the easiest fix for this is to blacklist the app from the notification plugin by default, on both Android and the desktop version.

STEPS TO REPRODUCE
1. Setup KDE Connect using Android + any Linux distro with GNOME

OBSERVED RESULT
Inception of sorts.

SOFTWARE/OS VERSIONS
Phone: Xiaomi Redmi Note 9 Pro(A11)
       Latest version of KDE Connect (from Google Play)
Device: Desktop running Manjaro (5.10.59-1-MANJARO)(GNOME 40.3)
        Latest version of GSConnect (from extensions.gnome.org)

Mirror of [this](https://bugs.kde.org/show_bug.cgi?id=441160).

**Comment by andyholmes** [comment]
GSConnect already ignores it's own notifications, so this is probably a bug in KDE Connect Android:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/5d282f71fc3410f33438fd65d84379ba32d4d10a/src/service/components/notification.js#L385-L388

**Comment by Netherquark** [comment]
Okay I'll close this for the time being then.

**Comment by andyholmes** [comment]
Okay, thanks for checking back. Feel free to re-open if you discover something indicating our guard above is not working.
