### ISSUE TITLE
Command presets

### ISSUE THREAD

**Issue by aha999** [GSConnect/gnome-shell-extension-gsconnect#1170]
**Is your feature request related to a problem? Please describe.**
Currently there's no command presets in GSConnect to select from, but you have to insert every command manually.

**Describe the solution you'd like**
In the Commands menu in GSConnect program, make it an option where we can select from some of the basic (or advanced) commands to be added, without having to enter them manually. Commands like:
- Shutdown
- Restart
- Lock screen
- Unlock screen 
- Suspend, etc.

**System Details (please complete the following information):**
 - GSConnect version: 45
   - Installed from: extensions.gnome.org

**Additional context**
In Kde Connect you can select from such command presets that i listed... i'm asking if GSConnect could have such a preset list, where by clicking on the option would add it. It would be very useful, especially for Linux users like myself, who don't know terminal commands, And it could also be useful for advanced users, because it's more convenient than typing every command.

**Comment by pesader** [comment]
Hi! I'd like to work on this issue. I have an idea for the implementation and would like to know if that sounds good for the maintainers:

1. Upon connection, check if the `runcommand` plugin is supported and enabled
2. If so generate commands for Lock, Log Out, Power Off, Restart, and Suspend.
3. Save these commands to gsettings (`gsconnect/device/<DEVICE ID>/plugin/runcommand/command-list`).
4. Send the commands to the host.

Thanks in advance!

**Comment by andyholmes** [comment]
Probably the easier way would just be to add them here:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/2039513393da9279206c874abdda16ced427532e/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml#L151-L155

Since the IDs for user-defined commands are random UUIDs, you could just name them `lock`, `shutdown`, etc.

**Comment by pesader** [comment]
Thank you so much for pointing me in the right direction!
Following your advice, I was able to make a PR to solve this issue.
