### ISSUE TITLE
Show the adb logcat?

### ISSUE THREAD

**Issue by CryptoCashCashoo** [GSConnect/gnome-shell-extension-gsconnect#1173]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A command line of this kind : "gsconnect logcat" 

**Describe alternatives you've considered**
None

**Comment by andyholmes** [comment]
Sorry, this is out of scope for GSConnect.

Since KDE Connect runs on many different platforms and devices other than Android, this is a better fit for a development tool or new application.
