### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by rafadesign** [GSConnect/gnome-shell-extension-gsconnect#1177]
hello, I'm studying UX/UI Design and I wanted to contribute to the project in this sense and I can't get in touch with any project developer, how do I do it?

**Comment by daniellandau** [comment]
Either here on GitHub or in the Matrix channel is fine: https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Contributing#questions

**Comment by andyholmes** [comment]
Closing, since the question has been answered.
