### ISSUE TITLE
Support for Ubuntu LTS version

### ISSUE THREAD

**Issue by anishmittal2020** [GSConnect/gnome-shell-extension-gsconnect#1183]
**Is your feature request related to a problem? Please describe.**
Ubuntu 20.04 LTS has Gnome 3.36.8. Does the new release of GSConect support LTS version? As far as what I can see I am stuck at GSConnect v43. Can't update from [GNOME Shell Extensions](https://extensions.gnome.org/).

I am facing a lot of issues with GSConnect v43, and it has rendered unusable for me (it fills up syslog files to 30 GB size!).

**Comment by andyholmes** [comment]
No, the GSConnect project only supports the latest stable release of GNOME.

Unfortunately, while Canonical may have the resources to support a release for 4+ years, our maintainers and volunteers do not. With each release we [branch](https://github.com/GSConnect/gnome-shell-extension-gsconnect/branches) before moving forward and volunteers are always welcome to come forward and take over maintenance if that's something they think is worth the effort.

**Comment by anishmittal2020** [comment]
I understand your point. May be you could consider supporting the LTS versions for 2 years as a new LTS Version comes out every 2 years.

**Comment by daniellandau** [comment]
Maintainers as a rule will not port new features to old versions but bugs will be fixed on a best effort basis or as contributions from the community. The best effort of enterprise distributions is hopefully more than ours, but the basic principle is the same.

**Comment by anishmittal2020** [comment]
May I suggest an alternative. It might be possible to develop on freezing the gnome version as that of LTS and then developing on that till the next LTS Version is released.

**Comment by daniellandau** [comment]
New GNOME versions are significantly important to all the current maintainers, but I'd be more than happy to merge feature updates to older versions if someone steps up and does the porting work.
