### ISSUE TITLE
Error in Wiki page

### ISSUE THREAD

**Issue by 3ship** [GSConnect/gnome-shell-extension-gsconnect#1188]
[Location of the error](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features#files-extension)

Specifically this part:

> In order for the extension to work, you must have [the Python extension for your file manager](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#files-integration-nautilus--nemo-) (`nautilus-python` or `nemo-python`) installed.

The link in the quote doesn't lead to the correct target. Should be changed to:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#optional-features

Also, as mentioned in the correct link, `nautilus-python` is sometimes packaged as `python-nautilus`. The part in parentheses had me confused for a bit.

**Comment by sonnyp** [comment]
Fixed https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features#files-extension

Thanks
