### ISSUE TITLE
CLI Scripting won't work for the following options: --ping or --ring 

### ISSUE THREAD

**Issue by mahdiaqallal** [GSConnect/gnome-shell-extension-gsconnect#1191]
First, your Extension is simply awesome . What a wonderful work !

CLI Scripting won't work for the following options: --ping or --ring 

**Steps To Reproduce:**
**System Details: Fedora Silverblue 34 Gnome 40 and GSConnect extension version 47
**Paired Device(s):**  HUAWEI P Smart 2019 and Samsung Tab SM-T280

**Describe the bug**
$ cd ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/
$ ./daemon.js --ping or --ring won't produce any result

Moreover when twp devices are paired and connected, what sould be the syntax to send ping/ring to a specific device ?

**Expected behavior**
The designated divices (but how ?) should show a ping or ring CLI executed

**Comment by andyholmes** [comment]
Please see the Wiki page for [CLI Scripting](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/CLI-Scripting), then feel free to re-open if you are still encountering problems.
