### ISSUE TITLE
Nautilus context menu is suddenly gone

### ISSUE THREAD

**Issue by Smart-Helper** [GSConnect/gnome-shell-extension-gsconnect#1192]
I am using Gnome 3.36.9 on Ubuntu 20.04 LTS and i'm connected to an OnePlus 6t.

Everything worked fine and suddenly the context menu for nautilus to send pictures to the mobile device is gone.

I already tried disabling and re-enabling the plugin, restarting the computer and tried "nautilus -q" in the terminal.
Nothing worked and the context menu is missing. Sending files via the "send files" menu inside the app works perfectly fine. Receiving files from my phone also works fine.

this is the Help Protocol: https://pastebin.com/FDELVZyZ

Can someone help me out here?

**Comment by andyholmes** [comment]
Can you show the output of `nautilus -q && nautilus`?

**Comment by Smart-Helper** [comment]
im so sorry. I forgot to close this issue.

I dont exactly remember anymore if it worked or not. But i switched to manjaro thus i dont have the issue anymore.Thank you nonetheless.
