### ISSUE TITLE
Crowdin no longer syncs translations to Github

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gnome-shell-extension-gsconnect#1200]
**Describe the bug**

The Crowdin service was linked to `andyholmes/gnome-shell-extension-gsconnect`, but since being moved to `GSConnect/gnome-shell-extension-gsconnect` the integration between Github and Crowdin has broken.

I'm not sure, but it doesn't seem like Crowdin supports Github organizations or maybe it's just stuck on my account. Suggestions would be welcome since the translations are stuck until further notice.

cc @sonnyp @daniellandau @ferdnyc

**Comment by ferdnyc** [comment]
They have [a FAQ entry on that](https://support.crowdin.com/github-integration/)!

> ### Q&A
> Q: What should I do if my repository becomes a part of the GitHub organization?
> A: To continue using GitHub integration in Crowdin, follow these steps:
> 
> 1. Go to Authorized OAuth Apps in your GitHub account.
> 1. Find Crowdin OAuth App in the list and revoke its access.
> 1. Set up the GitHub integration in your Crowdin project again using the instructions above.
>

**Comment by andyholmes** [comment]
🤦 I can't believe I didn't see that! Syncing now, let's see how it goes :)

**Comment by andyholmes** [comment]
All good, thanks for the assist!
