### ISSUE TITLE
Not able to (auto)mount and reveice files

### ISSUE THREAD

**Issue by 7nn3** [GSConnect/gnome-shell-extension-gsconnect#1214]
**Describe the bug**

When trying to send a file from my phone the message 'Failed sending files to <name>' appears in the notification center.
Not able to mount sftp on computer.

Things I allready tried which didnt affected the problem: 
- enabling avahi service in systemd
- editing the ssh_config as mentioned in #1203 
- installing the extension via AUR/system repos (not by pasting)
- Editing my firewalld config: enable kdeconnect service and whitelisted port 1714-1764 upd and tcp

**Steps To Reproduce:**

- Boot up desktop (click Mount button in control center) and start nautilus for sftp mount
- Share various file on android phone
-> Notification: 'Failed sending file to <name>' 

**Expected behavior**

Storage shows up in nautilus / file transfer works

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

GSConnect: 48 (system)
GJS:       17000
Session:   wayland
OS:        Arch Linux
--------------------------------------------------------------------------------
-- Journal begins at Sat 2021-07-31 15:02:16 CEST, ends at Wed 2021-12-01 23:26:18 CET. --
Dez 01 23:26:06 gnome-shell[1092]: JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
                                   _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
Dez 01 23:26:06 gnome-shell[1092]: JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
                                   _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
Dez 01 23:26:13 systemd[1020]: Started Application launched by gnome-shell.
Dez 01 23:26:13 nautilus[2481]: libnautilus-cloud-extension.so init
Dez 01 23:26:13 nautilus[2481]: thread_start [271]:bind successfull for path = '/home/jnnk/.cloud-ipc-socket'
Dez 01 23:26:13 nautilus[2481]: thread_start [275]:running with sock 21.....
Dez 01 23:26:13 nautilus[2481]: setDumpCacheReady [95]:Set dump cache as ready
Dez 01 23:26:13 org.gnome.Nautilus.desktop[2481]: Initializing nautilus-image-converter extension
Dez 01 23:26:13 dbus-daemon[464]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbusorg.freedesktop.hostname1.service' requested by ':1.91' (uid=1000 pid=2481 comm="nautilus --new-window ")
Dez 01 23:26:13 audit: BPF prog-id=34 op=LOAD
Dez 01 23:26:13 audit: BPF prog-id=35 op=LOAD
Dez 01 23:26:13 audit: BPF prog-id=36 op=LOAD
Dez 01 23:26:13 systemd[1]: Starting Hostname Service...
Dez 01 23:26:13 dbus-daemon[464]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dez 01 23:26:13 systemd[1]: Started Hostname Service.
Dez 01 23:26:13 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dez 01 23:26:13 systemd[1020]: Started VTE child process 2520 launched by org.gnome.Nautilus process 2481.
Dez 01 23:26:13 nautilus[2481]: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5624447ca290
Dez 01 23:26:13 nautilus[2481]: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x56244452c870

(... repetition for around 100 lines with different values for 'handle=...', may be caused by further nutlius extensions I use)

Dez 01 23:26:13 nautilus[2481]: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x562444b11cd0
Dez 01 23:26:18 kernel: nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based firewall rule not found. Use the iptables CT target to attach helpers instead.

**System Details (please complete the following information):**

 - **GSConnect version:** 48
 - **Installed from:** AUR package: https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect/
 - **GNOME/Shell version:** 41.1
 - **Distro/Release:** Arch Linux 5.15.5-arch1-1

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus 6T running microG LineageOS 18.1, build release: late October
 - **KDE Connect app version:** 1.18.0
 - **Plugin(s):**

**Additional Notes:**

Add any additional information about the problem or your system.

Actually I can send files from my desktop to the phone...

**Comment by andyholmes** [comment]
This seems to be a jumble of several different functions -- can you clarify exactly how you're trying to transfer files and provide a log showing the failed attempt? Please see [Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) in the Wiki and be sure to follow each step carefully.

**Comment by 7nn3** [comment]
I did a software update on my smartphone and now the problem is gone. 
I'm sorry for bothering with your time and thanks for your great work :)
