### ISSUE TITLE
Latest GSConnect extension causes RHEL 8.5 GNOME to crash on screen lock

### ISSUE THREAD

**Issue by jbillingredhat** [GSConnect/gnome-shell-extension-gsconnect#1221]
**Describe the bug**

Installed the latest version of GSConnect (v28) on a RHEL 8.5 system running GNOME shell 3.32.2.  When I lock the computer, gnome-shell exits.  It appears to restart after I log back in.

**Steps To Reproduce:**

1. Install the latest RHEL 8.5 (or CentOS 8, Alma, Rocky, etc.)
2. Install the GSConnect extension from https://extensions.gnome.org/
3. Lock screen

**Expected behavior**

Extension should operate normally and I should be able to lock the screen.

**Support Log**

GSConnect Version: 28
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Mon 2021-11-22 04:22:04 EST, end at Thu 2021-12-09 13:43:02 EST. --
Dec 09 13:42:02 wpa_supplicant[2243]: wlp0s20f3: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-69 noise=9999 txrate=650000
Dec 09 13:42:13 gjs[5521]: GtkDialog mapped without a transient parent. This is discouraged.
Dec 09 13:42:17 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:18 dbus-daemon[1277]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.691' (uid=1001 pid=4745 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:18 systemd[1]: Starting Hostname Service...
Dec 09 13:42:18 dbus-daemon[3146]: [session uid=1001 pid=3146] Activating service name='org.gnome.Nautilus' requested by ':1.123' (uid=1001 pid=4745 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:18 dbus-daemon[3146]: [session uid=1001 pid=3146] Activating service name='org.freedesktop.FileManager1' requested by ':1.123' (uid=1001 pid=4745 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:18 dbus-daemon[3146]: [session uid=1001 pid=3146] Successfully activated service 'org.gnome.Nautilus'
Dec 09 13:42:18 dbus-daemon[1277]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 09 13:42:18 systemd[1]: Started Hostname Service.
Dec 09 13:42:18 org.freedesktop.FileManager1[3146]: Failed to register: Unable to acquire bus name 'org.gnome.Nautilus'
Dec 09 13:42:18 dbus-daemon[3146]: [session uid=1001 pid=3146] Activated service 'org.freedesktop.FileManager1' failed: Process org.freedesktop.FileManager1 exited with status 1
Dec 09 13:42:19 org.gnome.Shell.desktop[4745]: == Stack trace for context 0x5573cab84210 ==
Dec 09 13:42:19 systemd[1]: Started Process Core Dump (PID 5607/UID 0).
Dec 09 13:42:19 systemd-coredump[5609]: Resource limits disable core dumping for process 4745 (gnome-shell).
Dec 09 13:42:19 systemd-coredump[5609]: Process 4745 (gnome-shell) of user 1001 dumped core.
Dec 09 13:42:19 systemd[1]: systemd-coredump@1-5607-0.service: Succeeded.
Dec 09 13:42:19 polkitd[1274]: Unregistered Authentication Agent for unix-session:2 (system bus name :1.691, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 09 13:42:19 gnome-session-binary[3180]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Dec 09 13:42:19 gnome-session[3180]: gnome-session-binary[3180]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): EDID vendor "LGD", prod id 1580
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Modeline "1920x1080"x0.0  114.46  1920 1968 2000 2164  1080 1083 1088 1102 +hsync -vsync (52.9 kHz e)
Dec 09 13:42:19 abrt-dump-journal-core[1403]: Failed to obtain all required information from journald
Dec 09 13:42:19 abrt-dump-journal-core[1403]: Failed to save detect problem data in abrt database
Dec 09 13:42:19 wpa_supplicant[2243]: wlp0s20f3: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-70 noise=9999 txrate=650000
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): EDID vendor "LGD", prod id 1580
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Dec 09 13:42:19 /usr/libexec/gdm-x-session[3152]: (II) modeset(0): Modeline "1920x1080"x0.0  114.46  1920 1968 2000 2164  1080 1083 1088 1102 +hsync -vsync (52.9 kHz e)
Dec 09 13:42:19 gsd-media-keys[3557]: g_variant_get_va: assertion 'value != NULL' failed
Dec 09 13:42:19 gsd-media-keys[3557]: g_variant_unref: assertion 'value != NULL' failed
Dec 09 13:42:19 org.gnome.Shell.desktop[5618]: current session already has an ibus-daemon.
Dec 09 13:42:20 gnome-shell[5618]: g_strsplit: assertion 'string != NULL' failed
Dec 09 13:42:20 polkitd[1274]: Registered Authentication Agent for unix-session:2 (system bus name :1.795 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 09 13:42:20 gnome-shell[5618]: Telepathy is not available, chat integration will be disabled.
Dec 09 13:42:20 gnome-shell[5618]: Some code accessed the property 'SHOW_BATTERY_PERCENTAGE' on the module 'power'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Dec 09 13:42:20 gnome-shell[5618]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Dec 09 13:42:20 NetworkManager[1436]: <info>  [1639075340.8601] agent-manager: agent[d259027d5cc46b62,:1.795/org.gnome.Shell.NetworkAgent/1001]: agent registered
Dec 09 13:42:21 gnome-shell[5618]: GNOME Shell started at Thu Dec 09 2021 13:42:20 GMT-0500 (EST)
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 gnome-shell[5618]: Error adding children to desktop: desktopGrid is undefined
Dec 09 13:42:22 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:27 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:30 gnome-shell[5618]: gsignal.c:2642: instance '0x55c198a31610' has no handler with id '11181'
Dec 09 13:42:32 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:36 dbus-daemon[1277]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.795' (uid=1001 pid=5618 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:36 systemd[1]: Starting Fingerprint Authentication Daemon...
Dec 09 13:42:36 dbus-daemon[1277]: [system] Successfully activated service 'net.reactivated.Fprint'
Dec 09 13:42:36 systemd[1]: Started Fingerprint Authentication Daemon.
Dec 09 13:42:37 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:42 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:44 gdm-password][5810]: pam_sss(gdm-password:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/tty1 ruser= rhost= user=testuser
Dec 09 13:42:44 gdm-password][5810]: pam_sss(gdm-password:auth): received for user testuser: 7 (Authentication failure)
Dec 09 13:42:44 gdm-password][5810]: gkr-pam: the password for the login keyring was invalid.
Dec 09 13:42:47 wpa_supplicant[2243]: wlp0s20f3: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-70 noise=9999 txrate=650000
Dec 09 13:42:47 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:50 systemd[1]: systemd-hostnamed.service: Succeeded.
Dec 09 13:42:52 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:42:53 gdm-password][5817]: pam_sss(gdm-password:auth): authentication success; logname= uid=0 euid=0 tty=/dev/tty1 ruser= rhost= user=testuser
Dec 09 13:42:53 gdm-password][5817]: gkr-pam: unlocked login keyring
Dec 09 13:42:53 dbus-daemon[1277]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.795' (uid=1001 pid=5618 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:53 systemd[1]: Starting Hostname Service...
Dec 09 13:42:53 dbus-daemon[3146]: [session uid=1001 pid=3146] Activating service name='org.gnome.Nautilus' requested by ':1.138' (uid=1001 pid=5618 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:53 dbus-daemon[3146]: [session uid=1001 pid=3146] Activating service name='org.freedesktop.FileManager1' requested by ':1.138' (uid=1001 pid=5618 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Dec 09 13:42:53 dbus-daemon[1277]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 09 13:42:53 systemd[1]: Started Hostname Service.
Dec 09 13:42:53 NetworkManager[1436]: <info>  [1639075373.8765] agent-manager: agent[90eb41184cb504f9,:1.795/org.gnome.Shell.NetworkAgent/1001]: agent registered
Dec 09 13:42:53 dbus-daemon[3146]: [session uid=1001 pid=3146] Successfully activated service 'org.gnome.Nautilus'
Dec 09 13:42:53 org.freedesktop.FileManager1[3146]: Failed to register: Unable to acquire bus name 'org.gnome.Nautilus'
Dec 09 13:42:53 dbus-daemon[3146]: [session uid=1001 pid=3146] Activated service 'org.freedesktop.FileManager1' failed: Process org.freedesktop.FileManager1 exited with status 1
Dec 09 13:42:53 gnome-shell[5618]: Error connecting to Nautilus
Dec 09 13:42:57 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
Dec 09 13:43:02 org.gnome.Shell.Extensions.GSConnect[4559]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions website
 - **GNOME/Shell version:** 3.32.2
 - **Distro/Release:** Red Hat Enterprise Linux 8.5

**GSConnect environment (if applicable):**

 - **Paired Device(s):** none

**Additional Notes:**

I am submitting this on behalf of a ticket I received from a customer.  We were able to narrow it down to the GSConnect extension.  I was able to reproduce it on a fresh install.

**Comment by andyholmes** [comment]
Sorry, but this is not the latest release of GSConnect and is thus unsupported by the project. v28 was released in [November of 2019](https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/tag/v28), while the current version is v48 released in [October of this year](https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/tag/v48).

The project simply doesn't have the resources to support older versions of GNOME. I would recommend your customer try installing the [official KDE Connect](https://kdeconnect.kde.org/) application, which may have better support for older systems.
