### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [GSConnect/gnome-shell-extension-gsconnect#1223]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://262.ecma-international.org/12.0/#sec-assignment-operators "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#\b(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-/%^]|\*\*?|&&?|\|\|?|\?\?|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/gnome-shell-extension-gsconnect/lokal -name '*.js')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 30 lines of this software?

**Comment by andyholmes** [comment]
This seems to only find assignment operators in `jasmine.js`, which is the testing framework we import wholesale from https://jasmine.github.io/. I'm not sure there's benefit to making changes there that the upstream developers don't implement.

Is there something your script is intended to do for our source that [ESLint](https://eslint.org/) doesn't already do?

**Comment by andyholmes** [comment]
Closing, apparently this is some kind of bot.
