### ISSUE TITLE
[Question] What's the purpose of TOOLTIP_BROWSE_ID in tooltip.js#L18?

### ISSUE THREAD

**Issue by nlpsuge** [GSConnect/gnome-shell-extension-gsconnect#1227]
Hi,

I'm adopting tooltip.js into my project, but I don't understand the purpose of TOOLTIP_BROWSE_ID in tooltip.js#L18:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/8e85f0fc0490dbf92d16a31ee5d73b46ae43e653/src/shell/tooltip.js#L18

It's never assigned to a meaningful value (which is a non-zero value in the case). Looks like it and some other code using it can be removed?

**Comment by andyholmes** [comment]
Ah, that's a mistake. It should probably be set as the return value of a call to `GLib.timeout_add()`, so that it's disabled after a period. Probably 500ms, from glancing at the source of `gtktooltip.c`.

**Comment by nlpsuge** [comment]
> It should probably be set as the return value of a call to `GLib.timeout_add()`

Assign this line's return value to TOOLTIP_BROWSE_ID, right? looks very likely, any way :)
https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/8e85f0fc0490dbf92d16a31ee5d73b46ae43e653/src/shell/tooltip.js#L246

**Comment by andyholmes** [comment]
That seems right :)
