### ISSUE TITLE
Child process exited with code 1

### ISSUE THREAD

**Issue by ironsmile** [GSConnect/gnome-shell-extension-gsconnect#1231]
I got this error when installed the GSConnect extension for a second time. Timeline:

* Installed the extension
* Looked at its settings via the Extensions app
* Uninstalled the extension
* Installed it again few hours later
* Opened its settings via the Gnome Tweak Tools

```
GSConnect: 43 (user)
GJS:       16405
Session:   x11
OS:        Ubuntu 20.04.3 LTS

Gio.TlsCertificate.new_for_paths@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/iron4o/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment]
Hmm, that's strange. I guess the error could be made a little more helpful there, we're not really checking what the process actually outputs.

If you're looking for a quick fix and just installed, I would just uninstall, wipe the config and reinstall:

```sh
gnome-extensions uninstall gsconnect@andyholmes.github.io
rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
rm -rf ~/.cache/gsconnect
rm -rf ~/.config/gsconnect
dconf reset -f /org/gnome/shell/extensions/gsconnect/
```

Those commands in a terminal will remove all settings, including the certificate which is what seems to be the problem.

**Comment by ironsmile** [comment]
I will give it a try. Also, I will be happy to try my hand on improving the logging. Any hints will be appreciated!

**Comment by ironsmile** [comment]
Also, I confirm that the extension is not crashing any more after clearing the settings.

**Comment by ironsmile** [comment]
The root problem on my machine turned out to be that generating the certificate and key for the machine was failing:

```
$ openssl req -new -x509 -sha256 -out ~/.config/gsconnect/certificate.pem -newkey rsa:4096 -nodes -keyout ~/.config/gsconnect/private.pem -days 3650 -subj '/O=andyholmes.github.io/OU=GSConnect/CN=serenity'
Can't open /usr/local/ssl/openssl.cnf for reading, No such file or directory
0:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:74:fopen('/usr/local/ssl/openssl.cnf','r')
0:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:81:
Generating a 4096 bit RSA private key
...........................................................................................................++
..........................................++
writing new private key to '/home/--/.config/gsconnect/private.pem'
-----
unable to find 'distinguished_name' in config
problems making Certificate Request
0:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto/conf/conf_lib.c:271:
```

My openssl installation seems to have some issues. A binary at `/usr/local/bin/openssl` was used which is probably some remnant from before times. When using `/usr/bin/openssl` the key and certificate got created without problem.

**Comment by andyholmes** [comment]
> I will give it a try. Also, I will be happy to try my hand on improving the logging. Any hints will be appreciated!

Basically,  this section here needs some help propagating the process output:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/8e85f0fc0490dbf92d16a31ee5d73b46ae43e653/src/service/__init__.js#L335-L349

The `wait_check()` call should be replaced with `communicate_utf8()` to read the output on stderr, so `Gio.SubprocessFlags.STDERR_PIPE` should be passed instead of `STDERR_SILENCE`.

```js
// Same code up to `proc.init(null)`
const stderr = proc.communicate_utf8(null, null)[2];
const status = proc.get_exit_status();

if (status !== 0) {
    throw new Gio.IOErrorEnum({
        code: Gio.io_error_from_errno(status),
        message: stderr ? stderr.trim() : GLib.strerror(status),
    });
}
```

I think that should properly propagate any errors, although some testing would be required :)

**Comment by andyholmes** [comment]
Moving discussion to the common issue #1209
