### ISSUE TITLE
Fix homepage link on extensions.gnome.org

### ISSUE THREAD

**Issue by darkdragon-001** [GSConnect/gnome-shell-extension-gsconnect#1235]
Please fix the link on [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/) to reflect the new `GSConnect` Github organisation.

**Comment by andyholmes** [comment]
Just needs to be updated in the `meson.build` file:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/3a67d3f0c3057949d7e239761bc1445912bbfab4/meson.build#L42-L43

Feel free to open a PR, but otherwise Github will do redirects automatically.
