### ISSUE TITLE
Provide newer build for older Gnome Shell versions on Gnome Extentions Website

### ISSUE THREAD

**Issue by pseudodamaging** [GSConnect/gnome-shell-extension-gsconnect#1251]
Please provide newer builds for older Gnome versions on the Gnome Extensions Website, for example Ubuntu 20.04lts uses GNOME Shell 3.36.
For Gnome 3.36 version 43 of GSConnect is currently provided, which is affected by Issue 1189.

**Comment by daniellandau** [comment]
A new version for 3.36 is now available.
