### ISSUE TITLE
Battery info doesn't show in panel display mode

### ISSUE THREAD

**Issue by johndzxu** [GSConnect/gnome-shell-extension-gsconnect#1254]
**Describe the bug**

When I change my display mode from user menu to panel, the battery info does not show in the drop down menu when the phone icon is clicked.

**Steps To Reproduce:**

1. Go to extension settings
2. Change display mode from user menu to panel
3. Click on the phone icon in the top panel

**Expected behavior**

An icon showing the battery percentage should be displayed. In fact, I can see a little bit of it but it seems to be obscured by the action buttons.

**Screenshots**

![image](https://user-images.githubusercontent.com/77399093/153849902-522e33cb-16c8-4a78-997f-29bdccbde766.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 47
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 40.5
 - **Distro/Release:** Ubuntu 21.10

 - **Paired Device(s):** Galaxy S10
 - **KDE Connect app version:** 1.19.1
 - **Plugin(s):** Default

**Additional Notes:**

I'm suspecting that this has something to do with my shell theme, which is Orchis

**Comment by andyholmes** [comment]
You'll have to take this up with the theme developer, unfortunately.

**Comment by johndzxu** [comment]
Sure, thanks for your comment.
