### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by VitalyAnkh** [GSConnect/gnome-shell-extension-gsconnect#1256]
```
GSConnect: 47 (user)
GJS:       17190
Session:   wayland
OS:        Arch Linux

_loadBackends@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by mackdroid** [comment]
encountering same issue on gnome 42.beta
![image](https://user-images.githubusercontent.com/68280146/155665837-e0031dd8-5006-4a25-92bb-3e5b4a4c14c2.png)

**Comment by openmindead** [comment]
Same on Ubuntu 22.04:

```
GSConnect: 47 (user)
GJS:       17101
Session:   wayland
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/openm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/openm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/openm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/openm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/openm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by eeickmeyer** [comment]
Reported in the official Ubuntu package as well: https://bugs.launchpad.net/gsconnect/+bug/1964276

**Comment by andyholmes** [comment]
Uh oh, it looks like after some 3-4 years Ubuntu has decided to update their GSConnect package and carry it in official repositories. I have to say that might not have been a wise choice with contacting upstream.

At this point GSConnect is verging on unmaintained and they've pushed a version of the extension that explicitly lacks support for the version of GNOME Shell version they're shipping. It looks like their freeze already happened on February 24th, so hopefully they plan on handling the bug reports themselves :confused:

**Comment by eeickmeyer** [comment]
@andyholmes I'm the person who did the updating. And that freeze doesn't apply in cases of bugs.

**Comment by andyholmes** [comment]
@eeickmeyer In that case, you may end up having to carry patches or build from a git snapshot. I don't use or develop GSConnect myself anymore and the current maintainer responsible for rolling releases is pretty constrained for time.

I've pushed #1276 which may fix the above problems, but it's mostly a guess based on following the development in GJS this cycle. It will required some testing from someone running GNOME 42.beta to confirm it fixes the problem and doesn't cause regressions.

**Comment by eeickmeyer** [comment]
@andyholmes I can do the testing, and git snapshots aren't an issue. :)

**Comment by eeickmeyer** [comment]
@andyholmes Good news! It does fix the problem of the settings window not working. Bad news: I found a whole new issue.

**Comment by daniellandau** [comment]
I'll roll releases over the weekend. @eeickmeyer want to elaborate on "Bad news: I found a whole new issue.", perhaps in a new issue?

**Comment by eeickmeyer** [comment]
@daniellandau I did, and it's already fixed.

**Comment by daniellandau** [comment]
I see, cool :)

**Comment by ferdnyc** [comment]
Reopening this pending the new releases getting out into the wild, or we'll keep getting more duplicates. (In fact, for the moment, pinning it as well.)

**Comment by daniellandau** [comment]
The new release is at e.g.o already

**Comment by kirienko** [comment]
I had this error constantly on Debian and almost gave up trying. But eventually, I found the solution.

Define your GNOME version carefully: I have GNOME 42 and `gnome-shell` 3.38. That means that on the [extensions](https://extensions.gnome.org/extension/1319/gsconnect/) page, when picking a version to download, I select "Shell version" as `42`, not `3.38`! (Both GNOME version and the shell version are in the same list, which is misleading). 

After selecting "Shell version" as 42, the only extension version offered is `v50`. And this one works for me, while `v51` does not!

**Comment by daniellandau** [comment]
I don't know what you're looking at, but you shouldn't have 42 and 3.38 on the same machine

**Comment by kirienko** [comment]
> I don't know what you're looking at, but you shouldn't have 42 and 3.38 on the same machine

Perhaps I _shouldn't_, you're right, but that's what I have. That's because being on `stable`, I take packages from `sid` from time to time. People do unexpected things, that's why, in turn, I think they _shouldn't_ place the `GNOME` version and the `gnome-shell` version in the same list. One cannot infer the version of one from the version of the other reliably.

**Comment by daniellandau** [comment]
I'm pretty sure in Debian you are on your own if you do that.

**Comment by andyholmes** [comment]
> Define your GNOME version carefully: I have GNOME 42 and gnome-shell 3.38. That means that on the [extensions](https://extensions.gnome.org/extension/1319/gsconnect/) page, when picking a version to download, I select "Shell version" as 42, not 3.38! (Both GNOME version and the shell version are in the same list, which is misleading).

I'm not sure what you're referring to as the GNOME version, but the "Shell version..." (as seen in the screenshot below) is the `gnome-shell` version and the only one that matters to GSConnect; all other dependencies of GSConnect are dependencies of GNOME Shell. GNOME Shell 42 is only supported by GSConnect v50, which is why that's the only version shown on the website.

![Screenshot from 2022-10-20 19-24-33](https://user-images.githubusercontent.com/1265208/197096634-04022f92-e2e3-4742-b6ad-f6c2213af304.png)
