### ISSUE TITLE
Getting battery level from a cli?

### ISSUE THREAD

**Issue by ioguix** [GSConnect/gnome-shell-extension-gsconnect#1275]
Hi,

I'm trying to get the phone battery status from my desktop. I am using i3wm, so I can't rely on gnome-shell integration.

Is it possible to get this information by any mean? 

I checked the CLI and found nothing for this.

Looking at dbus, it seems the battery info are send by a signal from org.gtk.Actions interface. I'm not sure how I could actually query the battery value, not just waiting for a signal to carry it to me.

I'm using gsconnect 48 installed from fedora 35 package.

Any guidance?

Thanks!

**Comment by andyholmes** [comment]
There's no CLI option for this unfortunately. The battery plugin exports a stateful GAction with a GVariant value of `(bsii)`, which is `(charging, icon-name, level, time-remaining)`.

You could get a text printout of the GAction state with something like this:

```sh
gdbus call --session \
           --dest org.gnome.Shell.Extensions.GSConnect \
           --object-path /org/gnome/Shell/Extensions/GSConnect/Device/<device-id> \
           --method org.gtk.Actions.Describe battery
```

And that would give you a printout something like this (pretty much a guess):

```
((true, signature '', [true, 'battery-full-charging-symbolic', 100, 2223]),)
```

Of course, this is a lot easier to do from a Python or GJS script. GSConnect wasn't really designed to be used in this way though, so you may have to do some fiddling to get this to work for your use case.

**Comment by ioguix** [comment]
Hi,

Thank you for your help and detailed answer!
