### ISSUE TITLE
Doesn't work on Ubuntu-22.04 beta - probably gnome-41 related?

### ISSUE THREAD

**Issue by jhaar** [GSConnect/gnome-shell-extension-gsconnect#1289]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

**Steps To Reproduce:**

1. I installed gsconnect via firefox on https://extensions.gnome.org
2. Clicked on the "on/off" button
3. nothing happens. ie cannot get the configuration to popup, nor does the app show up in the taskbar

**Expected behavior**

This was working fine under Ubuntu-20.04, and I  see this code hasn't been touched since Nov - so I'd guess gnome-41 has changed something? FYI Ubuntu-22.04 is meant to ship with gnome-42 - so maybe this beta is in some hybrid mode too? (gnome-shell is listed as 41 - not 42)

**System Details (please complete the following information):**

 - **GSConnect version:** 41/48
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 41
 - **Distro/Release:**Ubuntu 22.04beta

**Comment by eeickmeyer** [comment]
The gnome-shell-extension-gsconnect package is patched to work on GNOME 42.

**Comment by jhaar** [comment]
Just letting you know it works! Thanks!

**Comment by ArtMin96** [comment]
Any plans for GNOME 42.2 support?
