### ISSUE TITLE
Not compatible with Gnome 42

### ISSUE THREAD

**Issue by qwertychouskie** [GSConnect/gnome-shell-extension-gsconnect#1302]
Ubuntu 22.04 Beta just got GS42, and now GSconnect won't work

**Comment by VelocityDesign** [comment]
Same with Fedora 36 Beta 1.1. I'll try forking and changing the supported version and let you know if it works.

**Comment by Diegovsky** [comment]
did it?

**Comment by VelocityDesign** [comment]
I couldn't find the place to change it, sorry. I'm not familiar with the gnome extensions development workflow.

**Comment by eeickmeyer** [comment]
@qwertychouskie The gnome-shell-extension-gsconnect package is patched to work on GNOME 42.

**Comment by eeickmeyer** [comment]
@daniellandau I see you bumped the release, but GNOME 42 is due out any day, and Ubuntu and Fedora are already running the betas in their development branches. You may need to bump the version in data/metadata.json.in to work with GNOME 42.

**Comment by daniellandau** [comment]
Yeah I know, working on it

**Comment by daniellandau** [comment]
Fix released on extensions.gnome.org
