### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by reganto** [GSConnect/gnome-shell-extension-gsconnect#1305]
I update extension and it crashed. this is crash log:

GSConnect: v53
Session:   X11
OS:        Ubuntu 20.04

The settings of extension gsconnect@andyholmes.github.io had an error:
```
GLib.SpawnError: Failed to execute child process “/home/reganto/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences” (No such file or directory)
```

Stack trace:
```
buildPrefsWidget@/home/reganto/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:25:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by AfzGit** [comment]
Same. using ubuntu 20.04

**Comment by AfzGit** [comment]
if you get error on ubuntu 20.04, just install last working version v43. here is the link and the tutorial

Download:
https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/tag/v43

Tutorial:
https://www.debugpoint.com/2021/10/manual-installation-gnome-extension/

**Comment by daniellandau** [comment]
The extension update process is sometimes a bit wonky. Logging out and back in might fix it. That file does exist in v53.

**Comment by reganto** [comment]
> The extension update process is sometimes a bit wonky. Logging out and back in might fix it. That file does exist in v53.

It works flawlessly now. thank you
