### ISSUE TITLE
Can't send files after update v53

### ISSUE THREAD

**Issue by brccabral** [GSConnect/gnome-shell-extension-gsconnect#1309]
Today GSConnect updated to v53 and I can't send files from my phone anymore, it was working before...

**Comment by daniellandau** [comment]
Can you provide more details on your system etc

**Comment by brccabral** [comment]
OS: Ubuntu 20.04.4 LTS x86_64 
Host: 81LL IdeaPad L340-17IRH Gaming 
Kernel: 5.13.0-35-generic 
Shell: zsh 5.8 
DE: GNOME 3.36.9
WM: Mutter (Wayland)
CPU: Intel i7-9750H (12) @ 2.600GHz 
GPU: Intel UHD Graphics 630 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q

**Comment by andyholmes** [comment]
Please see [Generating a Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) in the Wiki. Without this information, reported issues are impossible to resolve.

Feel free to re-open when you can provide those logs.
