### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by johnaaronrose** [GSConnect/gnome-shell-extension-gsconnect#1317]
I've now got GSConnect installed by using Ubuntu Tweaks. howver, I don't see GSConnect in the Tray. How do I run GSConnect?

**Comment by MarcoWilli** [comment]
I don´t know about Ubuntu but on Fedora 35 I have an extension manager installed for all Gnome extensions and from there I can run it. Though I miss a status icon but I remember for this I need to install another extension to show it on the above bar.

**Comment by andyholmes** [comment]
GSConnect will automatically start when enabled. If you install by *any* method other than the official website, you should expect to have to restart GNOME Shell.
