### ISSUE TITLE
GSConnect doesn't see my phone

### ISSUE THREAD

**Issue by johnaaronrose** [GSConnect/gnome-shell-extension-gsconnect#1319]
Just installed GSConnect. GSConnect can't see my Android phone on my network: it just says 'Searching for devices'. Both my Ubuntu 20.04 box & my phone have static NAT addresses. My phone (using KDE Connect app) can't see any of them and they can't see GSConnect. I can ping my phone from my Ubuntu box. Firewall ports 1714-1764 are in & out for both UDP & TCP.

Steps To Reproduce:
    Go to Settings
    Click on Refresh

Expected behaviour:
My phone should show up.

Support Log:
GSConnect: 53 (user)
GJS:       16405
Session:   x11
OS:        Ubuntu 20.04.4 LTS
--------------------------------------------------------------------------------
-- Logs begin at Wed 2021-07-28 08:37:58 BST, end at Thu 2022-03-31 17:02:04 BST. --
-- No entries --

GSConnect Version: 53
KDE Connect app (on phone): 1.19.1

Also adding directly via the IP has no effect, after pressing on connect nothing happens
![GnomeShellExtensionsScreenshot](https://user-images.githubusercontent.com/397379/161100687-4986181a-aa1c-4a9a-bb49-aad9ebd8bf2c.png)

**Comment by johnaaronrose** [comment]
I forgot to attach GSConnect screenshot
![GSConnectScreenshot](https://user-images.githubusercontent.com/397379/161101834-9628fa01-1adf-4401-a233-0d2219a24033.png)
.

**Comment by teras** [comment]
Hello, any luck on this?

**Comment by johnaaronrose** [comment]
No.

Sent from Nine
________________________________

**Comment by yuukiAme** [comment]
Same. 
With Samsung Galaxy Tablet S8+ and Fedora 36 Gnome 42.

**Comment by wojpawlik** [comment]
Same with Samsung A22 and Fedora 36 Gnome 42. For some reason it works when I'm tethering tho.

**Comment by wojpawlik** [comment]
It also works on my home Wi-Fi, but not my rented room Wi-Fi. How can I troubleshoot?

**Comment by daniellandau** [comment]
Not much to be done if the network doesn't allow connections between devices.

**Comment by grizzlysmit** [comment]
same problem, do not know why but neither can see the other suddenly , I'll put a bug in with Ubuntu as I believe that is the problem

**Comment by andyholmes** [comment]
I'm going to close this issue, because we get dozens of these issues and they are just impossible to solve without proper logs.

Either there is a logged error that we're not being provided with, or this is a networking issue that is out of scope for GSConnect. Please feel free to re-open if you can provide said logs.
