### ISSUE TITLE
Clipboard is not automatically sent from phone

### ISSUE THREAD

**Issue by pesader** [GSConnect/gnome-shell-extension-gsconnect#1324]
**Describe the bug**

When I copy something on my phone, it is not sent to the clipboard of my computer even though I have enabled Clipboard Sync to and from device. However, when I manually send my phone's clipboard by pressing the "Send clipboard" on the KDE Connect app, it works.

**Steps To Reproduce:**

1. Enable Clipboard Sync "To Device" and "From Device" on GSConnect preferences
2. Copy some text on your phone
3. It will not appear on your computer's clipboard

**Expected behavior**

It is expected that the phone's clipboard and the computer's clipboard got synced.

**Support Log**

```
GSConnect: 49 (user)
GJS:       17002
Session:   wayland
OS:        Fedora Linux 35.20220405.1 (Silverblue)
--------------------------------------------------------------------------------
Apr 06 11:26:32 gnome-shell[1588]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Apr 06 11:26:32 gnome-shell[1588]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Apr 06 11:26:32 gnome-shell[1588]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**System Details (please complete the following information):**

 - **GSConnect version:** 49
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 41.4
 - **Distro/Release:** Fedora Silverblue 35

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Moto Edge 20
 - **KDE Connect app version:** 1.19.1

**Additional Notes:**

I thought this was happening because I disabled permanent notifications for the KDE Connect android app (hence, the clipboard wasn't being sent because the app was not active). Enabling permanent notifications has not solved the issue though.

Also, thanks a whole lot for developing this amazing program :rocket::heart:

**Comment by daniellandau** [comment]
That's an Android security thing and there's nothing we or KDE Connect can do about it.

**Comment by maggu2810** [comment]
@daniellandau Can you provide me some insights about the Android security challenge here?

[ClipboardManager getPrimaryClip](https://developer.android.com/reference/android/content/ClipboardManager#getPrimaryClip%28%29)

Is it about

>  If the application is not the default IME or does not have input focus this return null.

Would it be possible to use "addPrimaryClipChangedListener" and trigger a notification entry if the handler is called that allows to copy the clipboard content while using an "input focus"?

**Comment by Hassibayub** [comment]
Is this fixed?

**Comment by daniellandau** [comment]
We don't make the android app, so asking here is not fruitful.

**Comment by jabed11** [comment]
> Is this fixed?

Not yet. But this needs to be fixed.

**Comment by daniellandau** [comment]
This is not something we can fix, and probably not something that the KDE Connect android app can fix either. I'm locking this now as discussing it here is not useful for anybody.
