### ISSUE TITLE
Send clipboard manually

### ISSUE THREAD

**Issue by moshiur-raj** [GSConnect/gnome-shell-extension-gsconnect#1326]
Currently gsconnect automatically syncs clipboard from pc to phone when clipboard sync is turned on. This can be a security risk. For example I often have to copy passwords and usernames from bitwarden. I have auto deletion enabled but the password / username will still be in the android clipboard.

kdeconnect in andoroid offers a quick tile to send clipboard.
![Screenshot_20220409-064033](https://user-images.githubusercontent.com/36466700/162549653-57a18b43-3812-445c-b0e6-28ce014bf0a3.png)

Maybe we can get something similar in the gsconnect menu?

**Comment by andyholmes** [comment]
Thanks for reporting; this is a duplicate of #1167
