### ISSUE TITLE
[Feature Request] Add a Screencast support for better Integration across devices

### ISSUE THREAD

**Issue by prathikshetty2002** [GSConnect/gnome-shell-extension-gsconnect#1329]
It would be great if a screencast shortcut is added to the menu bar . As it comes in handy also easy. Those are required a lot of times.

**Comment by andyholmes** [comment]
This will have to be implemented in KDE Connect before it can be implemented in GSConnect.

You can open a feature request on https://bugs.kde.org.

**Comment by prathikshetty2002** [comment]
Ok thanks 👍 for letting me know
