### ISSUE TITLE
Rename nautilus mounted phone share

### ISSUE THREAD

**Issue by ebanDev** [GSConnect/gnome-shell-extension-gsconnect#1333]
Hello,
Actually, the name of the mounted GSConnect share in Nautilus is just the IP address of the device, it could be cool to have the name of the device instead
![Capture d’écran du 2022-04-19 15-31-46](https://user-images.githubusercontent.com/57091497/164015465-13f38529-c505-4abc-be54-7f3a4e674403.png)

**Comment by alecpetrosky** [comment]
Yes, maybe the device name we see in the context list as if we have more than one device connected with dynamic ip addresses you often end clicking all of them to find one you really need:

![Screenshot from 2022-05-08 16-53-54](https://user-images.githubusercontent.com/62790032/167317999-0337bbc2-b312-4000-867a-6ef7624648e9.png)

**Comment by andyholmes** [comment]
I'd say this is pretty much a no-go.

GSConnect offloads SFTP support to GVfs, so there's really nothing that can be done in this project to address this. Any other host-changey like workarounds are really out-of-scope for the project.
