### ISSUE TITLE
Presentation Remote does not work in Gnome 42 Pop OS 22.04

### ISSUE THREAD

**Issue by franckgaga** [GSConnect/gnome-shell-extension-gsconnect#1341]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Presentation remote does not work on Gnome 42 (Pop OS 22.04)

**Steps To Reproduce:**

1. Go to KDE Connect Android App
2. Click on Presentation Remote
3. Click next, previous, full screen, or exit presentation
4. Nothing happen on host computer (tested in Evince and Okular)

**Expected behavior**

The presentation remote should work in Evince and/or Okular

**Screenshots**

![image](https://user-images.githubusercontent.com/34136215/165797867-df7b75ab-f39d-47b1-971e-c330503b5110.png)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
```

**System Details (please complete the following information):**

 - **GSConnect version:** 50
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 42
 - **Distro/Release:** Pop OS 22.04
**GSConnect environment (if applicable):**

 - **Paired Device(s):** Xiaomi 11 Lite 5G
 - **KDE Connect app version:** 1.19.1
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any additional information about the problem or your system.

**Comment by bbb651** [comment]
I can reproduce this with a completely different setup, next slide, back slide, fullscreen, and exit presentation don't work at all.

**System Details (please complete the following information):**

 - **GSConnect version:** 50
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 42.0
 - **Distro/Release:** Arch
 - **Paired Device(s):** iPhone 7
 - **KDE Connect app version:** Testflight 0.2.0 (13)

**Comment by franckgaga** [comment]
@andyholmes  tested the fix on my system and it works great, thanks !

**Comment by andyholmes** [comment]
Thanks should go to @not-chicken :)
