### ISSUE TITLE
Scrolling with two fingers stop working on Firefox on Wayland

### ISSUE THREAD

**Issue by AXL1994** [GSConnect/gnome-shell-extension-gsconnect#1343]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
As the title says, scrolling a page with two fingers works one time on Firefox in Wayland, and after I load a new page it doesn't scroll anymore. If you scroll with the mouse or the trackpad the scrolling works again, but after loading another page, it stops working. Every other app I tested still works (only Stremio doesn't work, and it is basically a web app). I tested on XOrg and it works, so I presume the bug is related with Wayland and web browsers. 

**Steps To Reproduce:**

1. Open Firefox while on Wayland and load a page
2. Open your phone and connect it with KDEConnect
3. Start scrolling the loaded page, it all work.
4. Load another page, scrolling with the app doesn't work anymore

**Expected behavior**

Scrolling should always work

**Support Log**

See the attachment, I didn't see any error
[gsconnect.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/8603727/gsconnect.txt)

**System Details (please complete the following information):**

 - **GSConnect version:** 49
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 41
 - **Distro/Release:** Fedora 35

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Redmi Note 10 Pro
 - **KDE Connect app version:** 1.19

**Comment by AXL1994** [comment]
So, I tried to download the Flatpak version of Firefox (I was using the RPM one), and the scrolling works fine here. I tested again Stremio (flatpak application), but it has the same problems of the rpm Firefox, so it must be something related with browsers, but somehow the problem it's not present in Firefox flatpak app.

**Comment by andyholmes** [comment]
This seems unrelated to GSConnect, so closing for now. Feel free to re-open if you can confirm this is a problem with GSConnect and not Mutter's remote desktop interface or specific web browsers.
