### ISSUE TITLE
Add KDE Connect App for iOS

### ISSUE THREAD

**Issue by vscsilva** [GSConnect/gnome-shell-extension-gsconnect#1351]
iOS version is now available for iOS

**Comment by durianpeople** [comment]
I believe this is probably not the right project to report this issue... if it's an issue at all

**Comment by adasiko** [comment]
> I believe this is probably not the right project to report this issue... if it's an issue at all

It’s looks like «Add link (info) about existing iOS KDE Connect App to Wiki/README».

https://apps.apple.com/app/kde-connect/id1580245991

PS: can not create PR from mobile

**Comment by tejasraman** [comment]
It's on the wiki, so it's publicly editable.
I added it ;)

**Comment by andyholmes** [comment]
Thanks, closing then :)
