### ISSUE TITLE
PO files / Lang codes

### ISSUE THREAD

**Issue by hugok79** [GSConnect/gnome-shell-extension-gsconnect#1353]
Lang codes with more than three letters in some .po files have a dash and others have an underscore

With a dash (e.g. **ko-KR ; pt-PT**)
With an underscore (e.g. **nl_NL ; pt_BR**)

Another thing, shouldn't the LINGUAS file be up to date with all locales/lang codes?

**Comment by andyholmes** [comment]
Yep, locale is a bit confusing. Some languages in Crowdin need a mapping in `crowdin.yml` from dash to underscore (ie. `pt-BR` to `pt_BR`. Others may have been forgotten to be added to the `LINGUAS` file or `crowdin.yml` file.

If you find any mistakes, feel free to open PRs to fix them :)

**Comment by andyholmes** [comment]
Closing, since I believe the original issue was fixed by a PR.
