### ISSUE TITLE
In MS Edge for Linux, browser extension doesn't work

### ISSUE THREAD

**Issue by tejasraman** [GSConnect/gnome-shell-extension-gsconnect#1356]
**I have installed GSConnect on my iPad and my desktop (GNOME 42). If I install the extension on Edge, it says "no devices" - but in GSConnect, the iPad shows up fine and the iPad works fine too.** 

**Steps To Reproduce:**

1. Install extension in Edge
2. Click on extension - it says "no device found"
3. No item in right click either (as shown in chrome webstore description)

**Expected behavior**

The device shows up and I can send links to it in Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/96961804/168648020-16b81b6d-e6d4-4b02-ae9f-355f489e8f78.png)
![image](https://user-images.githubusercontent.com/96961804/168648192-6ecd9898-a13e-46c5-86a2-25e5e3d2a958.png)
![image](https://user-images.githubusercontent.com/96961804/168649668-a37c8e03-4259-44be-ab37-d8670ac48854.jpeg)

**System Details (please complete the following information):**

 - **GSConnect version:** [50]
   - **Installed from:** [GNOME Extensions Website]
 - **GNOME/Shell version:** [42.0]
 - **Distro/Release:** [Pop!_OS 22.04 (Ubuntu 22.04) ]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [iPad Air (4th Gen) ]
 - **KDE Connect app version:** [0.2.1 for iOS]

**Additional Notes:**

I am using Microsoft Edge, not Chrome.
> _Does this have something to do with edge?_

No, the iPad app isn't broken - it works fine with a beta of KDE Connect for Mac on my patched 2011 MacBook Pro with the KDE Connect extension

**Comment by tejasraman** [comment]
@andyholmes has this been fixed yet?

**Comment by andyholmes** [comment]
Nope, it doesn't look like anyone has taken it on.

Since GSConnect is basically community-maintained now, if you don't contribute a fix yourself you will have to wait for someone to come forward and work on it.

**Comment by tejasraman** [comment]
Sorry, switched to Budgie as a desktop and I am no longer actively using this extension. Might switch back some day, but I am using KDE's official extension + panel indicator now.
