### ISSUE TITLE
Native messaging host clutter

### ISSUE THREAD

**Issue by K4rakara** [GSConnect/gnome-shell-extension-gsconnect#1382]
I'm a bit of a lunatic when it comes to dotfile cleanliness, so when GSConnect is creating:

- `~/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/chromium/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/google-chrome/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/google-chrome-beta/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/google-chrome-unstable/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/microsoft-edge-beta/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
- `~/.config/microsoft-edge-dev/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`

I get a little miffed. Furthermore, these are only the non-sandboxed versions of these apps data directories, it doesn't even account for their flatpak or snap counterparts.

**Steps To Reproduce:**

Launch GSConnect. Check home directory.

**Expected behavior**

I don't even think this needs to be an option visible in the GUI. A simple dconf key to toggle this behavior would be splendid.

**System Details (please complete the following information):**

 - **GSConnect version:** 50
   - **Installed from:** Extension Manager (`com.mattjakeman.ExtensionManager`)
 - **GNOME/Shell version:** 42
 - **Distro/Release:** Fedora Silverblue 36

**Additional Notes:**

I'm gonna take a quick knack at fixing this, I'll PR it when I'm done.

**Comment by otuva** [comment]
For anyone that might wanna set this option to false

```bash
mkdir -p .local/share/glib-2.0/schemas
cp .local/share/gnome-shell/extensions/*/schemas/*gschema.xml .local/share/glib-2.0/schemas/
cd .local/share/glib-2.0/schemas/
glib-compile-schemas .
gsettings set org.gnome.Shell.Extensions.GSConnect create-native-messaging-hosts false
```

**Comment by otuva** [comment]
For removal be careful though

```bash
rm -r .config/chromium .config/google-chrome .config/google-chrome-beta .config/google-chrome-unstable .config/BraveSoftware .config/microsoft-edge-dev .config/microsoft-edge-beta .mozilla
```
