### ISSUE TITLE
Integration with Nautilus

### ISSUE THREAD

**Issue by luizfelmach** [GSConnect/gnome-shell-extension-gsconnect#1390]
**Is your feature request related to a problem? Please describe.**
I love to share files with my cell phone, it's very practical. Even more practical, it would be if I had to right-click inside nautilus and show an option like "Send to my phone"

**Describe the solution you'd like**
I have no idea if that would be possible.

**System Details (please complete the following information):**
 - GSConnect version: 50
   - Installed from: extensions.gnome.org

**Additional context**
It doesn't have

**Comment by moshiur-raj** [comment]
you need to have python-nautilus installed.
