### ISSUE TITLE
Ring facility in Android Phone increases the system's volume

### ISSUE THREAD

**Issue by VIS-WA** [GSConnect/gnome-shell-extension-gsconnect#1391]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Terms: 
Phone -> An android (12) phone having KDE Connect
PC -> Personal computer running Ubuntu 22.04 LTE

I have tried ringing the PC from my phone. This features works fine and rings the PC. But at the same time, I have my PC playing music (say the volume is at 25%). When I ring,  all the volumes (system, media, notifications) increase to 100%, which may be harmful when using Headphones or similar accessories.

**Steps To Reproduce:**
In PC,
1. Play some music set at 25% (or anything less than 100%)

In Phone (when connected on same network as the PC),
1.Open the KDE Connect app
2. Goto three dots on right top corner ':'
3. Click on the "Ring" button
4. Observer the sound output from PC
5. See/observe the error

**Expected behavior**

When ringed, only the ringing volume should be at maximum volume while other sounds can be at their initial set volumes.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

(Not required)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

(Not required)
```

```

**System Details (please complete the following information):**

 - **GSConnect version: *53* 
   - **Installed from: *GNOME Extensions Website* 
 - **GNOME/Shell version: *3.36.9*
 - **Distro/Release:*Ubuntu 22.04*

**GSConnect environment (if applicable):**

 - **Paired Device(s):*OnePlus 8T* 
 - **KDE Connect app version: *1.19.1* 
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any additional information about the problem or your system.

**Comment by andyholmes** [comment]
Thanks for reporting!

What volume would you suggest we set the mixer to? Should we just leave it as is?

**Comment by VIS-WA** [comment]
Two cases:
I)  Leave the mixer as it is
II) Pause all the playbacks and resume once the ringer is stopped (similar to when a phone call is received)

Anything of the above two should be fine i guess.
