### ISSUE TITLE
Photo Plugin: make destination folder configurable per paired device

### ISSUE THREAD

**Issue by autarctechelias** [GSConnect/gnome-shell-extension-gsconnect#1396]
I am using multiple devices and I would like the Photos plugin to store it's files where I want them to instead of just dumping into my Pictures folder. This would make managing my folder structures a bit easier. Additional bonus would be a configurable filename mask to allow for configurable timestamps and a running count.

**Comment by andyholmes** [comment]
Closing, due to https://bugs.kde.org/show_bug.cgi?id=474121
