### ISSUE TITLE
GS Connect does not run on pop os 22.04 LTS

### ISSUE THREAD

**Issue by khewweifeng** [GSConnect/gnome-shell-extension-gsconnect#1405]
Distribution (run cat /etc/os-release):
Pop!_OS 22.04 LTS

Related Application and/or Package Version (run apt policy $PACKAGE NAME):
gnome-shell-extension-gsconnect

Issue/Bug Description:
GS Connect does not launch even clicked open buttom from pop-os shop

Steps to reproduce (if you know):
Install GSConnect via pop-os store

**Comment by RasheedAZ** [comment]
> Issue/Bug Description: GS Connect does not launch even clicked open buttom from pop-os shop
> 
> Steps to reproduce (if you know): Install GSConnect via pop-os store

Pop shop does not appear to have GSConnect and neither does Flathub...

**Comment by adam-husain** [comment]
@RasheedAZ PopShop does have GSConnect and I can confirm it does NOT open.
![image](https://user-images.githubusercontent.com/34790400/177579989-a508ab2c-7350-4fea-b02d-76ff8dc668cb.png)
I can install it through Gnome Extensions and then it works perfectly fine.

**Comment by khewweifeng** [comment]
Hi guys, I found alternative solution from my end ... kdeconnect + nautilus-kdeconnect 

so I will close this issue.
