### ISSUE TITLE
Commands that accept parameters

### ISSUE THREAD

**Issue by BrunoCBart** [GSConnect/gnome-shell-extension-gsconnect#1410]
I wanted to specify a file when using a command from my phone device to the computer but I realized that you can`t input any parameters for commands...

It would be awesome if you guys could implement this feature, heck, I would do it myself if I could.

I would really appreciate if you guys could do this, thanks!

**Comment by andyholmes** [comment]
Sorry, this would have to be implemented in the KDE Connect protocol before it can be implemented in GSConnect.

You can open an upstream bug report at https://bugs.kde.org
