### ISSUE TITLE
Doesnt work over bluetooth

### ISSUE THREAD

**Issue by apacelus** [GSConnect/gnome-shell-extension-gsconnect#1416]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

When connecting the phone over bluetooth, neither the phone nor the laptop see each other.

**Steps To Reproduce:**

1. Pair phone and pc over bluetooth
2. Connect phone to pc
3. No connection

**Expected behavior**

Expecting the phone and the laptop to see each other over bt.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04 LTS
--------------------------------------------------------------------------------
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
Jul 12 15:24:10 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Jul 12 15:24:10 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Jul 12 15:24:10 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Jul 12 15:24:11 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Jul 12 15:24:11 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Jul 12 15:24:11 org.gnome.Shell.Extensions.GSConnect[1716]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
```

**System Details (please complete the following information):**

 - **GSConnect version:** 50
 - **Installed from:** [extension manager](https://github.com/mjakeman/extension-manager) flatpak version
 - **GNOME/Shell version:** 42.2
 - **Distro/Release:** Ubuntu 22.04 LTS
 - **GSConnect environment (if applicable):**

 - **Paired Device(s):** Oneplus 9 pro with lineageos(stock android)
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Connected to a wifi network which doesnt allow lan connections, but that shouldnt be an issue for a bluetooth connection.

**Comment by daknuett** [comment]
Using Bluetooth tethering and manually adding the IP address works.

Steps to reproduce:

1. Enable Bluetooth tethering using your computer (the phone should ask if that is OK, or enable it in the phone settings).
2. Look up the IP address of the computer using `ip addr`.
3. On the phone enter the IP address manually under *Settings->Add devices by IP*

The connection should then be established.

**Comment by andyholmes** [comment]
There is no bluetooth support in KDE Connect or GSConnect, and really never has been.

Please see #17 for historical discussion.
