### ISSUE TITLE
Supporting the new quick settings menu/extension

### ISSUE THREAD

**Issue by not-a-dev-stein** [GSConnect/gnome-shell-extension-gsconnect#1428]
**Is your feature request related to a problem? Please describe.**
GNOME is [starting the work into changing its quick settings menu design](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2392) to a new version based on [Allan Day's mockups](https://gitlab.gnome.org/Teams/Design/os-mockups/-/tree/master/system-status/quick-settings). There's already [an extension to develop and test how it'll look and feel](https://gitlab.gnome.org/fmuellner/quick-settings-extension). And it currently [looks broken when you use it with GSConnect](https://gitlab.gnome.org/fmuellner/quick-settings-extension/-/issues/5).

**Describe the solution you'd like**
It'll be nice to start planning for what updates will be needed to support this change when the time comes it is implemented / support the extension in some shape or form, if possible.

**Comment by ferdnyc** [comment]
There are some possible tweaks being proposed/requested in #1506, but for the most part this is completed, as there's _a_ QuickSettings menu button in GSConnect 54. Possibly an imperfect one, but it's at least there. Closing this as completed.
