### ISSUE TITLE
gs connect dosn't work anymore with ubuntu 22.04 on GNOME 42.4

### ISSUE THREAD

**Issue by theFus** [GSConnect/gnome-shell-extension-gsconnect#1466]
After upgrade to ubuntu 22.04 with gnome 42.4 "gnome extensions" says : "The extension is incompatible with the current GNOME version" , gsconnect doesn't work. 
gs connect extension is the newest version: 53

**Comment by PeteLawler** [comment]
Running Debian Bookworm here, they're on Gnome 43.
Bumped my ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/metadata.json shell-version to 43, relogged. Got 'AggregateMenu is undefined' error, so I guess it isn't an entirely quick fix like I was hoping for, heh.

**Comment by ak1n** [comment]
Tried downloading the stable zip and get the incompatible error preventing use on Gnome 42.5 (pop os 22.04 LTS).

**Comment by brccabral** [comment]
On Ubuntu 22.04 I had to go to $HOME/.local/share/applications , select both `.desktop` files 
`org.gnome.Shell.Extensions.GSConnect.desktop`
`org.gnome.Shell.Extensions.GSConnect.Preferences.desktop`
right click, Properties, Permissions, check `Allow executing file as program`, close.
Then, double click `GSConnect Preferences` to open GSConnect and pair my phone.

**Comment by sulliwane** [comment]
similar issue here: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1642

**Comment by daniellandau** [comment]
You shouldn't blindly use a version with the largest number. The correct version of GNOME Shell 42 is v50. Installing from https://extensions.gnome.org gives you automatically the correct version. On the GitHub releases page the latest release is generally for the latest released GNOME Shell version, which is usually not the same as the one in the latest Ubuntu LTS. Sometimes, such as with v53 it is stated explicitly in the release notes which version it's for, which in the case of v53 was a backport to an earlier shell.

**Comment by brad** [comment]
To provide just a little more information to help those who like me struggle with the current state (in 22.04) of browsers not working with https://extensions.gnome.org:
1. Download [GSConnect 50](https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v50.shell-extension.zip) from extensions.gnome.org
2. Install by following the [install from zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) section of the wiki
