### ISSUE TITLE
Incompatible with GNOME 43

### ISSUE THREAD

**Issue by MANICX100** [GSConnect/gnome-shell-extension-gsconnect#1468]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**FYI for the devs it does not work in version 43 released yesterday. Technically only in pre-release or rolling distros (Tested with Fedora 37 and editing metadata.json file) but it IS the current version of GNOME**

It is like it is not installed. No indication in UI extension manager says failed to load.

**Expected behavior**

It show up under power menu and operate as normal

**Support Log**

Can't generate can't load window.

**System Details (please complete the following information):**

 - **GSConnect version:** 53 (current)
   - **Installed from:** GNOME Extensions flatpak app
 - **GNOME/Shell version:** 43
 - **Distro/Release:** Fedora 37

**Comment by MANICX100** [comment]
> This issue is related to:
> 
> [Issue #1428](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1428) [Pull Request #1444](https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1444)
> 
> If you go over the PR and apply the changes to the master -- it will work. That's how I'm using it right now.

Perfect thank you can confirm fix works as intended.

**Comment by yochananmarqos** [comment]
@steve-todorov How is it working for you? What distro are you using?

After updating from upstream 43-alpha / 43-beta / 43-rc to 43.0 packages, it stopped working for me. I'm using the fcgu [gnome-unstable](https://codeberg.org/fabiscafe/gnome-unstable) repo on the Manjaro unstable (almost identical to Arch stable) branch.

**Comment by MANICX100** [comment]
If this helps in your debugging I have
gnome-shell-43.0-2
installed
and working with GSConnect via the linked Pull Request

**Comment by yochananmarqos** [comment]
@MANICX100 

> I have gnome-shell-43.0-2 installed

From where?

This is my [PKGBUILD]([url](https://gitlab.manjaro.org/packages/community/gnome/gnome-shell-extension/-/blob/43/gnome-shell-extension-gsconnect/PKGBUILD)) using the latest commit from master + #1444

**Comment by MANICX100** [comment]
> @MANICX100
> 
> > I have gnome-shell-43.0-2 installed
> 
> From where?
> 
> This is my [PKGBUILD](https://gitlab.manjaro.org/packages/community/gnome/gnome-shell-extension/-/blob/43/gnome-shell-extension-gsconnect/PKGBUILD) using the latest commit from master + #1444
> 
> **EDIT**: Oops, I wasn't actually using the latest commit from master. However I was at the time you posted it was working for you.
> 
> It's now working with [5a03d39](https://github.com/GSConnect/gnome-shell-extension-gsconnect/commit/5a03d39a368dffbaba68ae116985c9f61f6b278f).

Good to know its working for you know.

Installed gnome-shell from fedora 37 repos

**Comment by bitseater** [comment]
If i can help: Working for me with changes from 34cb005d2a15def81b7988663806c1cc6eca26f1 .

Debian unstable + gnome-shell 43.0

**Comment by MacTavishAO** [comment]
A hack-together port here: https://github.com/MacTavishAO/gnome-shell-extension-gsconnect

**Comment by steve-todorov** [comment]
Just to add some more info - there is now an official PR https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1475 from @MacTavishAO with better implementation. :)

**Comment by liferooter** [comment]
When will be the release on extensions.gnome.org?

**Comment by steve-todorov** [comment]
Most likely when it's merged - yes :)
