### ISSUE TITLE
GSConnect does not pause media on call

### ISSUE THREAD

**Issue by pled** [GSConnect/gnome-shell-extension-gsconnect#1502]
**Describe the bug**

Despite setting telephony parameters to pause on calls (incoming or outgoing) like below : 

![telephony](https://user-images.githubusercontent.com/2879483/198337194-f08b23a5-0326-4a89-b7b2-eb668f4c7e52.png)

Music on desktop does not pause.

**Steps To Reproduce:**

Receiving call or calling someone with the smartphone while Rhythmbox is playing music on desktop.

**Expected behavior**

Music should pause

**Support Log**

I cannot see anything relevant in the log. Attached is a log initiated before calling someone and stopped after call starts. If some specific logs can be generated, let me know.

[gsconnect.EZKFU1.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/9881064/gsconnect.EZKFU1.txt)

**System Details (please complete the following information):**

- OS: Debian GNU/Linux bookworm/sid x86_64 
- DE : Gnome 43.0
- GSConnect : 54 installed from GNOME Extensions Website

- Paired Device : LineageOS 18.1 with KDEConnect 1.19.1 from F-Droid-

**Comment by MacTavishAO** [comment]
Works fine for me. Can you confirm that you have given necessary permission to the app on your phone? (Call logs, Phone and Notification access etc.)

**Comment by pled** [comment]
@MacTavishAO  : Thank you, that was the problem. I think "Call logs" was missing for some reason. 
Now I have "Contacts", "Call logs", "SMS" and "Telephony" as permissions for KDE Connect, and media is paused on call as expected.
Thank you for pointing the right direction.
