### ISSUE TITLE
Browser extension totally broken 'Service unavailable'

### ISSUE THREAD

**Issue by dm30** [GSConnect/gnome-shell-extension-gsconnect#1504]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

Everything works reasonably well but the browser extension for sharing links is totally broken. 'Service unavailable' I read in any browser, in Ubuntu or Windows or even Virtual machines. In Firefox, Chrome or any other browser packaged in any form. GSConnect or KDE connect. Doesn't make a difference. Stopped working at some point. Maybe with GNOME 43? 

**Steps To Reproduce:**

Click browser extension ---> returns 'Service unavailable'
I don't know if related to Gnome Shell extension notice "your system native connector doesn't support API: v6"

**Expected behavior**

'Send' option to registered devices.

**Screenshots**

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 54 (system)
GJS:       17400
Session:   x11
OS:        Ubuntu 22.10
--------------------------------------------------------------------------------
oct 29 22:03:03 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
oct 29 22:03:05 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
oct 29 22:03:06 gjs[19294]: Failed to load module "appmenu-gtk-module"
oct 29 22:03:06 dbus-daemon[1116]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.267' (uid=1000 pid=19294 comm="gjs /usr/share/gnome-shell/extensions/gsconnect@an" label="unconfined")
oct 29 22:03:06 systemd[1]: Starting Hostname Service...
oct 29 22:03:07 dbus-daemon[1116]: [system] Successfully activated service 'org.freedesktop.hostname1'
oct 29 22:03:07 systemd[1]: Started Hostname Service.
oct 29 22:03:15 org.gnome.Shell.Extensions.GSConnect[8063]: [/service/device.js:sendPacket:449]: Nokia 9

```

**System Details (please complete the following information):**

Ubuntu 22.10 (GNOME 43). Firefox 106 and other up to date browsers.

**Additional Notes:**

I'll check Windows as well

Thank you very much
Kind Regards

**Comment by mattsches** [comment]
It might be related to Firefox being installed as snap? Try

`flatpak permission-set webextensions org.gnome.shell.extensions.gsconnect snap.firefox yes`

If you don't have `flatpak` installed or want to know more about the specifics, read [this](https://www.bentasker.co.uk/posts/blog/general/enabling-nativemessaging-for-keepassxc-on-ubuntus-snap-firefox.html) for instructions and examples. There might be other documentation out there, but this post helped me fix it.

**Comment by dm30** [comment]
Thank you. Firefox is installed as a native package. But happens in any format, any OS. I'm alone with this? Very weird.

**Comment by thomasgauthier** [comment]
I'm also experiencing this on Arch Linux with Gnome 43.3 and LibreWolf 110.

**Comment by diegonz** [comment]
```
GSConnect: 55 (system)
GJS:       17600
Session:   x11
OS:        Ubuntu 23.04
-----------------------
```

Firefox as snap is working fine.
Chrome 114.0.5735.133 showed service unavailable couple of times, now the icon is greyed out and not even clickable.

**Comment by matteopaolucci** [comment]
Same problem here, i have the **flatpak** version and i can send link from android to my laptop but i can not do the opposite. The extension after clicking on it shows: _Service Unavailable_.

**Comment by NyllRE** [comment]
Same problem but on Vivaldi Browser, Fedora (Nobara). everything is up to date

**Comment by kachapman** [comment]
Same problem, Brave browser. Tried the Gnome extension version and got the same error.

**Comment by dm30** [comment]
Now works. I'll close it

**Comment by NyllRE** [comment]
@dm30  ???
![image](https://github.com/user-attachments/assets/f7820441-b6af-4652-b81c-21bdcd2d882d)

**Comment by niels0n** [comment]
So, still no fix?
