### ISSUE TITLE
GNOME 43 Icons missing

### ISSUE THREAD

**Issue by Eonfge** [GSConnect/gnome-shell-extension-gsconnect#1509]
**Describe the bug**

![Screenshot from 2022-11-08 19-20-42](https://user-images.githubusercontent.com/33983090/200644555-413535a6-a1d8-4462-81ee-331cfec9afb7.png)

![Screenshot from 2022-11-08 19-21-39](https://user-images.githubusercontent.com/33983090/200644730-dd592ab1-10e2-4e1b-b40b-4a63c2011935.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 54
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 43
 - **Distro/Release:** Fedora 37

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus 7Pro Lineage OS 11
 - **KDE Connect app version:**1.19.1

**Additional Notes: **

Please let me know if you need more info, I gladly provide additional logs if you tell me where to find them

**Comment by ludvigng** [comment]
It's still broken for me, even after both a reboot and uninstalling and reinstalling the extension. Switching to panel mode helps, since that icon shows up correctly, but the icon in the user menu/quick settings is broken regardless.

**Comment by ludvigng** [comment]
Oops, never mind. I noticed other icons that were missing when I installed some webapps. Apparently I was lacking the theme index for the hicolor theme. Once I created that, the issue went away! :)

**Comment by patriziobrunops** [comment]
It's still missing for me, I'm on Fedora Silverblue 37 with GNOME 43, the shell package is `gnome-shell-43.2-1.fc37.x86_64` updated to latest version this morning.

**Comment by andyholmes** [comment]
Closing, since I guess everyone got it working eventually? Re-open if not :)

**Comment by NotoriousNico** [comment]
@andyholmes 

I'm having the same issue on my Fedora 43 workstation with GNOME 49.
But I can't reopen the issue, unfortunately.

<img width="523" height="683" alt="Image" src="https://github.com/user-attachments/assets/1660efc9-ba29-420a-a38b-28d5d0fdb8a4" />

**Comment by NotoriousNico** [comment]
@andyholmes Thank you for reopening, it's much appreciated!

**As a workaround, I did the following:**

In `/usr/share/icons/Adwaita/symbolic/status`, I've created the following Link:

`org.gnome.Shell.Extensions.GSConnect-symbolic.svg`

The Link Target is:
`/usr/share/icons/Adwaita/symbolic/devices/phone-symbolic.svg`

<img width="1060" height="1792" alt="Image" src="https://github.com/user-attachments/assets/1dd3938f-7ef9-49ac-a10f-ae13d01e2568" />

**The result:**
<img width="515" height="643" alt="Image" src="https://github.com/user-attachments/assets/9adc4ca1-95cb-47d6-8917-d7f1d0f8f8d6" />

**Comment by Wartybix** [comment]
One of my relatives had this problem.

Deleting `~/.local/share/icons/hicolor/icon-theme.cache` seemed to fix it. After logging out and back in, the icon appeared as normal 😁.

**Comment by viinamarja** [comment]
> One of my relatives had this problem.
> 
> Deleting `~/.local/share/icons/hicolor/icon-theme.cache` seemed to fix it. After logging out and back in, the icon appeared as normal 😁.

worked for me. thx a lot!
