### ISSUE TITLE
Settings do not open on Gnome 43

### ISSUE THREAD

**Issue by meisme-dev** [GSConnect/gnome-shell-extension-gsconnect#1513]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

When you try to open the settings from the quick settings tile or the extensions app, you get no settings window.

**Steps To Reproduce:**

1. Try to access the settings

**Expected behavior**

The settings should open.

**Screenshots**

https://user-images.githubusercontent.com/49573906/201453388-b1539b40-63ce-4050-a8b2-f37cd7401396.mp4

**Support Log**

Unavailable (cannot access settings)

**System Details (please complete the following information):**

 - **GSConnect version:** Latest version on extensions.gnome.org as of Nov 11 10PM EST (cannot check version because settings is inaccessible)
   - **Installed from:** [Extension Manager](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager)
 - **GNOME/Shell version:** 43.0
 - **Distro/Release:** NixOS 22.11 (Raccoon)

**Comment by meisme-dev** [comment]
I found this in logs
![image](https://user-images.githubusercontent.com/49573906/201453505-7a84d803-7702-451f-8e19-43b335b1eed6.png)

**Comment by meisme-dev** [comment]
Installing GJS solves it :facepalm: my bad

**Comment by andyholmes** [comment]
We've had a "no xdg-data-dirs" bug before, but I never thought we'd get a "no GJS" report :stuck_out_tongue_closed_eyes:

**Comment by ferdnyc** [comment]
Extension Manager isn't implemented in GJS? Well... guess we've found a down side to that!
