### ISSUE TITLE
GSConnect doesn't work in GNOME 43 lock screen

### ISSUE THREAD

**Issue by shdwchn10** [GSConnect/gnome-shell-extension-gsconnect#1516]
**Describe the bug**

Right after entering in GNOME 43 lock screen GSConnect stops

**Steps To Reproduce:**

1. Enter lockscreen
2. Try to do something from your KDE Connect phone app
3. See that your PC was disconnected

**Expected behavior**

GSConnect should work in lockscreen as it was with GNOME 42

**Support Log**

https://pastebin.com/JFGVtUwv

**System Details (please complete the following information):**

 - **GSConnect version:** 54
   - **Installed from:** Fedora Linux repos
 - **GNOME/Shell version:** 43.1
 - **Distro/Release:** Fedora Silverblue 37.20221113.0

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel 5a
 - **KDE Connect app version:** 1.19.1

**Comment by andyholmes** [comment]
See https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1475#issuecomment-1271910239 for details about why this changed.

**Comment by MacTavishAO** [comment]
Removing [this line](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/extension.js#L291) should help you with that. Maybe this behaviour should be bound to a boolean @andyholmes?

**Comment by andyholmes** [comment]
Sure, we could add an option. Somewhere in the main preferences would probably work.

**Comment by andyholmes** [comment]
For an interested contributor, this would involve:

1. Adding a boolean setting to [`org.gnome.Shell.Extensions.GSConnect.gschema.xml`](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml)
2. Adding a UI element, like a switch, probably to [`preferences/service.js`](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/preferences/service.js)
3. Check the setting before calling `this.service.stop()` at [`extension.js`, Line #293](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/1e856ae5ce6fc5fc3a38e5ccab90a794a035b5c0/src/extension.js#L293)

**Comment by bluepostit** [comment]
Hi there, @andyholmes. I haven't built anything with GJS before, but I want to try to fix this issue as it affects me. 

I've added the boolean setting, and added a switch to `preferences/service.js` -- but I am having trouble binding the boolean to the switch. I tried duplicating the way that the code already binds the `enabled` setting boolean to a key, but I'm not getting how the binding is supposed to happen with a switch. Is there an API, or some visible example of doing something similar?

I'd be happy to open a pull request, although my work is not yet finished.

**Comment by andyholmes** [comment]
I'm just about to go to bed (super late!), but absolutely throw it up in a PR and I will happily look at it tomorrow :slightly_smiling_face:

**Comment by bluepostit** [comment]
Thanks! Sounds great. Please see #1537 :)

**Comment by andyholmes** [comment]
Fixed in #1537, thanks @bluepostit!

**Comment by mpi3d** [comment]
@bluepostit @andyholmes Thanks for your work!

**Comment by pacho2** [comment]
Hello!

Do you plan to release a new version with this fix for Gnome 43?

Thanks

**Comment by andyholmes** [comment]
@daniellandau will typically post a release when he has free time available and there's enough changes to warrant it. There aren't really any ETAs for things like this though :)

**Comment by pacho2** [comment]
OK, thanks!
