### ISSUE TITLE
Launching settings doesn't close user menu (GNOME 43)

### ISSUE THREAD

**Issue by ferdnyc** [GSConnect/gnome-shell-extension-gsconnect#1517]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

### Describe the bug

This one's specific to the new Quick-Settings-based menu options in GNOME Shell 43. Unlike, say, "Wired > Wired Settings" (which opens `gnome-control-center` to the wired networking panel), "GSConnect > Mobile Settings" doesn't _fully_ close the  user menu, only it submenu. This leaves the user unable to interact with the desktop windows until the user menu closes, as it will steal input.

### Steps To Reproduce

1. Open user menu
2. Click arrow widget ( > ) at end of "GSConnect" button to open submenu
3. Click "Mobile Settings"
4. Submenu closes (but user menu stays open)
5. Wait for "GSConnect Preferences" to launch
6. Attempt to interact with newly-launched window (and/or its headerbar)
7. Observe settings window headerbar ignoring input until user menu is closed, other inputs requiring an extra click to first close user menu

### Expected behavior

The user menu completely closes when "Mobile Settings" is clicked, and the entire desktop is immediately interactive. (Again, this is what happens when clicking "Wired Settings", and other Quick Settings submenu launchers.

### Behavior notes
_Most_ interactions -- like clicking inside the GSConnect settings window, for example -- will have the effect of closing the window and returning control to the user. But that first click is still lost to closing the menu.

And _**some**_ interactions, such as trying to click on or drag the GSConnect settings window headerbar, are completely ignored. They will both not register to the application and fail to close the still-open user menu. 

(Clicking other application windows' headerbars does close the open menu. I suspect the reason GSConnect's own window differs is that focus has been given to the preferences application already. ("GSConnect Preferences" is visible in the top bar application-focus area.) So clicking its headerbar doesn't register as a change of focus, which is the action that actually triggers the menu close.)

### System Details

 - **GSConnect version:** 54
   - **Installed from:** e.g.o
 - **GNOME/Shell version:** 43
 - **Distro/Release:** Fedora 37 beta

**Comment by andyholmes** [comment]
I think all that's needed is a few function calls in the activation callback:

```js
// In case we were in the overview
Main.overview.hide();

// Close up the top menu
Main.panel.closeQuickSettings();
```

**Comment by ferdnyc** [comment]
> Actually, I guess [`addSettingsAction()`](https://gjs.guide/extensions/topics/popup-menu.html#popupmenubase) could work here:

Ooh, I like that. Seems cleaner than manually `Subprocess.new()`-ing. (Though adding `Main.panel.closeQuickSettings()` did work, in the `_preferences` callback.)

I'll slap together a PR, thanks.

**Comment by ferdnyc** [comment]
Hrm. #TIL that the QuickSettings-enabled system menu will under no circumstances consent to being scrolled, and anything hanging off the bottom of the screen is just — to quote Hall & Oates — "Outta touch". (Not to mention, outta sight.)

That's quite unfortunate, on my 1366×768 pixel laptop screen.

**Comment by andyholmes** [comment]
Does GSConnect have a device menu? I thought that was removed except for the device item, for some reason,

**Comment by ferdnyc** [comment]
> Does GSConnect have a device menu? I thought that was removed except for the device item, for some reason,

It's got a per-device section, just like before -- they're just not submenus anymore. But if there's more than _one_ device, on my laptop, the second one to connect will end up mostly offscreen.

This is the full height of my laptop's display:

![image](https://user-images.githubusercontent.com/538020/202955619-e008bacf-30b7-479c-a6a7-f5519a70b24a.png)

(I took the screenshot to report the cut-off tooltip as #1519.)
