### ISSUE TITLE
Switch issue template licenses to `.license` files or `.reuse/dep5` configs?

### ISSUE THREAD

**Issue by ferdnyc** [GSConnect/gnome-shell-extension-gsconnect#1524]
So, turns out the license comment in `.github/ISSUE_TEMPLATE/bug_report.md` or `.../feature-request-or-idea.md` _will_ be included in the prefilled textarea, when GitHub generates a new issue form from the corresponding template file. Not the end of the world, but it also isn't ideal.

Might be worth moving the license metadata out of those `.md` template files using one of the REUSE-supported methods. Just so that we keep things as uncluttered/non-confusing as possible, when users are filling out the template.

**Comment by andyholmes** [comment]
Yes, I typically add `*.md` as `CC0-1.0`/`No rights reserved` in the `dep5` file. `.md` files rarely involve any material really worth applying any copyright to, in my experience.

**Comment by ferdnyc** [comment]
Heh. And in the end, I decided to just convert the markdown templates completely, into issue _forms_. (#1525)
