### ISSUE TITLE
Gsconnect won't work after installation

### ISSUE THREAD

**Issue by killown** [GSConnect/gnome-shell-extension-gsconnect#1547]
### Describe the bug

broken pipe

get@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:392:37
_initCertificate@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

### Steps to reproduce

error appear after installation.

### Expected behavior

...

### GSConnect version

all versions tried, git, from extension.gnome.com, any, none works

### Installed from

GNOME Extensions website

### GNOME Shell version

➜  ~ gnome-shell --version GNOME Shell 43.2

### Linux distribution/release

archlinux

### Paired device(s)

can't pair anything

### KDE Connect app version

updated one, last update.

### Support log

```plain text
This issue has been happening for several weeks already
```

**Comment by andyholmes** [comment]
Can you confirm that `openssl` is installed on your system? Can you confirm that the files `~/.config/gsconnect/certificate.pem` and `~/.config/gsconnect/private.pem` exist?

**Comment by killown** [comment]
➜  ~ ls  ~/.config/gsconnect/
➜  ~

**Comment by andyholmes** [comment]
I'm going to assume you don't have `openssl` installed then, and recommend you install that before retrying.

**Comment by killown** [comment]
was installed already core/openssl 3.0.7-4

**Comment by andyholmes** [comment]
Can you run this in a terminal and confirm it outputs a valid certificate and private key?

```sh
openssl req -new -x509 -sha256 -out 'certificate.pem' -newkey 'rsa:4096' -nodes -keyout 'private.pem' -days 3650 -subj '/O=andyholmes.github.io/OU=GSConnect/CN=foobar'
```

If that works, you'll need to figure out which install method you are using, so that you can confirm the location of the `openssl` binary is being passed correctly.

**Comment by killown** [comment]
Thanks a lot man, the issue was openssl wrong binary, nothing to do with gsconnect besides it uses ssl
