### ISSUE TITLE
Add "Settings" button to the system tray menu

### ISSUE THREAD

**Issue by hyuri** [GSConnect/gnome-shell-extension-gsconnect#1554]
### Describe your request

It takes a few steps to get to GSConnect's settings:
1. Open menu or launcher;
2. Search for the Extensions app;
3. Search for GSConnect within the Extensions app;
4. Click on Settings.

### Proposed solution

It would be great if we had a "Settings" button right inside GSConnect's system tray menu that took us straight into the settings in one go (2 clicks total).

Either a piece of text, "Settings", or a small cog icon at the end would work great.

### GSConnect version

47

### Installed from

Extension Manager

### GNOME Shell version

40.4.0

### Linux distribution/release

Pop!_OS 21.10

**Comment by delight-aug** [comment]
The button is present for me, it's named "Mobile settings"

![image](https://user-images.githubusercontent.com/51861383/213626606-e40da4e0-6c52-485c-80a3-633e1ecd53e5.png)

**Comment by hyuri** [comment]
Oh, it must be because I'm using the Big Sur Status Area extension, that puts the systray icons back at the top panel. My bad.

Thanks for letting me know!
