### ISSUE TITLE
Port already in use, but not by KDE.

### ISSUE THREAD

**Issue by synapt1c0llapse** [GSConnect/gnome-shell-extension-gsconnect#1555]
### Describe the bug

Port already in use, but not by KDE. 1716 used by gjs

### Steps to reproduce

1. Boot
2. Error message
3. Reinstall
4. Worx

### Expected behavior

It works automatically after the boot 

### GSConnect version

50

### Installed from

GNOME Extensions website

### GNOME Shell version

42.5

### Linux distribution/release

Ubuntu 22.04.1 LTS

### Paired device(s)

Redmi Note 7 Pro

### KDE Connect app version

1.21.1

### Support log

GSConnect: 50 (user)
GJS:       17400
Session:   wayland
OS:        Ubuntu 22.04.1 LTS
--------------------------------------------------------------------------------
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
янв 19 17:31:04 zeitgeist-datah[7484]: /home/rio/.local/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
янв 19 17:31:04 zeitgeist-daemon[8810]: [14:31:04.882410 WARNING] ext-fts.vala:138: Ошибка вызова StartServiceByName для org.gnome.zeitgeist.SimpleIndexer: Время ожидания истекло
янв 19 17:31:06 gjs[9432]: /home/rio/.local/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
янв 19 17:31:06 gvfsd[9511]: smbXcli_negprot_smb1_done: No compatible protocol selected by server.
янв 19 17:31:06 gvfsd[9511]: got no contact to IPC$
янв 19 17:31:06 gvfsd[9511]: smbXcli_negprot_smb1_done: No compatible protocol selected by server.
янв 19 17:31:06 gvfsd[9511]: got no contact to IPC$
янв 19 17:31:07 pkexec[9547]: rio: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/home/rio] [COMMAND=/usr/lib/update-notifier/package-system-locked]
янв 19 17:31:07 update-notifier.desktop[9547]: Error executing command as another user: Not authorized
янв 19 17:31:07 update-notifier.desktop[9547]: This incident has been reported.
янв 19 17:31:07 update-notifier[9391]: /home/rio/.local/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
янв 19 17:31:07 gnome-shell[2700]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
янв 19 17:31:07 ubuntu-appindicators@ubuntu.com[2700]: unable to update icon for software-update-available
янв 19 17:31:07 gnome-shell[2700]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
янв 19 17:31:07 ubuntu-appindicators@ubuntu.com[2700]: unable to update icon for livepatch

**Comment by ferdnyc** [comment]
@synapt1c0llapse 

`gjs` is the GNOME JavaScript interpreter that extensions are run in, so (although I don't see any signs of it in the logs) it _sounds_ like the port is already in use **by GSConnect itself**.

Two possibilities:

1. Were you upgrading GSConnect? It could've just been a one-time conflict, where the new version was trying to start while the old one was still running. In which case, if it cleared up after a reboot it probably won't happen again.

1. Is it possible GSConnect is installed in two places on your system? Sometimes, a user will have a system package installed in `/usr/share/gnome-shell/extensions/`, and then also install it to their `$HOME/.local/share/gnome-shell/extensions/` directory. If you do have GSConnect installed to `/usr/share/` as a system package, and you don't need it because you're using it from `$HOME/.local/share/`, you can uninstall the system package with `sudo apt remove gnome-shell-extension-gsconnect` which may help prevent future conflicts.

**Comment by ferdnyc** [comment]
Ignore my first thought, if it happened right after boot then it's not likely to be an upgrade issue. It's probably number 2.

**Comment by synapt1c0llapse** [comment]
> Ignore my first thought, if it happened right after boot then it's not likely to be an upgrade issue. It's probably number 2.

**Comment by synapt1c0llapse** [comment]
It's just in  `$HOME/.local/share/gnome-shell/extensions/ `, and there aren't any installations.

**Comment by andyholmes** [comment]
I would conjecture that installing more clients will not solve your problem. Can you show the output of `lsof -i UDP:1716` immediately after you get the error?

**Comment by reinhart1010** [comment]
Or can you check the output of `sudo netcat -nutlp | grep 1716` on your system, in case you have sudo access?

**Comment by synapt1c0llapse** [comment]
```
rio@N76:~$ lsof -i UDP:1716
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gjs     5108  rio   22u  IPv6  45345      0t0  UDP *:1716 
```
and 
```

rio@N76:~$ sudo netcat -nutlp | grep 1716
netcat: option requires an argument -- 'p'
usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-M ttl]
	  [-m minttl] [-O length] [-P proxy_username] [-p source_port]
	  [-q seconds] [-s sourceaddr] [-T keyword] [-V rtable] [-W recvlimit]
	  [-w timeout] [-X proxy_protocol] [-x proxy_address[:port]]
	  [destination] [port]
;)```

**Comment by daniellandau** [comment]
The command should have been netstat, not netcat

**Comment by andyholmes** [comment]
It sounds like there are two versions of GSConnect installed. Can you check if there are two processes running?

**Comment by synapt1c0llapse** [comment]
I thought then it must be 

> It sounds like there are two versions of GSConnect installed. Can you check if there are two processes running?

I thought then it must be displayed in tray drop down menu (or how it titles right...)
How can I do it alternate way?

**Comment by andyholmes** [comment]
The solution is to uninstall it from everywhere except the extensions website. If you installed it with Extension Manager, you should uninstall any distribution package.

> Seems like the is the same daemon

GSConnect can only run one instance. The only way this can happen is if another copy of GSConnect is installed or another KDE Connect client is installed.
