### ISSUE TITLE
GSConnect fails to detect device with error code 127

### ISSUE THREAD

**Issue by Adrian-Benavente** [GSConnect/gnome-shell-extension-gsconnect#1569]
### Describe the bug

Since about a month GSConnect stopped detecting my mobile phone and if I uninstall and reinstall the extension I inmediately get a desktop notification with an error GSConnect: Error. And if I click on it I'm prompted to report the error with the following stack trace:

### Steps to reproduce

Log in to your session or uninstall and reinstall the extension

### Expected behavior

The mobile phone where the KDEConnect app is installed should be detected and also the other way round

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43.3

### Linux distribution/release

Fedora 37

### Paired device(s)

Redmi 9

### KDE Connect app version

1.22.1

### Support log

```plain text
El proceso hijo terminó con el código 127

Gio.TlsCertificate.new_for_paths@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/fena/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment]
@Adrian-Benavente 

As the extension is crashing where it's trying to set up the TLS Certificate (for encrypted communication), I suspect you either don't have permission to access your keys directory, or you don't have `openssl` installed on your machine.

I _thought_ `openssl` was one of those packages that couldn't really be uninstalled, but who knows? Or, maybe it's an ownership error.

Try this, to examine/fix the problem:

```sh
# Make sure the openssl package is installed
sudo dnf install openssl

# Check that it's in your $PATH and can be run
which openssl    # => /usr/bin/openssl
openssl version  # => OpenSSL 3.0.8 7 Feb 2023 ...

# Check permissions on the directory where keys are stored
ls -ld $HOME/.config/gsconnect  # => drwxr-xr-x. <you> <you> ...

# See if anything's been written there already
ls -l $HOME/.config/gsconnect
```

The last command's output should look something like,
```console
$ ls -l $HOME/.config/gsconnect 
total 21k
-rw-------. 1 ferd ferd 1.2k Nov 19  2017 certificate.pem
-rw-------. 1 ferd ferd 1.9k Jun 25  2020 id-gsconnect
-rw-------. 1 ferd ferd 1.2k Sep 25  2020 id-gsconnect-cert.pub
-rwx------. 1 ferd ferd  391 Jun 25  2020 id-gsconnect.pub
-rw-------. 1 ferd ferd 1.8k Nov 19  2017 private.pem
```

You probably won't have the 2017-era files without 'gsconnect' in the name, I'm pretty sure those are outdated and I should probably delete them.

If any of those files/directories are owned by `root`, or by a different username than your own, that would likely be the problem right there.

**Comment by Adrian-Benavente** [comment]
Thanks beforehand for your help!
This is the output for each command
```
sudo dnf install openssl  # => ...already installed...

which openssl    # => /usr/local/bin/openssl
openssl version  # => openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory **(maybe this is the problem?)**

ls -ld $HOME/.config/gsconnect  # => drwxr-xr-x. <you> <you> ... (this one is identical)

ls -l $HOME/.config/gsconnect  # => total 0
```

**Comment by Adrian-Benavente** [comment]
Solved by installing `openssl1.1`, my current version was 1.3
