### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by Scotty-Trees** [GSConnect/gnome-shell-extension-gsconnect#1573]
### Describe your request

Greetings,

I know it's still a little bit early, but Gnome 44 alpha/beta are out now for testing purposes and I was wondering if/when the extension will be updated? Some extensions are already being updated to support the latest which is very nice to see. The final release for Gnome 44 should be on March 22nd, 2023 btw. Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

### GSConnect version

54

### Installed from

Extension Manager

**Comment by andyholmes** [comment]
For anyone interested in working on this, there is a guide for [Porting to GNOME 44](https://gjs.guide/extensions/upgrading/gnome-shell-44.html) available on [gjs.guide](https://gjs.guide).

**Comment by sidevesh** [comment]
In case someone is taking a look at picking this up,
do consider https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1506 please.
Thanks.

**Comment by yochananmarqos** [comment]
Well, especially since the tile on GNOME 44 is blank, I guess it's now a clean slate. 😜

The extension works otherwise, by the way.

**Comment by retrixe** [comment]
One thing that could be improved (before releasing, possibly?) is adding the connected devices as a subtext like the updated Bluetooth sub-menu in GNOME 44:
![image](https://user-images.githubusercontent.com/6884828/226750887-820fd6f1-1cbe-40b7-839f-c7373c307ab4.png)
![image](https://user-images.githubusercontent.com/6884828/226750951-8dece960-6138-4ecc-a22a-a77ef5a7e6ef.png)
![image](https://user-images.githubusercontent.com/6884828/226751272-a657a029-6068-4778-a62a-7ccce8149cbb.png)
This would also solve #1506

**Comment by maggu2810** [comment]
But isn't it a general improvement? How is this improvement related to the porting of existing functionality to GNOME 44?

**Comment by yochananmarqos** [comment]
@retrixe It's already been done with the [Valent extension](https://github.com/andyholmes/gnome-shell-extension-valent):

![image](https://user-images.githubusercontent.com/5437803/226756038-6c02840a-4508-441c-b6c6-80a74b7004e4.png)

**Comment by retrixe** [comment]
This was actually rather easy to do (and the code change is simple and shouldn't introduce any bugs), so I've made a pull request here with the necessary functionality to get this working: #1581 

> But isn't it a general improvement? How is this improvement related to the porting of existing functionality to GNOME 44?

Arguably, this was dropped when going from 42 to 43. GSConnect doesn't release often as far as I can tell, so it would be great if we can get this in before releasing the GNOME 44 version.

> @retrixe It's already been done with the [Valent extension](https://github.com/andyholmes/gnome-shell-extension-valent):
>
> ![image](https://user-images.githubusercontent.com/5437803/226756038-6c02840a-4508-441c-b6c6-80a74b7004e4.png)

Interesting, I'll keep an eye on this project (it seems to be in alpha atm so I'll wait a while). Still, GSConnect is supposed to be maintained still, so it shouldn't be an issue to add this quality-of-life tweak to the extension.

**Comment by yochananmarqos** [comment]
@retrixe Hooray!

![image](https://user-images.githubusercontent.com/5437803/226769580-825d5e3d-c41f-4287-9bc5-c9e86216cd5f.png)

**Comment by sidevesh** [comment]
Just an idea but is the GSConnect label really necessary ?
It feels less well integrated into the system.
Although I am not able to think of something to replace that label with that will fit within the space available abd be meaningful.

**Comment by sidevesh** [comment]
Maybe we show the device name with battery percentage in subtitle if there's a single device connected or we show "2 devices" with devide names or battery percentages in subtitle if multiple devices are present.

**Comment by sidevesh** [comment]
I guess the Devices label that Valent extension shows works too.

**Comment by teohhanhui** [comment]
> Just an idea but is the GSConnect label really necessary ?

It's consistent with other quick settings tiles. Also, how would you tell it's GSConnect otherwise?

**Comment by sidevesh** [comment]
Most other quick settings tiles mention the feature it toggles on or off or shows details of.
Not what application or extension implements that toggle.
GSConnect label makes it stick out from all the other toggles there, and I think the fact that Valent also implemented the toggle with Devices label is a good indication of how this should be implemented, given that there are no HIGs for the quick settings toggles at least yet.

**Comment by andyholmes** [comment]
I'd love to be proven wrong, but I think the truth is there's no good word here. Really the two words to work with are "connect" and "device", two of the vaguest and most common words in computing 

I picked "Devices" for Valent, because I thought it looked weird just saying "Valent" (and "GSConnect). I think GSConnect's old drop down said something like "Mobile Devices" and "Mobile Settings", but that's not right either since they could be latpops, etc.

The logical choice is "KDE Connect", since that's the closest thing to a word like "Bluetooth" there is, but "KDE Connect" clearly wasn't chosen as a name of a technology like Wi-Fi or NFC.

Maybe someone should open a vote in the Discussions, or one of the maintainers could do it to make it seem a bit more official?

**Comment by daniellandau** [comment]
IMO GSConnect is fine as the label. It's currently an extension (although maintained by some GNOME foundation members) so it doesn't have to be fully "well integrated".

GSConnect is now live for GNOME 44 at e.g.o, so I'm closing this issue. Feel free to open new issues as needed and thanks @istvan-derda and @retrixe for doing the work!
