### ISSUE TITLE
GSConnect ignores some/all freedesktop Notifications

### ISSUE THREAD

**Issue by ferdnyc** [GSConnect/gnome-shell-extension-gsconnect#1591]
### Describe the bug

In a discussion (#1586), @aplumez asked why GSConnect wasn't registering / able to relay notifications created by Google Chrome. It turns out, <s>we're not looking at the correct field(s) of the notification body, to match those notifications up to their source application.</s> (See below.)

### Steps to reproduce

1. Visit https://www.bennish.net/web-notifications.html using Google Chrome
2. Authorize notifications for the site, and then use the Show button to create a test notification.
3. Look for Chrome in a device's Notifications list — it will not appear

### Expected behavior

GSConnect recognizes the test notification as coming from Chrome, and adds it to the list of applications for which notifications can be shared.

### GSConnect version

54

### Installed from

other source

### GNOME Shell version

43.3

### Linux distribution/release

Fedora 37

### Paired device(s)

--

### KDE Connect app version

--

### Notes

Sniffing notification traffic with `dbus-monitor` proves enlightening:

```console
$ dbus-monitor --session "interface='org.freedesktop.Notifications'"
method call time=1680638594.410850 sender=:1.21695 -> destination=org.freedesktop.Notifications serial=250 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Google Chrome"
   uint32 0
   string "file:///tmp/.com.google.Chrome.3F5zhp"
   string "Notification #8"
   string "www.bennish.net

This is the text body of the notification. 
Pretty cool, huh?"
   array [
      string "default"
      string "Activate"
      string "settings"
      string "Settings"
   ]
   array [
      dict entry(
         string "urgency"
         variant             uint32 1
      )
      dict entry(
         string "desktop-entry"
         variant             string "google-chrome"
      )
      dict entry(
         string "image_path"
         variant             string "/tmp/.com.google.Chrome.TGa9S6"
      )
      dict entry(
         string "image-path"
         variant             string "/tmp/.com.google.Chrome.TGa9S6"
      )
   ]
   int32 -1
```

The first argument is what GSConnect detects as the `appName`, and that's set to `"Google Chrome"`. But what we _**should**_ be looking for (preferentially, at least, if present) is the [standard](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints) entry in the `hints` dictionary: `desktop-entry`.

The `desktop-entry` hint is set to `google-chrome`, which corresponds to the `google-chrome.desktop` file that's used to identify the application.

**Comment by ferdnyc** [comment]
So... turns out the issue _wasn't_ actually that. "Google Chrome" should be fine as an app name to look up.

The problem is, the `destination` field of notifications sent by Chrome contains (as you can see above) `org.freedesktop.Notifications`. And since commit 4734c8feb82ff9f955b774ed34c8b76b15fa4ca4, the code would **only** accept the `destination` field being set to the _owner_ of that interface — IOW, on my current system, with:

```console
$ dbus-send --session --print-reply --dest=org.freedesktop.DBus \
$ /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner \
$ string:org.freedesktop.Notifications
method return time=1680648019.558408 sender=org.freedesktop.DBus ->
destination=:1.24198 serial=4294967295 reply_serial=2
   string ":1.60"
```

...The code now requires the `destination` to be `:1.60` and _only_ `:1.60` — anything else would cause `_onHandleMethodCall()` to `return` without processing the notification. Which is exactly what was happening to the Chrome notifications.

It looks like I can put in a check for `message_body.destination() === "org.freedeskop.Notifications"`, to end-run around the name-owner lookup dealie. At least on my system, when the duplicate notification mesaages come across the bus, only _one_ is ever sent **to** `org.freedesktop.Notifications`. (The other is a relay sent _from_ `:1.60` to some other destination.)

cc: @andyholmes

**Comment by ferdnyc** [comment]
Bingo!

![image](https://user-images.githubusercontent.com/538020/229940179-fc58cdbb-58b5-4177-90f1-7fa4dbe33f13.png)


Arguably we should be using the `image_path` / `image-path` (SRSLY?) field from the `hints` as the icon, instead of the application icon, since web notifications can be accompanied by their own icons representing the source website. On my desktop, that same notification looks like this:

![image](https://user-images.githubusercontent.com/538020/229940316-0ffeb3c1-9e3a-48ac-8c09-ea0ac1626fdd.png)



...But, baby steps.

**Comment by andyholmes** [comment]
> Arguably we should be using the `image_path` / `image-path`

That makes sense, it should be fairly trivial to just check for the "secondary" image and use the application icon as the fallback.

**Comment by ferdnyc** [comment]
I'll convert that comment to a new issue, so we don't lose track of it.

**Comment by ferdnyc** [comment]
> `image_path` / `image-path` (SRSLY?)

Turns out, that's because `image_path` is deprecated in the standard, so Chrome is being backwards-compatible I guess.

(There's also `image-data` / (deprecated) `image_data` / (deprecated) `icon_data` — _man_, they were indecisive — which can hold a super-complicated Variant providing raw image data. No idea if anyone's ever actually used that.)
