### ISSUE TITLE
stuttering when interacting with a music player, "Unhandled promise rejection" in journalctl

### ISSUE THREAD

**Issue by back-lacking** [GSConnect/gnome-shell-extension-gsconnect#1605]
### Describe the bug

when interacting with music in a music player (in my case, strawberry music player), eg. playing/pausing and skipping to the next song, there would be a slight stutter. 
https://pastebin.com/m2agA2Sk journalctl log

### Steps to reproduce

1. open music player of choice
2. play music
3. pause/resume, skip a song or go back to previous track. 
4. observe if there is a stutter. 

### Expected behavior

the system doesnt stutter when playing/pausing, skipping songs, etc in a music player. 

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43.4

### Linux distribution/release

Fedora 37

### Paired device(s)

LG G7 ThinQ

### KDE Connect app version

1.24.0

### Support log

```plain text
https://pastebin.com/HjgDAWgY because github cant send the issue with the raw text
```

### Notes

If more info is needed, tell me.

**Comment by back-lacking** [comment]
https://cdn.discordapp.com/attachments/693925504725549120/1096654427668094986/gsconnect-stutter.mp4 video showing stutter

**Comment by andyholmes** [comment]
Thanks for the report and logs!

Looks like there is indeed an uncaught `Promise` in the [`lan`](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/v54/src/service/backends/lan.js#L916) plugin. I'm not sure if that's the cause of the stutter, but it would be good place to start.

**Comment by ferdnyc** [comment]
@back-lacking Unfortunately, that pastebin seems to have expired, so the log can no longer be accessed.

Please attach the log directly to this report (you can insert files directly into a comment using the GitHub web interface — `.txt` and `.log` files are accepted directly, any other format should be stored inside a `.zip` archive) so that we can use them to track down the problem.

**Comment by back-lacking** [comment]
> @back-lacking Unfortunately, that pastebin seems to have expired, so the log can no longer be accessed.
> 
> Please attach the log directly to this report (you can insert files directly into a comment using the GitHub web interface — `.txt` and `.log` files are accepted directly, any other format should be stored inside a `.zip` archive) so that we can use them to track down the problem.

[gsconnect.6ZBE31.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11303941/gsconnect.6ZBE31.txt)
[gsconnect.N68021.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11303942/gsconnect.N68021.txt)
here are the 2 logs i gathered for this issue

**Comment by andyholmes** [comment]
You can give the [test build](https://github.com/GSConnect/gnome-shell-extension-gsconnect/suites/12453336772/artifacts/663165232) from #1609 a shot if you want. I'm not sure if it will solve the stuttering though.

**Comment by back-lacking** [comment]
> You can give the [test build](https://github.com/GSConnect/gnome-shell-extension-gsconnect/suites/12453336772/artifacts/663165232) from #1609 a shot if you want. I'm not sure if it will solve the stuttering though.

just installed it using the install from zip instructions and now its "outdated" in the installed extensions 
![image](https://user-images.githubusercontent.com/86173810/234124777-f288137b-78c2-445f-bbb5-55bbd0717c82.png)
i remember i did a fix for a different extension which required me to chage like a json file and add my gnome version to it. does this need to be applied here?

**Comment by andyholmes** [comment]
Yeah, GSConnect has moved to GNOME 44, so you'll have to add `"43"` to your `metadata.json`.

**Comment by back-lacking** [comment]
> Yeah, GSConnect has moved to GNOME 44, so you'll have to add `"43"` to your `metadata.json`. That's in `/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`.

trying to access that path returns an error, as that dir doesnt exist on my system. i remember i did it for an extension but forgot which one. also forgot where fedora stores the extension

**Comment by andyholmes** [comment]
Sorry, there should be a `~` at the beginning, so `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`.

**Comment by back-lacking** [comment]
> Sorry, there should be a `~` at the beginning, so `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`.

so i did that edit, relogged into my user, and now the extension is just gone

**Comment by andyholmes** [comment]
It should look more like `"shell-version": ["43, "44"],`.

**Comment by ferdnyc** [comment]
Unfortunately I don't think that will work, see #1611. Last time I had to get a test build to a GNOME 43 user, I built one locally off the `v54` tag and uploaded it as an attachment to the issue.

**Comment by back-lacking** [comment]
> It should look more like `"shell-version": ["43, "44"],`.

unable to enable to extensions, its just red and i cant turn it on. 
![image](https://user-images.githubusercontent.com/86173810/234356923-ad3aa0fe-ba70-4259-9131-58982cebde62.png)

**Comment by andyholmes** [comment]
If you copied that exactly, there was a typo in there. You'll want to add that missing quotation. Here's a ZIP:

[gsconnect@andyholmes.github.io.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11325879/gsconnect%40andyholmes.github.io.zip)

**Comment by back-lacking** [comment]
> ~If you copied that exactly, there was a typo in there. You'll want to add that missing quotation. Here's a ZIP:~
> 
> ~[gsconnect@andyholmes.github.io.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11325879/gsconnect%40andyholmes.github.io.zip)~
> 
> Frank's probably right, so here's a ZIP that might work built off the last GNOME 43 commit I could find:
> 
> [gsconnect@andyholmes.github.io.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11325965/gsconnect%40andyholmes.github.io.zip)



> ~If you copied that exactly, there was a typo in there. You'll want to add that missing quotation. Here's a ZIP:~
> 
> ~[gsconnect@andyholmes.github.io.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11325879/gsconnect%40andyholmes.github.io.zip)~
> 
> Frank's probably right, so here's a ZIP that might work built off the last GNOME 43 commit I could find:
> 
> [gsconnect@andyholmes.github.io.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11325965/gsconnect%40andyholmes.github.io.zip)

just installed it, here is a fresh log. 
[gsconnect.P15231.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11327187/gsconnect.P15231.txt)

**Comment by andyholmes** [comment]
Well the error gets caught now, I bet that's the cause of a lot of uncaught promise rejections so might as well merge it. Thanks for testing!

Looks like the old [packet queue on the device-side](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1025) problem.
