### ISSUE TITLE
REGRESSION: "Mobile Settings" option no longer works in GNOME 44.

### ISSUE THREAD

**Issue by iguanajuice** [GSConnect/gnome-shell-extension-gsconnect#1623]
### Describe the bug

I've upgraded to GNOME 44.1 on my laptop, only to find that the "Mobile Settings" option doesn't function. When attempting to use the button on my desktop computer; which is running GNOME 43.5, it works as intended. When updating GNOME on my desktop, this bug is also present. Snapshoting back to GNOME 43.5 fixes the issue.

You can still access the mobile settings by going through GNOME Extension Manager. 

### Steps to reproduce

1. Upgrade to GNOME 44.
2. Install GSConnect extension
3. Click on top right menu
4. Click on right arrow on "GSConnect"
5. Click on "Mobile Settings"

### Expected behavior

Clicking on "Mobile Settings" should launch the GSConnect settings window.

### GSConnect version

55

### Installed from

Extension Manager

### GNOME Shell version

44.1

### Linux distribution/release

Arch

### Paired device(s)

LG V40 ThinQ

### KDE Connect app version

1.24.5

**Comment by daniellandau** [comment]
Could you try generating a support log? On my computer the button does work.

**Comment by iguanajuice** [comment]
Odd. Seems to be working now.
