### ISSUE TITLE
Mildly annoying notifications

### ISSUE THREAD

**Issue by gaussandhisgun** [GSConnect/gnome-shell-extension-gsconnect#1624]
### Describe the bug

If my Android phone gets a notification which is set to be passed through to desktops, I receive it on my laptop. That's fine. But if I try to dismiss the notification, it just pops back. Indefinitely. Until i remove it from the phone.

### Steps to reproduce

1. Set up Notifications plugin in KDE Connect so you can easily get a notification to appear on your phone and be sent over to your desktop (in my case, i pass all the Termux:API notifications)
2. Create or receive a notification in any way
3. Try to dismiss it from the desktop

### Expected behavior

The notification should disappear either from _just_ the desktop or from _both_ desktop and phone, forever and ever.

### GSConnect version

55 (also happened on earlier versions)

### Installed from

GNOME Extensions website

### GNOME Shell version

44.1 (also happened on earlier versions)

### Linux distribution/release

Arch (updated yesterday)

### Paired device(s)

Redmi Note 9S (Android 13), Waydroid x86_64 (Android 11)

### KDE Connect app version

1.24.5 (F-Droid, also happened on earlier versions)

### Plugin(s)

Notification Sync (from android side)

### Support log

```plain text
https://katb.in/hiruqexagig - the notification that i was trying to dismiss this time is "Sample Notification".
```

### Screenshots

https://photos.app.goo.gl/7ZW85PWFWPGZZSSUA - a video description

**Comment by andyholmes** [comment]
Are you using any other extensions that may interfere with GSConnect's ability to track notifications?

**Comment by ferdnyc** [comment]
It's possible this extension was interfering:

> JS WARNING: [.../notifications_to_file@fawtytoo/extension.js 37]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3

**Comment by andyholmes** [comment]
Yeah, that caught my attention, too.

**Comment by gaussandhisgun** [comment]
oh yeah, this still exists. for whatever reason, this issue does not happen with Waydroid running android 11 anymore, but *still* happens with my phone running android 13. weird

**Comment by andyholmes** [comment]
> Are you using any other extensions that may interfere with GSConnect's ability to track notifications?

Any response for this?

**Comment by gaussandhisgun** [comment]
> > Are you using any other extensions that may interfere with GSConnect's ability to track notifications?
> 
> Any response for this?

i am using notification log and notification expand, but that should not influence the fact that *specifically on my phone* the notifications sent *to my phone* dont get removed when they are removed on my laptop. and the fact that the same scenario, but with Waydroid, somehow works perfectly fine

**Comment by gaussandhisgun** [comment]
> It's possible this extension was interfering:
> 
> > JS WARNING: [.../notifications_to_file@fawtytoo/extension.js 37]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3

also that extension does not work at all, should've removed it a long time ago

**Comment by gaussandhisgun** [comment]
notably, removing that did not help; also, buttons like "Mark as read" dont do anything either. up to date version stuff: GSConnect 55, gnome 44.5, kde connect 1.29.0 f-droid

**Comment by andyholmes** [comment]
Not sure then, I see GSConnect sending requests to close remote notifications from "termux". That seems to indicate there's nothing going wrong on GSConnect's side.

**Comment by gaussandhisgun** [comment]
aaand its just now i notice that this is basically a direct clone of #789 - which, by the way, is also still unresolved :thinking:

**Comment by gaussandhisgun** [comment]
i might have found something, will report there (as this is a dub anyway)
