### ISSUE TITLE
Fresh install cannot launch Settings "error sending ActivateAction message..."

### ISSUE THREAD

**Issue by neekfenwick** [GSConnect/gnome-shell-extension-gsconnect#1626]
### Describe the bug

Freshly installed the extension (never installed before) and I see it in the system dropdown, but clicking Mobile Settings in its tab doesn't seem to do anything.  Inspecting the journal (journalctl -xe) shows an error:

```
May 19 10:28:55 uberneek org.gnome.Shell.Extensions.GSConnect.Preferences.desktop[31317]: error sending ActivateAction message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
May 19 10:28:55 uberneek systemd[2651]: app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-31317.scope: Couldn't move process 31317 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-31317.scope': No such process
May 19 10:28:55 uberneek systemd[2651]: app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-31317.scope: Failed to add PIDs to scope's control group: No such process
May 19 10:28:55 uberneek systemd[2651]: app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-31317.scope: Failed with result 'resources'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has entered the 'failed' state with result 'resources'.
May 19 10:28:55 uberneek systemd[2651]: Failed to start app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-31317.scope - Application launched by gnome-shell.
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished with a failure.
░░ 
░░ The job identifier is 1895 and the job result is failed.
```

I've no idea how to debug this further :)

### Steps to reproduce

1. Go to the gnome system menu at top right of screen
2. click on the ">" next to GSConnect to expand its panel
3. click on "Mobile Settings"

### Expected behavior

I think it should launch some kind of App or UI but nothing appears.

### GSConnect version

55 (according to extensions/gsconnect@andyholmes.github.io/metadata.json)

### Installed from

GNOME Extensions website

### GNOME Shell version

44

### Linux distribution/release

Fedora release 38

### Support log

```plain text
I cannot generate support log because the UI won't come up.
~/.cache/gsconnect does not exist on my system.
~/.config/gsconnect does not exist on my system.
```

### Notes

This is a pretty normal Fedora 38 desktop workstation I use for software development.  Recently upgraded from Fedora 37 which went smoothly.

**Comment by andyholmes** [comment]
Those logs are more than enough to get the idea, thanks :)

Fedora should be just fine, so my first guess here is that some part of the desktop has not picked up on the installed desktop files.

GSConnect installs one `.desktop` file for the service and one for the preferences, so that it's recognized. It also installs a D-Bus `.service` file so that it can be auto-started, or started by the preferences app.

I'd first suggest just logging out/in to give that a jumpstart, and make sure you haven't accidentally installed it as an RPM *and* from the website.

**Comment by neekfenwick** [comment]
Tried this again today and the Mobile Settings button brings up a dialog OK, so I guess whatever problem I ran into just needed a restart or something.

Closing, thanks!
