### ISSUE TITLE
Messaging window too large.

### ISSUE THREAD

**Issue by MaxTheSpy** [GSConnect/gnome-shell-extension-gsconnect#1629]
### Describe the bug

After installing Zorin connect, which has the GSConnect built into the ISO. I noticed that the messaging window is much too wide. The height is fine, about 1/3rd to 1/4 the screen tall. The width is about 4-5 total screen widths. I would think it should be less than 1 screen width with the ability to expand if needed.

After finding the edge of the window, I am then able to make it wider, but not narrower.

### Steps to reproduce

connect phone, Launch messages, window pops up wayy too big.

### Expected behavior

Window should be 1 screen width or less.

### GSConnect version

53

### Installed from

other source

### GNOME Shell version

3.38.4

### Linux distribution/release

Zorin 16.2

### Paired device(s)

Samsung S22+

**Comment by ferdnyc** [comment]
@MaxTheSpy 

While it's true that the Zorin Connect extension is based on GSConnect, they've forked the code and done their own thing with it — you'd have to report any issues you encounter with it over in their repo ([ZorinOS/gnome-shell-extension-zorin-connect](https://github.com/ZorinOS/gnome-shell-extension-zorin-connect)), unless you can reproduce the problem with (actual-)GSConnect.

**Comment by barondem** [comment]
Hi, I can confirm that this bug is reproducible also on original GSConnect extension (Fedora 38, GSConnect 55). If it can be useful, in my case the GSConnectMessagingWindow's width is about 28000 pixels.
