### ISSUE TITLE
Не работает функция: "Примонтировать"

### ISSUE THREAD

**Issue by VitaliyMkhchyan** [GSConnect/gnome-shell-extension-gsconnect#1634]
### Describe the bug

При нажатии на кнопку: "Примонтировать" нечего не происходит

### Expected behavior

В файловом менеджере папку с файлами android телефона

### GSConnect version

1.25.0

### Installed from

GNOME Extensions website

### Linux distribution/release

Fedora 38

### Paired device(s)

Samsung A30s

### KDE Connect app version

55

### Screenshots

[gsconnect.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/11601776/gsconnect.txt)

**Comment by andyholmes** [comment]
Duplicate of #1203
