### ISSUE TITLE
Gsconnect error

### ISSUE THREAD

**Issue by Ghost707** [GSConnect/gnome-shell-extension-gsconnect#1635]
### Describe the bug

Gs connect just crashed after a recent update. It was either that or the fact that i recently built libssl from sourcce recently. Its no longer even launching.

### GSConnect version

55

### Installed from

Extension Manager

### GNOME Shell version

44

### Linux distribution/release

Archlinux

### Paired device(s)

Xioami Redmi Note 10

### KDE Connect app version

1.25.0

### Support log

```plain text
Error writing to file descriptor: Broken pipe

get@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:372:37
_initCertificate@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:186:13
start@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:444:18
_loadBackends@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:259:25
start@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:462:14
vfunc_startup@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:262:22
vfunc_handle_local_options@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:668:18
@/home/aditya/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:731:17
```

**Comment by ferdnyc** [comment]
@Ghost707 

You say you build _libssl_ from source — does your **`openssl`** command still work properly?

GSConnect issues `openssl` commands to manage its encryption, and line 372 of `service/__init__.js` is one of those command lines. Basically, if you can't run this command in the shell, GSConnect won't be able to do what it needs to do to build encrypted network connections:

```bash
openssl x509 -noout -dates -in $HOME/.config/gsconnect/certificate.pem
```

If everything is working properly, that should print a `notBefore` date in the past, and a `notAfter` date in the future.

**Comment by Ghost707** [comment]
Hey,

Libssl was apparently completely messed up. Openssl or any other related
commands stopped working.Even after i removed the library completely and
reinstalled using the default arch repos.

I did a fresh install and everything works fine now.

Thanks a ton,
Ghost707 (Adi)
