### ISSUE TITLE
device icon randomly disappears from menu

### ISSUE THREAD

**Issue by sombriks** [GSConnect/gnome-shell-extension-gsconnect#1637]
### Describe the bug

device icon randomly disappears from menu

### Expected behavior

just stare at the icon, it will disappear at some moment

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

44.1

### Linux distribution/release

Fedora 38

### Paired device(s)

Samsung galaxy S21+ SM-G996B

### KDE Connect app version

1.24.5

### Support log

```plain text
jun 09 14:21:16 lucien gnome-shell[2467]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
jun 09 14:21:35 lucien gnome-shell[2467]: g_closure_unref: assertion 'closure->ref_count > 0' failed
jun 09 14:21:35 lucien gnome-shell[2467]: g_closure_unref: assertion 'closure->ref_count > 0' failed
jun 09 14:21:38 lucien gjs[233571]: JS ERROR: SM-G996B: Gio.IOErrorEnum: Conexão falhou
                                    _handleMount/</<@/home/sombriks/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:257:38
                                    @/home/sombriks/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:731:17
```

**Comment by ferdnyc** [comment]
@sombriks 

It looks like you probably have the "Filesystem expose" plugin enabled on the Android side, but don't have a directory chosen and permissions granted to share the contents.

In situations like that, having the "SFTP" plugin enabled on the Linux side, and either attempting to Mount the remote directory manually, _or_ having "SFTP Automount" enabled, will cause those errors when GSConnect attempts to make an SFTP connection and fails.

Normally I'd advise you to grant the necessary file-sharing permissions on the Android side. But attempting to do that myself, I can't seem to find any way to **_actually do that_** with the newest version of the KDEConnect app. Normally there would be a message in the paired device's interface pane, in the Android app, but that's just not coming up for me.

I'm not sure what's going on with that, or if I'm missing something... but as a workaround for the moment, on the Linux side you can open GSConnect's **Mobile Settings** dialog, select your phone from the list of devices, and then:

1. Disable **Advanced > Experimental > SFTP Automount**, if it's enabled.
2. If that doesn't work, or it was already disabled, just switch off **Advanced > Plugins > SFTP** completely.

You won't be able to browse the files on your phone, but you can't do that anyway right now. And hopefully disabling SFTP will stop GSConnect from crashing every time it attempts, and fails, to connect.

**Comment by sombriks** [comment]
Hello @ferdnyc !

yes disabling sftp made the device icon become stable, it still disappears if it pass too much time inactive but it's way better than before, thanks!
