### ISSUE TITLE
Gsconnect 55 incompatible with Ubunut 22.04 (Gnome 42.5)

### ISSUE THREAD

**Issue by sulliwane** [GSConnect/gnome-shell-extension-gsconnect#1642]
### Describe the bug

I manually installed version 55:
```shell
gnome-extensions install --force gsconnect@andyholmes.github.io
lsb_release --release # Release: 22.04
gnome-shell --version # GNOME Shell 42.5
```
And after logging out/in (wayland) the extension is not loaded and I can see this error message:
![Screenshot from 2023-06-15 10-43-08](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/1733686/8f2c54bd-9762-40fb-85bf-1412988c7cc3)

Also tried with version 54, same issue. I'm now back to version 50.

### GSConnect version

55

### Installed from

GitHub releases (zip file)

### GNOME Shell version

42.5

### Linux distribution/release

Ubuntu 22.04

**Comment by sulliwane** [comment]
similar issue here: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1466

**Comment by daniellandau** [comment]
You shouldn't blindly use a version with the largest number. The correct version of GNOME Shell 42 is v50. Installing from https://extensions.gnome.org gives you automatically the correct version. On the GitHub releases page the latest release is generally for the latest released GNOME Shell version, which is usually not the same as the one in the latest Ubuntu LTS. Sometimes, such as with v53 it is stated explicitly in the release notes which version it's for, which in the case of v53 was a backport to an earlier shell.
