### ISSUE TITLE
Not work correct on Ubuntu Wayland

### ISSUE THREAD

**Issue by Slavomir9** [GSConnect/gnome-shell-extension-gsconnect#1644]
### Describe the bug

Hello,
On Ubuntu default setting (probably Wayland) not work correct Kde Connect. Main features not work correct.
KDE Connect work correct only on Ubuntu Xorg.
Can you add support for Ubuntu Wayland?
Or can you add notify, that work correct only on Ubuntu Xorg?

I use actual version of Ubuntu 23.

### GSConnect version

version 55, installed from ubuntu snap store

### GNOME Shell version

44.1

### Linux distribution/release

Ubuntu 23.04 lunar

![xorg vs wayland](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/73296504/d51d3ff7-9be5-4a76-9cf2-b03d841c5300)

![20230618_174946](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/73296504/4218f55c-65fd-43c9-b897-debc80e20e5b)

**Comment by daniellandau** [comment]
We don't support the snap store. Try installing through the extensions website at https://extensions.gnome.org. It should work correctly on Wayland too.

**Comment by Slavomir9** [comment]
I am sorry. GS Connect work perfect, but KDE Connect not work on Wayland. I confused KDE Connect and GSConnect
