### ISSUE TITLE
Add Remote File System Browser

### ISSUE THREAD

**Issue by Slavomir9** [GSConnect/gnome-shell-extension-gsconnect#1648]
### Describe your request

Hi developers
Can you please this feature to the GSConnect?
https://userbase.kde.org/KDEConnect#Remote_File_System_Browser

On KDE connect with Dolphin it work on me computer and Ubuntu very good

### GSConnect version

actual

### Installed from

GNOME Extensions website

### Linux distribution/release

Ubuntu 23.04 lunar

**Comment by andyholmes** [comment]
This feature is supported by GSConnect. See:

- https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features#sftp
- https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features#files-extension
