### ISSUE TITLE
Login/Logout loop

### ISSUE THREAD

**Issue by leoheck** [GSConnect/gnome-shell-extension-gsconnect#1652]
### Describe the bug

I am experiencing a login loop, where I log in and then I am logged out after 1 or 2 seconds. I believe this extension is causing that. 

Android has the KDE Connect 1.26.3

The laptop has Ubuntu 23.04, and the GSConnect is 55.
I am also using Gnome 44.2 and X11.

Additional extensions I have enabled.
```
➜ ls  ~/.local/share/gnome-shell/extensions/ -1 | nl
     1	appindicatorsupport@rgcjonas.gmail.com
     2	BingWallpaper@ineffable-gmail.com
     3	gnome-shell-screenshot@ttll.de
     4	gnome-shell-trash-extension
     5	gsconnect@andyholmes.github.io
     6	just-perfection-desktop@just-perfection
     7	quick-settings-tweaks@qwreey
     8	rounded-window-corners@yilozt
     9	topiconsfix@aleskva@devnullmail.com
    10 trayIconsReloaded@selfmade.pl
    11 user-theme@gnome-shell-extensions.gcampax.github.com
    12 waylandorx11@injcristianrojas.github.com
    13 world_clock_lite@ailin.nemui
```

### Steps to reproduce

Enable GSConnect
Lock the screen
Log in back
Wait for 1s or 2s until the system logs you out...

Sometimes doing this for a couple of times, like 4 or 5, it stops. But there are other times when this takes forever.

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

44.2

### Linux distribution/release

Ubuntu 23.04

### Paired device(s)

Pixel 7 Pro

### KDE Connect app version

1.26.3

### Plugin(s)

It maybe the case, I tried to turn on/off a couple of plugins for some time until I could track the issue to GSConnect (see the screenshot below)

### Screenshots

All my plugins are listed here for reference.
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/1277920/8b4d4894-2459-4ea7-bcea-9ddf3db9624c)
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/1277920/6059bd04-bbef-4dd4-99e0-94f63555f048)

**Comment by andyholmes** [comment]
Was this confirmed as a bug in GSConnect? Are there are any logs indicating it might be?
