### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [GSConnect/gnome-shell-extension-gsconnect#1665]
### Describe your request

There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

### GSConnect version

N/A

### Installed from

OS package manager

**Comment by guilhem** [comment]
Extension currently fails with:
```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///home/guilhem/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:10:19
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by istvan-derda** [comment]
Heya, I'd be up for doing this, just gotta find a free afternoon. I think I can be done before the official gnome 45 release. :)

**Comment by Scotty-Trees** [comment]
https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

There's also this helpful link for potential extension devs/contributors. If anyone gets stuck or needs a little help, the Gnome devs on their Discource and Matrix channels are around to offer whatever help they may be able to provide. All details are in the link above. Good luck and can't wait for 45 to be released.

**Comment by derkrasseleo** [comment]
Wondering the same thing..

**Comment by PussInScreen** [comment]
If anyone's waiting on Gnome 45 and are okay with using "test" software the latest nightly build works well on Gnome 45 so far; [Here :)](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build)

**Comment by unicornsandcandies** [comment]
> If anyone's waiting on Gnome 45 and are okay with using "test" software the latest nightly build works well on Gnome 45 so far; [Here :)](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build)

when can we expect the stable version?

**Comment by Muspellheimr** [comment]
i am on endevouros gnome 45.1 and my devices cant find each other

**Comment by derkrasseleo** [comment]
Can't confirm on EndeavourOS with gnome 45.1 and iOS as a client (Maybe try removing the certificates in the app)

**Comment by Muspellheimr** [comment]
@derkrasseleo Hey, i am new to Linux, and i only used GSConnect once before on Fedora and it just worked.
I must confess that i don't really know what you mean. (i guess i have to life with it not working)

**Comment by derkrasseleo** [comment]
> i am on endevouros gnome 45.1 and my devices cant find each other



> @derkrasseleo Hey, i am new to Linux, and i only used GSConnect once before on Fedora and it just worked. I must confess that i don't really know what you mean. (i guess i have to life with it not working)
> 
> btw. i try to connect EndeavourOS and Android

Can't really help you with android but somewhere in the apps settings under "Advanced Settings" (at least her on iOS) there are two options `Erase saved devices cache` and `Delete host certificates`, which makes the app "forget" all connected devices. Solved connection issues many times for me.

**Comment by PussInScreen** [comment]
> > If anyone's waiting on Gnome 45 and are okay with using "test" software the latest nightly build works well on Gnome 45 so far; [Here :)](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build)
> 
> when can we expect the stable version?

No idea, I'm not involved in the development of the project. I was just letting people know the nightly builds are a thing and from my own use, work on Gnome 45.

**Comment by NyllRE** [comment]
> If anyone's waiting on Gnome 45 and are okay with using "test" software the latest nightly build works well on Gnome 45 so far; [Here :)](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build)

Just tried it, doesn't work with me unfortunately
