### ISSUE TITLE
Delete obsolete .pot German translation on Crowdin

### ISSUE THREAD

**Issue by Amr-Ibra** [GSConnect/gnome-shell-extension-gsconnect#1666]
### Describe your request

I was improving the German translation on Crowdin: https://crowdin.com/project/gsconnect/de

I clicked `Translate All`, then later realized that I was editing the translation under `master` which I think is obsolete and not used any more, even though it receives updates from time to time.

### Proposed solution

Please delete the obsolete .pot translations on Crowdin so that time and effort are not wasted.

### GSConnect version

main

### Installed from

GNOME Extensions website

**Comment by andyholmes** [comment]
Thanks for reporting, I've deleted the `master` branch from Crowdin.
