### ISSUE TITLE
Regression from photo plugin removal

### ISSUE THREAD

**Issue by byquanton** [GSConnect/gnome-shell-extension-gsconnect#1686]
### Describe the bug

When upgrading GSConnect to the latest version (with the photos plugin removal) an exception is thrown when GSConnect tries to load the "supported-plugins" for a device. This can be manually fixed by removing the photos plugin from all devices with dconf.

### Steps to reproduce

1. Pair a device on an older version of GSConnect and enable the photo plugin
2. Upgrade GSConnect

### Expected behavior

Not trying to load no longer existing plugins from the device settings

### GSConnect version

55

### Installed from

GitHub releases (zip file)

### GNOME Shell version

45

### Support log

```plain text
No JS module 'photo' found in search path

_loadPlugin@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:1009:17
_loadPlugins@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:1041:28
async*_init@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:130:18
Device@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:84:4
_loadDevices@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:273:28
start@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:461:14
vfunc_startup@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:266:22
vfunc_handle_local_options@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:663:18
@/home/me/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:723:17
```

**Comment by daniellandau** [comment]
Good catch, thank you! This was happening a while back when people were installing a backport bugfix release on top of a newer release so they got a version with some plugin missing. This definitely needs to be fixed before releasing a version with the current main

**Comment by andyholmes** [comment]
Testing the ZIP here would be appreciated :)

https://github.com/GSConnect/gnome-shell-extension-gsconnect/actions/runs/6386504052

**Comment by andyholmes** [comment]
> Seems to fix it.

Thanks for testing :)

> Maybe also remove it from the outgoing capabilities.

That's up to the remote device to decide, so it would just keep getting replaced anyways.
