### ISSUE TITLE
Phone and computer do not recognize each other

### ISSUE THREAD

**Issue by ArthurValada** [GSConnect/gnome-shell-extension-gsconnect#1689]
### Describe the bug

Hi. I've been facing this problem for a while now. I access the issues to find something similar, if there is, please forgive me for the inconvenience, but none of my devices recognize each other. I'm using Gnome 43.1. I've already tried uninstalling it through extensions.gnome.org and through the zip with the version compatible with my DE. Despite this, nothing has worked. I've looked at the log files, but nothing significant from what I've been able to find. I tried adding each one through the other using IP, but nothing happens. The computer does not recognize the phone and the phone does not recognize the computer. I've tried similar issue solutions, but without any progress.
Any ideas on how to resolve it? Thank you very much in advance.

### Steps to reproduce

1. Open GSConnect

### Expected behavior

List of the device on LAN that is running KDE Connect

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43.1

### Linux distribution/release

Vanilla OS Kinetic

### Paired device(s)

No one

### KDE Connect app version

1.29.0

### Support log

```plain text
GSConnect: 54 (user)
GJS:       17400
Session:   x11
OS:        VanillaOS 22.10 all
--------------------------------------------------------------------------------
out 10 16:36:00 portmaster_notifier.desktop[632630]: 231010 16:36:00.173 ent/client:078 ▶ INFO 885 client: reconnecting...
out 10 16:36:01 portmaster_notifier.desktop[632630]: 231010 16:36:01.173 ent/client:078 ▶ INFO 886 client: reconnecting...
out 10 16:36:01 CRON[636312]: pam_unix(cron:session): session opened for user arthur(uid=1000) by (uid=0)
out 10 16:36:01 CRON[636313]: (arthur) CMD (/home/arthur/.local/bin/organize run)
out 10 16:36:02 postfix/pickup[635631]: 23D7510A9AA: uid=1000 from=<arthur>
out 10 16:36:02 postfix/cleanup[635705]: 23D7510A9AA: message-id=<20231010193602.23D7510A9AA@vanilla.localdomain>
out 10 16:36:02 CRON[636312]: pam_unix(cron:session): session closed for user arthur
out 10 16:36:02 postfix/qmgr[1987]: 23D7510A9AA: from=<arthur@vanilla.localdomain>, size=5503, nrcpt=1 (queue active)
out 10 16:36:02 postfix/local[635707]: 23D7510A9AA: to=<arthur@vanilla.localdomain>, orig_to=<arthur>, relay=local, delay=0.01, delays=0.01/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
out 10 16:36:02 postfix/qmgr[1987]: 23D7510A9AA: removed
out 10 16:36:02 portmaster_notifier.desktop[632630]: 231010 16:36:02.174 ent/client:078 ▶ INFO 887 client: reconnecting...
out 10 16:36:03 portmaster_notifier.desktop[632630]: 231010 16:36:03.175 ent/client:078 ▶ INFO 888 client: reconnecting...
out 10 16:36:04 portmaster_notifier.desktop[632630]: 231010 16:36:04.176 ent/client:078 ▶ INFO 889 client: reconnecting...
out 10 16:36:05 portmaster_notifier.desktop[632630]: 231010 16:36:05.176 ent/client:078 ▶ INFO 890 client: reconnecting...
out 10 16:36:06 portmaster_notifier.desktop[632630]: 231010 16:36:06.177 ent/client:078 ▶ INFO 891 client: reconnecting...
out 10 16:36:07 gnome-shell[632340]: Ignoring length property that isn't a number at line 21, col 17
out 10 16:36:07 gnome-shell[632340]: Ignoring length property that isn't a number at line 22, col 18
out 10 16:36:07 portmaster_notifier.desktop[632630]: 231010 16:36:07.177 ent/client:078 ▶ INFO 892 client: reconnecting...
out 10 16:36:08 portmaster_notifier.desktop[632630]: 231010 16:36:08.178 ent/client:078 ▶ INFO 893 client: reconnecting...
out 10 16:36:09 portmaster_notifier.desktop[632630]: 231010 16:36:09.179 ent/client:078 ▶ INFO 894 client: reconnecting...
out 10 16:36:10 portmaster_notifier.desktop[632630]: 231010 16:36:10.180 ent/client:078 ▶ INFO 895 client: reconnecting...
out 10 16:36:10 org.gnome.Shell.Extensions.GSConnect[634343]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
out 10 16:36:11 portmaster_notifier.desktop[632630]: 231010 16:36:11.181 ent/client:078 ▶ INFO 896 client: reconnecting...
```

### Screenshots

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/101188458/e2059cfd-214f-46ca-a856-74db9c5c8078)

### Notes

Despite using Portmaster, even turning it off and disabling the firewall, the problem persists.

**Comment by andyholmes** [comment]
Sorry, I don't know how Portmaster works, but it's required to open ports 1716-1764 for TCP & UDP. You should also check that your router supports UDP broadcasts and so on.

It's difficult to provider personalized support for everyone's network and firewall configuration, so you may have to check with those relevant parties.

**Comment by ArthurValada** [comment]
This may sound a little sarcastic, but I promise it's not. I'm really grateful for the help. You identified the problem as being the portmaster, as nothing changed on my LAN network to make me believe the problem was with the router or access point, and, thanks to that, after a bit of research, I discovered how to allow broadcasting via TCP and UDP on ports 1714 to 1764 using the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints) section of the Portmaster.

I found a [similar Issue](https://github.com/safing/portmaster/issues/412) on portmaster's github. Thank you very much. :)

**Comment by andyholmes** [comment]
Ah well that's good :)

Feel free to add a little section to the Wiki if you think it will help others: https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#firewall-blocking-port

**Comment by andyholmes** [comment]
Actually, I just moved it here: https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#firewall-configuration

Feel free to add a Portmaster section.

**Comment by EpycZen** [comment]
> This may sound a little sarcastic, but I promise it's not. I'm really grateful for the help. You identified the problem as being the portmaster, as nothing changed on my LAN network to make me believe the problem was with the router or access point, and, thanks to that, after a bit of research, I discovered how to allow broadcasting via TCP and UDP on ports 1714 to 1764 using the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints) section of the Portmaster.
> 
> I found a [similar Issue](https://github.com/safing/portmaster/issues/412) on portmaster's github. Thank you very much. :)

Hey could you show me the rules you set? it's still not working for me after setting the ones in the pic attached

<img width="1400" height="965" alt="Image" src="https://github.com/user-attachments/assets/390660c5-600f-4273-acff-e8421c3c757e" />
