### ISSUE TITLE
GSConnect extension support with gnome 45

### ISSUE THREAD

**Issue by sarowarhosen03** [GSConnect/gnome-shell-extension-gsconnect#1690]
### Describe your request

Tomorrow 12 October Ubuntu will release with gnome 45. I like to explore new Ubuntu with gnome 45. But gsconnect missing on gnome 45. Please release gsconnect with gnome 45 support 

### GSConnect version

Latest 

### Installed from

GNOME Extensions website

### GNOME Shell version

45

### Linux distribution/release

Ubuntu 23.10

### Additional context

Gnome 45 support

**Comment by skewty** [comment]
duplicate of #1680
