### ISSUE TITLE
Seems highly insecure

### ISSUE THREAD

**Issue by ittayd** [GSConnect/gnome-shell-extension-gsconnect#1692]
### Describe your request

I followed the installation instructions on two desktops and could pair the two without any notification or pn request. So it seems anyone on the same network can do the same and see my clipboard data etc. Or camera etc. 

### Proposed solution

Pairing should ask for the user to insert a key they got from the other device and on the other desktop request for the user password before showing the key

### GSConnect version

latest

### Installed from

GNOME Extensions website

**Comment by ferdnyc** [comment]
@ittayd 

How do you figure? You can add paired devices to GSConnect via IP address, it's true, but they get added _Unpaired_. When you go to configure the device, a banner shows allowing you to send a pair request:

![Screenshot from 2023-10-20 08-21-55](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/538020/b6d1794c-dd72-4ffa-9fea-164a0c545b69)

...which then results in a notification on the other end:

![Screenshot from 2023-10-20 08-19-12](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/538020/be4ec94d-c4e2-4aed-aa14-8ee7e2b867d0)

(It even defaults to "Reject"!)

If you had _previously_ paired the two devices, deleted one from the other's list, and then re-connected them, you might be able to reestablish the pairing without a notification. But the two devices would have to have already exchanged encryption keys.

**Comment by ferdnyc** [comment]
(Even if you could silently add a paired device completely unattended from one end of the link, everything (except a pairing request) that any device sends out over the kdeconnect protocol is encrypted. Without having received the paired device's encryption key, your end wouldn't be able to read any of the data.)

**Comment by andyholmes** [comment]
> I followed the installation instructions on two desktops and could pair the two without any notification or pn request.

Can you explain how you did this? Also what pn request do you mean?

> ...and on the other desktop request for the user password before showing the key

Not sure I understand this part? The confirmation key is just a hash of the local & remote certificates, to help confirm no MITM attack has occurred.

**Comment by eode** [comment]
From an outsider's view, this request could reasonably be closed.  They haven't responded, and your responses have been entirely reasonable.

**Comment by ferdnyc** [comment]
Indeed. I suppose neither of us tagged @ittayd in our responses, which might've been more attention-grabbing. So, doing that now, with a note to say that we'll close this in 7 days if we haven't gotten any response to the followup questions posted here.

Thanks for the poke, @eode.

**Comment by andyholmes** [comment]
Closing due to lack of information from reporter.
