### ISSUE TITLE
not compatible with gnome 45

### ISSUE THREAD

**Issue by elmhadji** [GSConnect/gnome-shell-extension-gsconnect#1697]
### Describe the bug

it was working fin just after I upgrade my OS into gnome 45 it stopped working. 

### Steps to reproduce

1. upgrade your gnome to gnome 45 (or use directly gnome 45)

### Expected behavior

not working

### GSConnect version

1.29.0

### Installed from

GNOME Extensions website

### GNOME Shell version

45

### Linux distribution/release

arch

### Paired device(s)

poco x3

### KDE Connect app version

1.29.0

### Notes

please make it compatible with gnome 45

**Comment by sarowarhosen03** [comment]
im aslo waiting for the next release . gsconnect dev team should harry up for the next release

**Comment by elmhadji** [comment]
> im aslo waiting for the next release . gsconnect dev team should harry up for the next release

we all do the problem that when i get used to it broke Lamo. (when upgrade to gnome45)

**Comment by azmeuk** [comment]
Duplicate of #1665

**Comment by sarowarhosen03** [comment]
> Duplicate of #1665

So what? It's still not resolve. Duplicate is important to remember you that Ubuntu with gnome,  45 has been released

**Comment by andyholmes** [comment]
Please don't intentionally open duplicate issues.

**Comment by elmhadji** [comment]
@andyholmes can you please tell me how close this issus ?

**Comment by sarowarhosen03** [comment]
> @andyholmes can you please tell me how close this issus ?

Already closed by admin
