### ISSUE TITLE
Question about daemon.js usage

### ISSUE THREAD

**Issue by evert** [GSConnect/gnome-shell-extension-gsconnect#1698]
### Describe the bug

I tested the daemon script by running: `./deamon.js --ring -d [id]` which works!

However, `./deamon.js --notification=hello -d [id]` does not. Both commands do emit an error.

```
(gjs:625179): GLib-GIO-CRITICAL **: 00:16:19.046: GFileInfo created without standard::symlink-target

(gjs:625179): GLib-GIO-CRITICAL **: 00:16:19.046: file ../gio/gfileinfo.c: line 2062 (g_file_info_get_symlink_target): should not be reached
```

### GSConnect version

nightly

### Installed from

GitHub releases (zip file)

### GNOME Shell version

45

### Linux distribution/release

Fedora 39

### Paired device(s)

Pixel 7

### KDE Connect app version

1.29.0

**Comment by andyholmes** [comment]
Thanks for reporting, #1701 should fix the critical warnings.

As for the `--notification` CLI option, just be sure the remote device is set to show notifications. In the Android app the *Receive notifications* plugin is off by default, which catches people off guard.
