### ISSUE TITLE
GSConnect settings does not opens

### ISSUE THREAD

**Issue by xl-soft** [GSConnect/gnome-shell-extension-gsconnect#1704]
### Describe the bug

GS Connect does not starting, and when i attempting to open settings, it immideatly crashes (from topbar menu it doesn't even think to open up), and KDE Connect client not seeing pc

### Steps to reproduce

1. Install latest version of GS Connect
2. So... that`s it

### Expected behavior

GS Connect at least starts

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

45.1

### Linux distribution/release

Arch

### Paired device(s)

Redmi Note 12

### KDE Connect app version

1.29.0

**Comment by andyholmes** [comment]
Please provide any logs you can when opening issues with unknown causes. If you can still reproduce this, please re-open with system logs showing the time period GSConnect fails to start.

Thanks!
