### ISSUE TITLE
first Chinese character does not input with remote input

### ISSUE THREAD

**Issue by howdev** [GSConnect/gnome-shell-extension-gsconnect#1716]
### Describe the bug

when the gsconnect service is first start, either on the phone or desktop, using the Chinese language the first character is not sent through from the phone, from thereon, all the characters will input. I have repeated this process with same behaviour. 
Whenever the service is first started, first Chinese character does not input

### Steps to reproduce

1. On the Android device, stop the background service, if running.
2. start the kdeconnect app
3. also enable the desktop gsconnect
4. open a text editor, or terminal
5. go to remote input
6. activate the keyboard
7. type a Chinese character

### Expected behavior

all character should sent through, no matter the service is first start or already running

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45

### Linux distribution/release

Ubuntu 23.10

### Paired device(s)

Galaxy A13

### KDE Connect app version

1.29.0

**Comment by andyholmes** [comment]
Ah, sorry. This is expected behaviour for GSConnect.

As a result of user-feedback early in implementation, GSConnect will not request permission for remote control until requested, which usually means the first event is dropped.

**Comment by howdev** [comment]
@andyholmes Thank you for telling me of the GSConnect problem. Therefore, I am using the kdeconnect app instead, and it works perfectly.
