### ISSUE TITLE
Duplicate context menu in nautilus

### ISSUE THREAD

**Issue by pakosaan** [GSConnect/gnome-shell-extension-gsconnect#1723]
### Describe the bug

Duplicate menu in the context menu of nautilue:
Two Send to mobile devices in nautilus
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/35842120/6021384b-d2c7-4d9b-9e71-4d9f9290ec28)

### Steps to reproduce

1. Go to the nautilus
2. Right click on any file you want to send to Android device
3. And you see the duplicate entries in context menu

### Expected behavior

I only want single entries in context menu for gsconnect-nautilus

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45.2

### Linux distribution/release

Fedora 39

### Paired device(s)

Samsung J6

### KDE Connect app version

1.29.0

### Screenshots

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/35842120/36374d7c-adf3-4237-9ad7-d7f7a002819f)

**Comment by andyholmes** [comment]
This is usually caused by installing the Nautilus extension with GSConnect, and as a system package.

Can you check that hasn't happened?

**Comment by lousuan** [comment]
> This is usually caused by installing the Nautilus extension with GSConnect, and as a system package.
> 
> Can you check that hasn't happened?

Why dont I have this menu in nautilus...

**Comment by pakosaan** [comment]
![image](https://github.com/user-attachments/assets/ed4e081c-06b4-407f-b958-ee03a83dea2d)
so I installed nautilus-gsconnecct via dnf . and the gsconnect extension as  gnome-extensions. That's it

**Comment by pakosaan** [comment]
Oh now i got it. i removed the gsconnect extension installed via extension manager cuz nautilus-python has gsconnect-extension as a dependencies by default. so i removed it but still the gsconnect didn't show up so i had to logout and login and now its fixed. it was just easy to fix this but i guess i am noob afterall lol. Thanks @andyholmes  for the help.
