### ISSUE TITLE
Connecting phone and PC with port forwarding

### ISSUE THREAD

**Issue by road2react** [GSConnect/gnome-shell-extension-gsconnect#1726]
### Describe your request

I can't seem to figure out a way to connect my phone to my PC using port forwarding. I am able to port forward ports 1714-1764 with both TCP and UDP directly to my computer, but I can't seem to get the Android KDE Connect client to connect. Based on my inspection, it looks like the Android client first sends a UDP broadcast packet, which then causes GSConnect to open a TCP connection to the Android client. 

### Proposed solution

Ideally it would be possible for the TCP connection to be opened the other way (phone to computer); without a broadcast UDP packet.

### Alternatives

I could set up a VPN, but that would make it more difficult; and most VPN clients are mutually exclusive: only one can be running at a time.

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45.2

### Linux distribution/release

Arch Linux

**Comment by andyholmes** [comment]
The changes required to address this will have to be discussed with the upstream team, who can be contacted via https://kdeconnect.kde.org/get-involved.html
