### ISSUE TITLE
daemon using 100% CPU, can't turn off

### ISSUE THREAD

**Issue by cfe316** [GSConnect/gnome-shell-extension-gsconnect#1755]
### Describe the bug

I'm running Pop!_OS 22.04. I have GSConnect (version: 50, shell-version: 42) installed as an Extension. When I started up my laptop and logged on, I found via `htop` that `gjs /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js` was using 100% of one CPU. I also was unable to use the `Turn Off` button (under `Mobile Devices` in a side menu). 

After turning GSConnect off and on again via the Extensions menu, it uses only negligible CPU and can be turned on and off normally.

### Steps to reproduce

1. Have GSConnect installed (version: 50, shell-version: 42), via Pop Shop.
2. Start up computer and log on as a user to the graphical desktop.
3. See that it's using 100% CPU.

### GSConnect version

50

### Installed from

OS package manager

### GNOME Shell version

42

### Linux distribution/release

Pop!_OS 22.04

### Paired device(s)

Pixel 6

### KDE Connect app version

n/a

### Plugin(s)

?

**Comment by kernelb00t** [comment]
Does the issue happens everytime you reboot your computer? Please check in your logs : `journalctl -b 0` if GSConnect says anything. (This command gets the current logs of the system from the current boot. For the last boot, use `journalctl -b -1`, etc...)

**Comment by cfe316** [comment]
I was able to fix the issue, I think it was by reinstalling GSConnect - my apologies for not taking good notes. 
It behaves normally now! Sorry, you can close the issue; I can reopen if it happens again.

Since it's working I don't see anything odd with journalctl.
