### ISSUE TITLE
Can't connect my IOS device to GSConnect

### ISSUE THREAD

**Issue by AlessioSarica** [GSConnect/gnome-shell-extension-gsconnect#1761]
### Describe the bug

My Distro is Fedora 39 and i try to install GSConnect and give me an error "openssl" then i installed it but on my IOS device i don't view my computer

### Steps to reproduce

Go to KDEConnect
Try to pair a new device but don't view never

### GSConnect version

56

### Installed from

Extension Manager

### GNOME Shell version

45

### Linux distribution/release

Fedora 39

### Paired device(s)

iPhone 12 Pro

### KDE Connect app version

0.3.0

**Comment by ferdnyc** [comment]
@AlessioSarica 

Sorry for the delay, it sounds like you need [firewalld configs](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#firewalld) to allow incoming connections.

> ### GUI:
> Open Firewall Configuration `(firewall-config)`. In **Zones ➔ Services**, check the **kdeconnect** service. Turn in on if it's not.
> 
> Make sure you choose the "**Permanent**" Configuration: option in the drop-down menu at the top, otherwise rebooting will discard your settings changes.

(Note: The GUI tool is actually just labeled "Firewall", in the app list on Fedora. If you don't have it on your system, install the `firewall-config` package.)

> ### CLI:
> 
> ```bash
> sudo firewall-cmd --permanent --zone=public --add-service=kdeconnect 
> sudo firewall-cmd --reload
> ```
> 
> In the above command `--zone=public`, replace `public` with your current zone.

If you're using the GUI, you'd want to see something like this. (I've circled the important parts; the zone selected by default when you launch the tool _should_ be the correct one, so you shouldn't have to worry about that.)

![Screenshot from 2024-03-29 21-55-56](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/538020/aec6f3f2-a0e6-46e1-bdee-725542ff0411)

Let us know if you're still having problems after opening up the firewall to receive `kdeconnect` connections.

**Comment by AlessioSarica** [comment]
Thank you
