### ISSUE TITLE
Please Support Gnome 46.*

### ISSUE THREAD

**Issue by NickBelhomme** [GSConnect/gnome-shell-extension-gsconnect#1768]
### Describe your request

Please support Gnome 46

### GSConnect version

probably latest, cannot launch version (disabled / outdated)

### Installed from

GNOME Extensions website

### GNOME Shell version

GNOME 46.0

### Linux distribution/release

openSUSE Tumbleweed x86_64 

### Additional context

cannot upgrade gsconnect through extension website

![2024-03-27_10-06](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/312003/c88074e7-adc1-4b56-b8d4-085b5655cff3)

**Comment by harshkushwaah** [comment]
i recently updated gnome shell and yes GSConnect doesn't support the new version. Although I haven't tried to rebuild it from the source, have you?

**Comment by NickBelhomme** [comment]
no I always use the extension manager website as posted in the screenshot. So no manual build.

**Comment by TrazhCant** [comment]
I followed the instructions for installing the nightly build and it worked.

**Comment by NickBelhomme** [comment]
ok thx, that indeed works. awesome

**Comment by harshkushwaah** [comment]
(I'm a Noob) I tried to install it, but I couldn't, I have gnome-extentions and gnome-extention-manager installed.
[123@123 Downloads]$ gnome-extentions install --force gsconnect@andyholmes.github.io.zip 
bash: gnome-extentions: command not found

**Comment by NickBelhomme** [comment]
use a search engine to search on "gnome-extentions: command not found + [your distrobution here]"

for example "gnome-extentions: command not found opensuse"

**Comment by wolf-yuan-6115** [comment]
> (I'm a Noob) I tried to install it, but I couldn't, I have gnome-extentions and gnome-extention-manager installed. [123@123 Downloads]$ gnome-extentions install --force [gsconnect@andyholmes.github.io.zip](mailto:gsconnect@andyholmes.github.io.zip) bash: gnome-extentions: command not found

You can also download `.zip` file and install it manually: https://www.debugpoint.com/manual-installation-gnome-extension/

**Comment by harshkushwaah** [comment]
it worked guys thanks, nightly build worked, I can peacefully uninstall Valent now.
