### ISSUE TITLE
Notifications synced from the mobile device isn't received on GNOME Shell

### ISSUE THREAD

**Issue by stel-bl** [GSConnect/gnome-shell-extension-gsconnect#1770]
### Describe the bug

The GNOME 46 update cannot sync the notifications properly - The notifications are sent from the GNOME PC to the mobile device, but the mobile device cannot post notifications on the GNOME PC.

### Steps to reproduce

1. Install GSConnect from the Git repository.
2. Pair the mobile device with GSConnect using KDE Connect app.
3. Post a test notification on both devices.
4. Observe the cross-device notifications.

### Expected behavior

The notifications are synced from/to the GNOME PC.

### GSConnect version

56

### Installed from

other source

### GNOME Shell version

46

### Linux distribution/release

Arch

### Paired device(s)

WayDroid x86_64 Device, Redmi Note 10S

### KDE Connect app version

1.29.0

### Plugin(s)

N/A

### Support log

```
Mar 27 14:21:54 gnome-shell[8453]: JS ERROR: TypeError: notificationParams is undefined
                                   addNotification@file:///home/stella/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:232:13
                                   AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:665:16
                                   _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
                                   _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
                                   @resource:///org/gnome/shell/ui/init.js:21:20
```

### Screenshots

N/A

### Notes

N/A

**Comment by Skythrew** [comment]
As I was saying in #1764, the issue with GNOME 46 support for GSConnect is only the notification part. The recently merged pull request #1767 was not complete at all. We need to rewrite the whole notification part, not simply by changing `MessageTray.NotificationBanner` to `Calendar.NotificationMessage`.

**Comment by stel-bl** [comment]
> As I was saying in #1764, the issue with GNOME 46 support for GSConnect is only the notification part. The recently merged pull request #1767 was not complete at all. We need to rewrite the whole notification part, not simply by changing `MessageTray.NotificationBanner` to `Calendar.NotificationMessage`.

I see. Thanks for letting me know. The only option that's left for me is to wait and keep testing then.

**Comment by Skythrew** [comment]
You're welcome :+1: I'm currently trying to rewrite the implementation of the notification part. It's a lot of debugging as GNOME didn't really make docs for this change in the API but I'm on the right track :smile:

**Comment by stel-bl** [comment]
Good luck! You got this!

And if you ever need someone else to test it out for you, I'm always here to help!
