### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by kzhe2059** [GSConnect/gnome-shell-extension-gsconnect#1772]
### Describe your request

I'm always frustrated when I go to use GSConnect and realise I can't because I'm on GNOME 46

### Proposed solution

It would be great if I could get support

### Alternatives

None

### GSConnect version

N/A

### Installed from

other source

### GNOME Shell version

46

### Linux distribution/release

Endeavour OS

**Comment by taukakao** [comment]
Please check closed issues in the future. 
This is already implemented, there just hasn't been a new release yet. 

Duplicate of #1768 and #1764
