### ISSUE TITLE
Incoming call notification is staying always visible and notification buttons not working

### ISSUE THREAD

**Issue by malisipi** [GSConnect/gnome-shell-extension-gsconnect#1775]
### Describe the bug

After getting a call notification, the notification will always stay there. (Screenshots is below)

The only way to hide the notification is logging out from Gnome session.

### Steps to reproduce

1. Connect your KDEConnect application in Android and GSConnect extension.
2. Allow KDEConnect to handling incoming calls
3. Call the phone that connected via KDEConnect.
4. GSConnect will show the incoming call notification.
5. And there are no way to hide. Clicking buttons (including (X) and (^) buttons that placed top right of notification), answering the call, ignoring the call is not a solution.

### Expected behavior

It hides the incoming call notifications.

### GSConnect version

56 (Installed from Nightly Builds from Github)

### Installed from

GitHub releases (zip file)

### GNOME Shell version

46

### Linux distribution/release

Arch Linux

### Paired device(s)

Samsung A11

### KDE Connect app version

1.29.0

### Plugin(s)

Call notifier

### Screenshots

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/87281783/1411cddf-22cd-402b-adae-257cadda8624)
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/87281783/3a588249-6d90-4710-8506-1b6db7a68758)

**Comment by daniellandau** [comment]
I noticed the same thing while preparing a release. There's a stacktrace in the logs associated, but I'm not at my computer right now. This needs to be fixed before release (and checked if it's Arch specific, as that's what I was using too to test)

**Comment by daniellandau** [comment]
The notification I ran into this with is the pairing request notification. I guess both have in common that they are supposed to be persistent unless dismissed, so maybe there's a bug there.

**Comment by daniellandau** [comment]
We can't dismiss `Gio.NotificationPriority.URGENT` notifications. That should be fixed, but unless a fix is found a workaround is to just send normal priority notifications for the three cases where we currently use urgent to get a release out.
