### ISSUE TITLE
Share to Device missing from Context Menu of nautilus

### ISSUE THREAD

**Issue by ujwalnk** [GSConnect/gnome-shell-extension-gsconnect#1802]
### Describe the bug

The context menu, share to device appeared for a while and suddenly disappeared recently. I can share files using the icon at the top bar, but nothing in the Nautilus context menu.

I seem to have all the required dependencies, i.e. nautilus-python, python3-gobject (Not able to install python2-gobject), nautilus-extensions.x86_64 & gnome-shell-extension-gsconnect.x86_64.

Also there doesn't seem to be any option for nautilus integration in the gs connect app device preferences.

I am running Fedora 40 (Workstation Edition), Gnome 46 Wayland.

Thanks in advance for the help.

PS. Another qa-form mentioned the default file-browser app not being called Nautilus, but Files in Gnome 46. If that helps???

### Steps to reproduce

Fresh install of Fedora 40, with GS Connect.

### Expected behavior

A context menu option, Share to device should appear allowing sharing of files.

### GSConnect version

GS Connect 57

### Installed from

GNOME Extensions website

### GNOME Shell version

Gnome 46

### Linux distribution/release

Fedora 40 (Workstation Edition)

### Paired device(s)

Samsung M21, Samsung S6 Lite

### KDE Connect app version

1.30.1

### Screenshots

Able to share files from the top bar icon

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/18006871/f0b1b378-cf67-47a4-9793-cf7c6f2c3179)

No context menu on nautilus 
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/18006871/3781440b-3a9b-4536-9512-558ef89664e2)

**Comment by ketanbaitule** [comment]
https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#optional-features

After installing optional dependency, you need to restart `Nautilus`

**Comment by ferdnyc** [comment]
Ah, no, I see the problem.

@ujwalnk When using the distro-packaged GSConnect on Fedora, to get file manager integration you need to also install the `nautilus-gsconnect` RPM.

```sh
sudo dnf install nautilus-gsconnect
```

The Fedora packager for GSConnect [has taken the nonsense position](https://src.fedoraproject.org/rpms/gnome-shell-extension-gsconnect/pull-request/2) that file manager integration is not a "core functionality" of the extension, and so has refused to add even soft dependencies; users are forced to discover the existence of `nautilus-gsconnect` and `nemo-gsconnect` for themselves. Sorry!

**Comment by ferdnyc** [comment]
(You may also want to `sudo dnf install webextension-gsconnect`, as that package contains the bits that integrate with the browser extension to provide the link-sending and open-on-device features.)

**Comment by ferdnyc** [comment]
Oh, sorry, one thing I just noticed:

You mentioned having the extension installed from the Extensions website, but _also_ having the `gnome-shell-extension-gsconnect` RPM installed. That means you're actually _**NOT**_ using the extension installed from extensions.gnome.org; the one installed to the system (in `/usr/share/gnome-shell/extensions/`) will override it.

So the alternative solution is to do this:
```sh
sudo dnf remove gnome-shell-extension-gsconnect
```
...which will cause your session to use the extension installed from e.g.o to `$HOME/.local/share/gnome-shell/extensions/`. That version will have the webextension hooks and file-manager integration enabled.
