### ISSUE TITLE
Unable to browse files on Android 12: Permission Denied

### ISSUE THREAD

**Issue by bdobby** [GSConnect/gnome-shell-extension-gsconnect#1804]
### Describe the bug

Running GSConnect on Ubuntu 22.04 and KDE Connect on Android 12. File transfer works ok, but attempt to mount the phone file system fails. The support log shows 'permission denied' in response to 'list directories'. The KDE Connect app has 'All files' permission.

### Steps to reproduce

1. Click on system menu
2. Click on phone name to display GS Connect menu
3. Click on _Mount_
4. The _Mount_ menu is not replaced by a _Files_ menu
5. The phone appears in Nautilus, but attempts to view the files shows a _Permission Denied_ message.

### Expected behavior

1. The phone files should be visible in Nautilus. 
2. I understand that the _Mount_ menu in GSConnect should be replace by _Files_, but I've not used this app before so I may be wrong.

### GSConnect version

50

### Installed from

Extension Manager

### GNOME Shell version

42.9

### Linux distribution/release

Ubuntu 22.04

### Paired device(s)

Ulafone Armor 17, Android 12

### KDE Connect app version

1.30.1

### Support log

```plain text
May 09 09:57:54 org.gnome.Shell.Extensions.GSConnect[2883]: [/service/device.js:sendPacket:449]: Zaphod: {
                                                              "id": 1715245074127,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
May 09 09:57:54 org.gnome.Shell.Extensions.GSConnect[2883]: [/service/device.js:_readLoop:341]: Zaphod: {
                                                              "id": 1715245074444,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "192.168.18.2",
                                                                "port": 1750,
                                                                "user": "kdeconnect",
                                                                "password": "NKqrHSy9fwzAJbb6Kga5pF1JT96t",
                                                                "path": "/storage/emulated/0",
                                                                "multiPaths": [
                                                                  "/storage/emulated/0"
                                                                ],
                                                                "pathNames": [
                                                                  "Internal shared storage"
                                                                ]
                                                              }
                                                            }
May 09 09:57:55 org.gnome.Shell.Extensions.GSConnect[2883]: [/service/plugins/sftp.js:_listDirectories/iter</<:161]: Zaphod: Permission denied
                                                            _listDirectories/iter</<@/home/brian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:161:38
                                                            @/home/brian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

### Screenshots

Message when attempting to view files from mount in Nautilus.

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/30202518/a1f6d6cd-f099-4a9c-9849-f45645fa18c6)

**Comment by ferdnyc** [comment]
This appears to be the same issue as #1610, and since there's been significant activity over there I'm going to close it as a duplicate and keep the conversation centered on that issue. Thanks for reporting!

**Comment by bdobby** [comment]
👍

**Comment by Ebrat222** [comment]
Use This Code :

cd ../sdcard/download

![Screenshot_20251218-213842.png](https://github.com/user-attachments/assets/ba2190a3-a4ac-410c-950b-0b97aaf6260c)
