### ISSUE TITLE
Android mounting doesn't work

### ISSUE THREAD

**Issue by Yarnacle** [GSConnect/gnome-shell-extension-gsconnect#1829]
### Describe the bug

All other features seem fine. I can't mount my Samsung Android device. When I select the Mount option on my computer, nothing happens. I have ``python3-nautilus`` and ``gir1.2-nautilus-3.0`` installed. I saw reports for other mounting errors but none matched mine exactly.

### Expected behavior

I expected for my device to show up in Nautilus

### GSConnect version

50

### Installed from

GNOME Extensions website

### GNOME Shell version

42.9

### Linux distribution/release

Pop!_OS 22.04 LTS

### Paired device(s)

Samsung Galaxy S22

### KDE Connect app version

1.30.1

### Support log

```plain text
Jun 20 12:00:32 org.gnome.Shell.Extensions.GSConnect[381215]: [/service/device.js:sendPacket:449]: Galaxy S22: {
                                                                "id": 1718902832688,
                                                                "type": "kdeconnect.sftp.request",
                                                                "body": {
                                                                  "startBrowsing": true
                                                                }
                                                              }
Jun 20 12:00:32 org.gnome.Shell.Extensions.GSConnect[381215]: [/service/device.js:_readLoop:341]: Galaxy S22: {
                                                                "id": 1718902832698,
                                                                "type": "kdeconnect.sftp",
                                                                "body": {
                                                                  "ip": "192.168.1.21",
                                                                  "port": 1746,
                                                                  "user": "kdeconnect",
                                                                  "password": "v6bSOALyO0vTSaBGWv74twuGpz9Y",
                                                                  "path": "/storage/emulated/0",
                                                                  "multiPaths": [
                                                                    "/storage/emulated/0"
                                                                  ],
                                                                  "pathNames": [
                                                                    "Internal storage"
                                                                  ]
                                                                }
                                                              }
Jun 20 12:00:33 gjs[381215]: JS ERROR: Galaxy S22: Gio.IOErrorEnum: Permission denied
                             _handleMount/</<@/home/roger/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                             @/home/roger/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by jpritikin** [comment]
Same symptom here:

this._getESourceRegistry is not a function

_initEvolutionDataServer@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/contacts.js:270:41
fetch@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/contacts.js:545:28
_sync@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:967:30
_init@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:874:14
MessagingWindow@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:833:4
get window@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:170:28
sms@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:464:9
_activateAction@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugin.js:94:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
