### ISSUE TITLE
Can not mount phone

### ISSUE THREAD

**Issue by AM-dev-8** [GSConnect/gnome-shell-extension-gsconnect#1847]
### Describe the bug

Hello,
I want to browse my phone by gsconnect sftp but i can not mount it.

I tried to install any ssh related apps but nothing happends.

### Steps to reproduce

1-Turn on the GSConnect from quick tiles and pair the phone KDE Connect in more settings
2-Open the more options from 3 dots in device setting window and Click on mount
3- Nothing shows in nautilus

### GSConnect version

57

### Installed from

Extension Manager

### GNOME Shell version

46

### Linux distribution/release

Ubuntu 22.04

### Paired device(s)

Samsung Galaxy A54 5G

### KDE Connect app version

1.30.1

### Plugin(s)

SFTP Mount

### Support log

Journalctl Log:

Jul 28 21:51:17 strixwolf-pc gjs[29587]: JS ERROR: SM-A546E: Gio.IOErrorEnum: Connection failed
                                         _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                         _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
                                         ### Promise created here: ###
                                         _handleMount@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:228:24
                                         async*handlePacket@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:121:26
                                         handlePacket@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:435:25
                                         _readLoop@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:359:22
                                         async*setChannel@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:340:18
                                         _onChannel@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:234:20
                                         channel@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:432:19
                                         _onIncomingChannel@file:///home/strixwolf/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:252:18
                                         async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
Jul 28 21:51:19 strixwolf-pc tracker-miner-fs-3[31450]: (tracker-extract-3:31450): GLib-GIO-WARNING **: 21:51:19.672: Error creating IO channel for /proc/self/mountinfo: Invalid argument (g-io-error-quark, 13)

**Comment by ferdnyc** [comment]
@AM-dev-8 

If you want to be a little more security-conscious, you can limit that config to just your local network, e.g.

```text
Host 192.168.1.*  # (substitute your local net prefix, obv.)
    HostKeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
```

That way, you'll still exclude relatively insecure RSA keys from hosts elsewhere on the internet. (They're disabled by default for a reason, after all...)
