### ISSUE TITLE
Remote Input Screen Can Profit From Displaying Name Of The Connected System

### ISSUE THREAD

**Issue by mohsenBanan** [GSConnect/gnome-shell-extension-gsconnect#1854]
### Describe your request

Remote Input Screen Can Profit From Displaying Name Of The Connected System.

I connect to many systems. And on my android device when it is connected to one of those systems, I wish I could know 
which one it is connected to from the Remote Input screen. I can go back one screen and it will then show me the connected system name.
But, why should I have to do that?

### Proposed solution

Display the name of the connected system on the Android Input Screen.

### Alternatives

None.

### GSConnect version

1.32.0

### Installed from

OS package manager

### GNOME Shell version

43.9

### Linux distribution/release

Debian 12

### Additional context

This relates to the Android/Device side not the Gnome desktop (GSconnect). I tried reporting it on KDE Connect side but was not successful. If you see merit in what I am suggesting, please pass it along to the KDE Connect folks. Thanks in advance.

**Comment by ferdnyc** [comment]
@mohsenBanan 

> 1.32.0

That's not a valid GSConnect version. A GSConnect version is something like `49` or `52` or `56` or (current) `57`. It _might_ be a `gjs` version, which isn't relevant in this particular situation.

Given that you're on GNOME 43, you're likely running an outdated (and unsupported) version of GSConnect. GSConnect 57 does indeed display the target device name in the window headerbar. When sending remote input to my paired "Galaxy A53 5G" device...

![image](https://github.com/user-attachments/assets/3ab706bc-ce0c-4460-9a06-ed8981077478)

**Comment by ferdnyc** [comment]
> This relates to the Android/Device side not the Gnome desktop (GSconnect). I tried reporting it on KDE Connect side but was not successful.

Oh, sorry, I failed to read that part carefully enough. My mistake.

**Comment by ferdnyc** [comment]
We have no real "in" with the KDE Connect folks, but bugs and feature requests can be filed in KDE bugzilla under the [kdeconnect android-application component](https://bugs.kde.org/enter_bug.cgi?product=kdeconnect&component=android-application).

**Comment by mohsenBanan** [comment]
Thank your very much for having looked into it and the pointer.
