### ISSUE TITLE
Publish v58 to extensions.gnome.org

### ISSUE THREAD

**Issue by ferdnyc** [GSConnect/gnome-shell-extension-gsconnect#1880]
### Describe your request

@daniellandau, could you please submit the newly-released https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/download/v58/gsconnect@andyholmes.github.io.zip to E.G.O. for review?

### GSConnect version

58

### Installed from

GitHub releases (zip file)

### GNOME Shell version

47

**Comment by daniellandau** [comment]
Now published at e.g.o. Sorry for not having the bandwidth to contribute more this cycle 😟
