### ISSUE TITLE
gnome-shell-extensions is missing

### ISSUE THREAD

**Issue by jbla62** [GSConnect/gnome-shell-extension-gsconnect#1896]
### Describe the bug

Hi,
I installed "gnome-shell-extension-gsconnect" and "gnome-shell-extension-gsconnect-browsers" via "apt install" on an "Ubuntu 24.04" laptop. After that I couldn't enable the extension because the package "gnome-shell-extensions" was not installed. I had to install it manually.

Thanks for this application!! It makes the "Android <--> Linux" communication much easier!

### Expected behavior

The package "gnome-shell-extensions" should be installed automatically when GSConnect is installed.

### GSConnect version

57-1

### Installed from

OS package manager

### GNOME Shell version

46.1-2

### Linux distribution/release

Ubuntu 24.04

**Comment by jbla62** [comment]
I forgot! This was the first "gnome-shell-extension" on this laptop.

**Comment by ferdnyc** [comment]
@jbla62 We don't create or control the `.deb` packages for GSConnect. I'd tend to _agree_ with you about the dependencies, but that's something to bring up @ Launchpad I suppose.

**Comment by ferdnyc** [comment]
(If it helps your case any, on Fedora `gnome-shell-extensions-gsconnect` requires `gnome-shell`, and the `gnome-extensions` utility is part of `gnome-shell`.)
