### ISSUE TITLE
[A11Y] GSConnect Basic Accessibility

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gnome-shell-extension-gsconnect#240]
> ***Please Don't Edit These Lists.*** If you're interested in helping to test accessibility features, please ping a developer on this issue.

**[GNOME Accessibility Checklist](https://developer.gnome.org/accessibility-devel-guide/stable/gtest.html)**

* [ ] GP General Principles
  * [ ] GP.1 Every action that alters the user's data or application's settings can be undone.
  * [ ] GP.2 All application settings can be restored to their defaults without the user having to remember what those defaults were.
  * [x] GP.3 ~~After installation, the application can be used without the user having to insert a disk or CD at any time.~~
  * [ ] GP.4 The most frequently used functions are found at the top level of the menu structure.
* [ ] KN Keyboard Navigation
  * [ ] KN.1 Efficient keyboard access is provided to all application features.
  * [ ] KN.2 All windows have a logical keyboard navigation order.
  * [ ] KN.3 The correct tab order is used for controls whose enabled state is dependent on checkboxes, radio buttons or toggle buttons.
  * [ ] KN.4 Keyboard access to application-specific functions does not override existing system accessibility features.
  * [ ] KN.5 The application provides more than one method to perform keyboard tasks whenever possible.
  * [ ] KN.6 There are alternative key combinations wherever possible.
  * [ ] KN.7 There are no awkward reaches for frequently performed keyboard operations.
  * [ ] KN.8 The application does not use repetitive, simultaneous keypresses.
  * [ ] KN.9 The application provides keyboard equivalents for all mouse functions.
  * [ ] KN.10 Any text or object that can be selected with the mouse can also be selected with the keyboard alone.
  * [ ] KN.11 Any object that can be resized or moved with the mouse can also be resized or moved with the keyboard alone.
  * [ ] KN.12 The application does not use any general navigation functions to trigger operations.
  * [ ] KN.13 All keyboard-invoked menus, windows and tooltips appear near the object they relate to.
* [ ] MI Mouse Interaction
  * [ ] MI.1 No operations depend on input from the right or middle mouse buttons.
  * [ ] MI.2 All mouse operations can be cancelled before they are complete.
  * [x] MI.3 ~~Visual feedback is provided throughout drag and drop operations~~
  * [ ] MI.4 The mouse pointer is never warped under application control, or its movement restricted to part of the screen by the application.
* [ ] GE Graphical Elements
  * [ ] GE.1 There are no hard-coded graphical attributes such as line, border or shadow thickness.
  * [ ] GE.2 All multi-color graphical elements can be shown in monochrome only, where possible.
  * [ ] GE.3 All interactive GUI elements are easily distinguishable from static GUI elements.
  * [ ] GE.4 An option to hide non-essential graphics is provided.
* [ ] FT Fonts and Text
  * [ ] FT.1 No font styles or sizes are hard-coded.
  * [ ] FT.2 An option to turn off graphical backdrops behind text is provided.
  * [ ] FT.3 All labels have names that make sense when taken out of context.
  * [ ] FT.4 No label names are used more than once in the same window.
  * [ ] FT.5 Label positioning is consistent throughout the application.
  * [ ] FT.6 All static text labels that identify other controls end in a colon (:).
  * [ ] FT.7 Static text labels that identify other controls immediately precede those controls in the tab order.
  * [x] FT.8 ~~An alternative to WYSIWYG is provided. For example, the ability to specify different screen and printer fonts in a text editor.~~
* [ ] CC Color and Contrast
  * [ ] CC.1 Application colors are not hard-coded, but are drawn either from the current desktop theme or an application setting.
  * [ ] CC.2 Color is only used as an enhancement, and not as the only means to convey information or actions.
  * [ ] CC.3 The application supports all available high- contrast themes and settings.
  * [ ] CC.4 The software is not dependent on any particular high-contrast themes or settings.
* [ ] MG Magnification
  * [ ] MG.1 The application provides the ability to magnify the work area.
  * [ ] MG.2 The application provides the option to scale the work area.
  * [ ] MG.3 The application's functionality is not affected by changing the magnification or scale settings.
* [ ] AU Audio
  * [ ] AU.1 Sound is not used as the only means of conveying any items of information.
  * [ ] AU.2 The user can configure the frequency and volume of all sounds and warning beeps.
* [ ] AN Animation
  * [ ] AN.1 There are no flashing or blinking elements with a frequency greater than 2Hz or lower than 55Hz.
  * [ ] AN.2 Any flashing or blinking is confined to small areas of the screen.
  * [ ] AN.3 If animation is used, an option is available to turn it off before it is first shown.
* [ ] KF Keyboard Focus
  * [ ] KF.1 When a window is opened, focus starts at the most commonly-used control.
  * [ ] KF.2 Current input focus position is clearly displayed at all times.
  * [ ] KF.3 Input focus is shown in exactly one window at all times.
  * [ ] KF.4 Appropriate audio or visual feedback is provided when the user attempts to navigate past either end of a group of related objects.
  * [ ] KF.5 The default audio or visual warning signal is played when the user presses an inappropriate key.
  * [ ] KF.6 There is sufficient audio information for the visual focus that the user can figure out what to do next.
  * [ ] KF.7 When using assistive technologies, such as a screen reader or braille device, the current program indicates the position and content of the visual focus indicator.
* [ ] TM Timing
  * [ ] TM.1 There are no hard-coded time-outs or time-based features in the application.
  * [ ] TM.2 The display or hiding of important information is not triggered solely by movement of the mouse pointer.
* [ ] DC Documentation
  * [ ] DC.1 All documentation is in an accessible format, with textual alternate descriptions provided for all figures and diagrams.
  * [ ] DC.2 The documentation includes a section that covers all the application's accessibility features.

**GSConnect Specific Checklist**

* [ ] Service Settings
  * [ ] *Connect to...* Dialog
  * [ ] *Generate Support Log* Dialog
* [ ] Device Settings
  * [x] Sharing
  * [ ] Commands
  * [ ] Notifications
  * [x] Telephony
  * [ ] Keyboard Shortcuts
    * [ ] Shortcut Editor Dialog
  * [ ] Advanced
* [ ] Messaging Window
  * [ ] Contacts List
  * [ ] Conversation List
  * [ ] Conversation Widget
* [ ] Miscellaneous Dialogs and UI
  * [ ] Device Chooser Dialog
  * [ ] Share File Chooser Dialog
* [ ] Shell Extension
  * [ ] Device Indicator (Panel)
  * [ ] Device Menu (Panel)
  * [ ] Device Menu (User Menu)
  * [ ] Service Menu (User Menu)
  * [ ] *Do Not Disturb* Dialog
* [ ] WebExtension
  * [ ] Context Menu
  * [ ] Popup Menu
* [x] Relevant Bugs/Issues
  * [x] #335 Multi-DPI support on Wayland
  * [x] #356 "Locate"/Find My Phone"
  * [x] #376 Repliable Notifications

**See Also:**
* https://phabricator.kde.org/T9885
* https://mail.gnome.org/archives/orca-list/2018-October/msg00112.html

**Comment by fr3nchalp4a** [comment]
Did this have been forgotten ? @andyholmes 
I see most of the associated issues have been resolved (or partially).

**Comment by andyholmes** [comment]
I never received any feedback about the changes I made, and I don't really contribute to GSConnect anymore, sorry! Someone else is welcome to pick-up the issue if they like.

**Comment by fr3nchalp4a** [comment]
I think nobody is actually _caring_ about this and focuses on other tasks 😅 I'm going through every old issues to make sure they are not forgotten (i personally hate when people dont care to respond and just leave the issue like it never happened)

**Comment by andyholmes** [comment]
Sure, although it's worth mentioning that there aren't many contributions to this project any more. If the criteria is close issues that no one is working on, then that's more or less all of them AFAIK.

**Comment by fr3nchalp4a** [comment]
It seems that it's still used actually, but you were the only one to seriously develop this anyway.
