### ISSUE TITLE
Custom battery level alert when charging

### ISSUE THREAD

**Issue by noccy80** [GSConnect/gnome-shell-extension-gsconnect#872]
**Is your feature request related to a problem? Please describe.**
I try to avoid charging my phone to 100% to preserve battery health, but at times I forget to check the phone and end up getting the notification from GSC that my battery is fully charged.

**Describe the solution you'd like**
A toggle and an input to specify a percentage at which you want to receive a notification, f.ex. 80%. The notification should only show up if the device is charging.

**Describe alternatives you've considered**
I've tried apps to do it on the phone, but they always come with extra crap that might affect performance and require permissions.

**System Details (please complete the following information):**
 - GSConnect version: 38
 - Installed from: extensions.gnome.org

**Additional context**

**Comment by andyholmes** [comment]
I probably won't add this this feature myself, but I would accept a patch for it.

**Comment by andyholmes** [comment]
Sorry for the late reply.

Neither are very difficult, but I don't have any plans to add UI features myself as I don't have as much time to dedicate to GSConnect. If someone contributes a patch, I'd probably accept it as I assume they'll also have time/incentive to maintain it.

**Comment by daniellandau** [comment]
Fix has been merged.
