### ISSUE TITLE
GSConnect does not support OpenSSL 3.0 pre-releases

### ISSUE THREAD

**Issue by mokilcde** [GSConnect/gnome-shell-extension-gsconnect#886]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

When starting computer I got a popup with the following message:
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null
get@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/__init__.js:92:64
_initCertificate@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:146:35
start@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:410:14
_initBackends@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:492:25
vfunc_startup@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:630:14
vfunc_handle_local_options@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1064:18
@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1132:17

Already delete extension and all settings in dconf and in local

**Steps To Reproduce:**

1. Start computer
2. Log in

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

``
GSConnect Version: 39
GSConnect Install: user
GJS: 16403
XDG_SESSION_TYPE: x11
GDMSESSION: lightdm-xsession
--------------------------------------------------------------------------------
[0;1;39mHint: You are currently not seeing messages from other users and the system.[0m
[0;1;39m      Users in groups 'adm', 'systemd-journal' can see all messages.[0m
[0;1;39m      Pass -q to turn off this notice.[0m
-- Logs begin at Fri 2020-04-24 10:48:31 CEST, end at Tue 2020-06-30 06:27:00 CEST. --
Jun 30 06:26:43 gnome-shell[3551]: JS WARNING: [resource:///org/gnome/shell/ui/workspacesView.js 756]: reference to undefined property 1
Jun 30 06:26:43 gnome-shell[3551]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                   _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:756:13
                                   setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:746:14
                                   setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:301:33
                                   _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:497:27
                                   vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:401:14
                                   _computeWindowCenter@resource:///org/gnome/shell/ui/workspace.js:302:35
                                   _init@resource:///org/gnome/shell/ui/workspace.js:160:14
                                   _addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1856:21
                                   _init@resource:///org/gnome/shell/ui/workspace.js:1174:22
                                   _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
                                   _init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
                                   _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
                                   show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
                                   show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
                                   _animateVisible@resource:///org/gnome/shell/ui/overview.js:579:27
                                   show@resource:///org/gnome/shell/ui/overview.js:565:14
                                   toggle@resource:///org/gnome/shell/ui/overview.js:688:18
                                   _initializeUI/<@resource:///org/gnome/shell/ui/main.js:220:22
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.ControlCenter.SearchProvider' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Contacts.SearchProvider' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Documents' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Nautilus' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Boxes.SearchProvider' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Calculator.SearchProvider' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Calendar' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Characters.BackgroundService' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.clocks' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Notes.SearchProvider' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.seahorse.Application' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Photos' requested by ':1.57' (uid=1000 pid=3551 comm="/usr/bin/gnome-shell")
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Boxes.SearchProvider'
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.clocks'
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Calculator.SearchProvider'
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.seahorse.Application'
Jun 30 06:26:43 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Characters.BackgroundService'
Jun 30 06:26:44 systemd[3200]: Starting Tracker metadata database store and lookup manager...
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.159' (uid=1000 pid=8860 comm="/usr/bin/gnome-photos --gapplication-service")
Jun 30 06:26:44 systemd[3200]: Started Tracker metadata database store and lookup manager.
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.freedesktop.Tracker1'
Jun 30 06:26:44 bijiben-shell-s[8854]: Loading account account_1543474776_0
Jun 30 06:26:44 seahorse[8857]: key.vala:268: Key doesn't have a valid type (1024).
Jun 30 06:26:44 seahorse[8857]: key.vala:268: Can't distinguish type from data (space missing).
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Documents'
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Contacts.SearchProvider'
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Notes.SearchProvider'
Jun 30 06:26:44 systemd[3200]: Started GnuPG cryptographic agent and passphrase cache.
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Nautilus'
Jun 30 06:26:44 gpg-agent[8962]: gpg-agent (GnuPG) 2.2.20 starting in supervised mode.
Jun 30 06:26:44 gpg-agent[8962]: using fd 3 for std socket (/run/user/1000/gnupg/S.gpg-agent)
Jun 30 06:26:44 gpg-agent[8962]: using fd 4 for browser socket (/run/user/1000/gnupg/S.gpg-agent.browser)
Jun 30 06:26:44 gpg-agent[8962]: using fd 5 for ssh socket (/run/user/1000/gnupg/S.gpg-agent.ssh)
Jun 30 06:26:44 gpg-agent[8962]: using fd 6 for extra socket (/run/user/1000/gnupg/S.gpg-agent.extra)
Jun 30 06:26:44 gpg-agent[8962]: listening on: std=3 extra=6 browser=4 ssh=5
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Photos'
Jun 30 06:26:44 org.gnome.Nautilus[8843]: Initializing nautilus-image-converter extension
Jun 30 06:26:44 org.gnome.Nautilus[8843]: Initializing nautilus-dropbox 2019.02.14
Jun 30 06:26:44 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Calendar'
Jun 30 06:26:44 gnome-photos[8860]: Module '/usr/lib/x86_64-linux-gnu/gegl-0.4/exr-load.so' load error: libIlmImf-2_3.so.24: cannot open shared object file: No such file or directory
Jun 30 06:26:44 gnome-photos[8860]: Module '/usr/lib/x86_64-linux-gnu/gegl-0.4/exr-save.so' load error: libIlmImf-2_3.so.24: cannot open shared object file: No such file or directory
Jun 30 06:26:44 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'Contacts': Failed with HTTP error 403: Forbidden
Jun 30 06:26:44 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'Feiertage in Deutschland': Failed with HTTP error 403: Forbidden
Jun 30 06:26:44 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'kc.videri@gmail.com': Failed with HTTP error 403: Forbidden
Jun 30 06:26:45 systemd[3200]: tmp-sanity\x2dmountpoint\x2d891562073.mount: Succeeded.
Jun 30 06:26:45 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:45 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='com.intel.dleyna-renderer' requested by ':1.159' (uid=1000 pid=8860 comm="/usr/bin/gnome-photos --gapplication-service")
Jun 30 06:26:45 dleyna-renderer-service[9063]: dLeyna core version 0.6.0
Jun 30 06:26:45 dleyna-renderer-service[9063]: dleyna-renderer-service version 0.6.0
Jun 30 06:26:45 dleyna-renderer-service[9063]: Type[0] Level[0x13] Mask[0x4C] Flags[0x4F]
Jun 30 06:26:45 dleyna-renderer-service[9063]: Load file [/srv/home/michael/.config/dleyna-renderer-service.conf]
Jun 30 06:26:45 dleyna-renderer-service[9063]: [General settings]
Jun 30 06:26:45 dleyna-renderer-service[9063]: Never Quit: F
Jun 30 06:26:45 dleyna-renderer-service[9063]: Connector Name: dbus
Jun 30 06:26:45 dleyna-renderer-service[9063]: Port: 0
Jun 30 06:26:45 dleyna-renderer-service[9063]: Push host port: 0
Jun 30 06:26:45 dleyna-renderer-service[9063]: [Logging settings]
Jun 30 06:26:45 dleyna-renderer-service[9063]: Log Type : 0
Jun 30 06:26:45 dleyna-renderer-service[9063]: Log Level: 0x13
Jun 30 06:26:45 dleyna-renderer-service[9063]: [Network filtering settings]
Jun 30 06:26:45 dleyna-renderer-service[9063]: Enabled : F
Jun 30 06:26:45 dleyna-renderer-service[9063]: Entries: (null)
Jun 30 06:26:45 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'com.intel.dleyna-renderer'
Jun 30 06:26:45 dleyna-renderer-service[9063]: Calling GetRenderers method
Jun 30 06:26:45 zeitgeist-datah[3774]: zeitgeist-datahub.vala:207: Error during inserting events: GDBus.Error:org.gnome.zeitgeist.EngineError.InvalidArgument: Incomplete event: interpretation, manifestation and actor are required
Jun 30 06:26:45 systemd[3200]: Started Application launched by gnome-shell.
Jun 30 06:26:45 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:45 dleyna-renderer-service[9063]: New media server /com/intel/dLeynaRenderer/server/uuid_3abb5e21ce_2d1111_2d11b2_2df918_2dAC6FBB481B50
Jun 30 06:26:45 dleyna-renderer-service[9063]: Client :1.159 lost
Jun 30 06:26:45 dleyna-renderer-service[9063]: Lost /com/intel/dLeynaRenderer/server/uuid_3abb5e21ce_2d1111_2d11b2_2df918_2dAC6FBB481B50
Jun 30 06:26:46 gvfsd[9106]: smbXcli_negprot_smb1_done: No compatible protocol selected by server.
Jun 30 06:26:46 gvfsd[9106]: got no contact to IPC$
Jun 30 06:26:47 dleyna-renderer-service[9063]: dLeyna: Exit
Jun 30 06:26:52 org.gnome.tweaks.desktop[9157]: gnome-shell-extension-prefs is deprecated
Jun 30 06:26:52 org.gnome.tweaks.desktop[9157]: Install https://flathub.org/apps/details/org.gnome.Extensions for extension
Jun 30 06:26:52 org.gnome.tweaks.desktop[9157]: management, or use the gnome-extensions command line tool.
Jun 30 06:26:52 org.gnome.tweaks.desktop[9157]: Extensions can use the ExtensionUtils.openPrefs() method.
Jun 30 06:26:52 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Shell.Extensions' requested by ':1.176' (uid=1000 pid=9159 comm="gnome-extensions prefs gsconnect@andyholmes.github")
Jun 30 06:26:52 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.gnome.Shell.Extensions'
Jun 30 06:26:52 dbus-daemon[3231]: [session uid=1000 pid=3231] Reloaded configuration
Jun 30 06:26:52 gnome-shell[9196]: X Error of failed request:  BadWindow (invalid Window parameter)
Jun 30 06:26:52 gnome-shell[9196]:   Major opcode of failed request:  18 (X_ChangeProperty)
Jun 30 06:26:52 gnome-shell[9196]:   Resource id in failed request:  0x8600007
Jun 30 06:26:52 gnome-shell[9196]:   Serial number of failed request:  13
Jun 30 06:26:52 gnome-shell[9196]:   Current serial number in output stream:  15
Jun 30 06:26:52 gnome-shell[3551]: STACK_OP_RAISE_ABOVE: sibling window 0x8600007 not in stack
Jun 30 06:26:53 gnome-shell[3551]: STACK_OP_RAISE_ABOVE: sibling window 0x8600007 not in stack
Jun 30 06:26:53 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.1' (uid=1000 pid=3227 comm="/usr/libexec/tracker-miner-fs")
Jun 30 06:26:53 systemd[3200]: Starting Tracker metadata extractor...
Jun 30 06:26:53 tracker-extract[9198]: Set scheduler policy to SCHED_IDLE
Jun 30 06:26:53 tracker-extract[9198]: Setting priority nice level to 19
Jun 30 06:26:53 dbus-daemon[3231]: [session uid=1000 pid=3231] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
Jun 30 06:26:53 systemd[3200]: Started Tracker metadata extractor.
Jun 30 06:26:55 bijiben-shell-s[8854]: Creating ressource <vim> davs://michael@doc.k-c13.org/remote.php/webdav/Notes/vim.txt
Jun 30 06:26:56 bijiben-shell-s[8854]: Creating ressource <mc> davs://michael@doc.k-c13.org/remote.php/webdav/Notes/mc.txt
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:26:57 bijiben-shell-s[8854]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 30 06:27:00 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'Feiertage in Deutschland': Failed with HTTP error 403: Forbidden
Jun 30 06:27:00 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'Contacts': Failed with HTTP error 403: Forbidden
Jun 30 06:27:00 gnome-calendar[8849]: source_credentials_required_cb: Failed to authenticate 'kc.videri@gmail.com': Failed with HTTP error 403: Forbidden`
```

**System Details (please complete the following information):**

 - **GSConnect version:** 39
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Debian SID

**GSConnect environment (if applicable):**

 - **KDE Connect app version:** [e.g. 1.14.2]

**Additional Notes:**

Here my syslog (only lines with gsconnect)
```
Jun 30 06:21:12 k-c13 gjs[3855]: JS ERROR: TypeError: /(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null#012get@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/__init__.js:92:64#012_initCertificate@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:146:35#012start@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:410:14#012_initBackends@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:492:25#012vfunc_startup@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:630:14#012vfunc_handle_local_options@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1064:18#012@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1132:17
Jun 30 06:26:52 k-c13 dbus-daemon[3231]: [session uid=1000 pid=3231] Activating service name='org.gnome.Shell.Extensions' requested by ':1.176' (uid=1000 pid=9159 comm="gnome-extensions prefs gsconnect@andyholmes.github")
```

Add any addtional information about the problem or your system.

**Comment by andyholmes** [comment]
Can you confirm you have `openssl` installed and a cetificate exists at `~/.config/gsconnect/certificate.pem`?

**Comment by mokilcde** [comment]
Hi Andy!
All exists!
$ dpkg -l | grep opensslii  libcrypt-openssl-bignum-
perl             0.09-1+b2                        amd64        Perl
module to access OpenSSL multiprecision integer arithmetic
librariesii  libcrypt-openssl-random-perl             0.15-
1+b2                        amd64        module to access the OpenSSL
pseudo-random number generatorii  libcrypt-openssl-rsa-
perl                0.31-
1+b2                        amd64        module for RSA encryption
using OpenSSLii  libcurl4-openssl-dev:amd64               7.68.0-
1                         amd64        development files and
documentation for libcurl (OpenSSL
flavour)ii  openssl                                  3.0.0~~alpha3-
1                  amd64        Secure Sockets Layer toolkit -
cryptographic utilityii  perl-openssl-
defaults:amd64              5                                amd64     
   version compatibility baseline for Perl OpenSSL packages
apt policy opensslopenssl:  Installed: 3.0.0~~alpha3-1  Candidate:
3.0.0~~alpha3-1  Version table: *** 3.0.0~~alpha3-1 660        660 
http://ftp.de.debian.org/debian experimental/main amd64
Packages        100 /var/lib/dpkg/status     1.1.1g-1 710        670 
http://ftp.de.debian.org/debian testing/main amd64 Packages        710 
http://ftp.de.debian.org/debian unstable/main amd64
Packages     1.1.1d-0+deb10u3 600        600 
http://ftp.de.debian.org/debian stable/main amd64 Packages        600 
http://security.debian.org stable/updates/main amd64
Packages        600 http://security.debian.org buster/updates/main
amd64 Packages

$
ls  ~/.config/gsconnect/certificate.pem/srv/home/michael/.config/gsconn
ect/certificate.pem
CU  Michael
On Tue, 2020-06-30 at 15:08 -0700, Andy Holmes wrote:
> ~/.config/gsconnect/certificate.pem
-- 
CU
  Michael Ott


-- 
Keppler IT GmbH - Die Hostingexperten.

Michael Ott                 Tel. (09131) 691-480
Developer                   Fax: (09131) 691-489

Am Weichselgarten 7         UStID.-Nr. DE259788698
91058 Erlangen              Amtsgericht Fürth, HRB 11477
www.keppler-it.de           Sitz d. Gesellschaft: Erlangen
______________________________________________________________________

**Comment by andyholmes** [comment]
Sorry, that's quite hard to read.

I'm assuming your version of `openssl` is `3.0.0~~alpha3-1`. This seems to be a pre-release version of openssl, as I'm running the latest stable `1.1.1g` locally.

OpenSSL 3.0 is a major refactoring of the project, so I'm not surprised something's going wrong and I'm not sure I can do anything about it. I'd recommend you run a stable release of OpenSSL instead, because we can't support pre-release software such as this.

**Comment by andyholmes** [comment]
Closing this one up, since this is an upstream problem.

**Comment by senjacob** [comment]
Ubuntu 22.04 only has openssl 3.0. 
For me gsconnect/kdeconnect does not show any devices in Ubuntu 22.04.

**Comment by andyholmes** [comment]
Issue moved to #1209, discussion continues there.
