### ISSUE TITLE
GSConnect is looking for a new maintainer

### ISSUE THREAD

**Issue by andyholmes** [GSConnect/gnome-shell-extension-gsconnect#989]
GSConnect is looking for a volunteer to take over maintainership of the project. Interested parties should comment here so the transfer of relevant permissions and resources can be made.

It's been a fun ride and I've learned a lot, with a lot of help, but it's time to pass the reigns to someone new. I'll continue general maintenance until the end of the year (about 3 months), then archive the repository if a volunteer hasn't come forward.

**Comment by ferdnyc** [comment]
Thanks for all the work you've put into it! GSConnect has grown and blossomed beyond what I'd ever have expected.

For my part, I'm happy to stay on and assist with support & maintenance (if the new developer wishes), and I can even take over release management duties if necessary, but I don't feel proficient enough in JavaScript to act as sole developer of a codebase this complex or dynamic. 

Anyone who steps up shouldn't feel as if they'll have to go it alone, though. (Unless, like I said, that's what they'd prefer.)

**Comment by pwd-github** [comment]
Thanks for everything. You've been more than amazing.

**Comment by sonnyp** [comment]
@andyholmes thanks for GSConnect! Will you stay involved in GNOME ?

I'd be happy to take over development and maintenance. The time I can dedicate to GSConnect is limited but worst case scenario should be enough to release bug and compatibility fixes as well as helping out contributors.

**Comment by blackwolf12333** [comment]
I don't have a lot of experience with extension development, but it's been one of the things that's been on my radar for a while. So I'm definitely interested in picking up some issues in the future. I've seen another project somewhere, where they were also looking for a new maintainer and that responsibility was split over a couple of new people, that might also work here?

Thanks for all the work on GSConnect!

**Comment by andyholmes** [comment]
> thanks for GSConnect! Will you stay involved in GNOME ?

Yep, I'll still be around doing other things :) 

I remember you form some contributions to GJS, so I've added you as a contributor for now. I plan to write up a short guide on making releases, but a full transfer of the repository might take a little more time, since there's crowdin, the CI docker image and so on. I guess a new Github organization would be best?

**Comment by andyholmes** [comment]
> I've seen another project somewhere, where they were also looking for a new maintainer and that responsibility was split over a couple of new people, that might also work here?

Seems like a good idea to me, but I was hoping a for new main maintainer, so they could pick and approve other contributors as necessary. Of course you can always file PRs for issues you want to take :)

**Comment by sonnyp** [comment]
> Yep, I'll still be around doing other things :)

Glad to hear, looking forward to it :)

>  I plan to write up a short guide on making releases

That'd be great, also feel free to email me random thoughts and napkin sketches about anything that can be of help if you don't have the time for a proper write-up, I'll take care of it.

Tips and tricks for development, testing and improving the feedback loop would be very useful.

> a full transfer of the repository might take a little more time, since there's crowdin, the CI docker image and so on. I guess a new Github organization would be best?

I'd suggest not changing too much right now and see how it goes. Let's get in touch soon-ish and discuss ?

**Comment by andyholmes** [comment]
> Tips and tricks for development, testing and improving the feedback loop would be very useful.

Okay, I think the best place for that is probably `CONTRIBUTING.md`, so I'll try to add notes there. I plan on uploading a file called `RELEASE_CHECKLIST.md`, although it's fairly straightforward.

> I'd suggest not changing too much right now and see how it goes. Let's get in touch soon-ish and discuss ?

Sound good. We will have to transfer ownership on extensions.gnome.org so you can upload releases though. I'm usually around on matrix, I guess the [#gsconnect](https://matrix.to/#/#gsconnect:matrix.org) channel is a good place or private message if you want.

**Comment by sonnyp** [comment]
@andyholmes many thanks for the documentation, it's great.

Do you have something in mind that'd be good for me get started with?

**Comment by andyholmes** [comment]
> Do you have something in mind that'd be good for me get started with?

I guess that's mostly up to you :)

#987 is probably the most important right now, while #897 might be an easy fix (although I couldn't reproduce it myself).

For feature requests #872 or #953 might be easier to start with, since you could implement those however you want.

**Comment by godslayer201** [comment]
@andyholmes 

I'm not an experienced Linux dev,but I really liked the functionality offered by GSConnect. 

Can I also volunteer as an maintainer? I would love to contribute to the extension.

Thanks!

**Comment by andyholmes** [comment]
@godslayer201 Sure, contributions are always welcome. Feel free to open a PR for any contribution, although I'm not really maintaining this extension any longer.

**Comment by mcl21014** [comment]
Thanks for your help! I found a memory leak somehow in the extension, with more details in a bug report. I read that the extension is looking for a new maintainer, so don't bother fixing it yourself. Good luck! But please let the new maintainer know of the leak. I hope I can reproduce it in the future.

**Comment by andyholmes** [comment]
At this point I'd consider GSConnect unmaintained and probably won't be fixing any bug or implementing features anymore.

Unless a volunteer steps forward to accept transfer of the repository and other resources (e.g.o. permissions, crowdin translations, etc), I'll be archiving it at the end of the month as planned

**Comment by premek** [comment]
@mcl21014 could you please have a look at my issue #1028 and add any info you got on the memory leak?

**Comment by daniellandau** [comment]
I'd be happy to accept the transfer and include the people above who have shown interest as co-maintainers. Thank you @andyholmes for your work creating this extension. It has become an essential part of my computer workflow.

The main credentials I can point to for why I could be suitable is my own extension https://github.com/daniellandau/switcher/ and I've also contributed a little to Polari and Shotwell (in addition to a bunch of stuff not related to GNOME, I can elaborate if needed or some of it is on my GitHub profile).

If you find my "application" suitable, I'd create a new GitHub organisation to be the target of the transfer. I just joined the Matrix room and I see you already left, but I can approach you there on a private message for the other stuff (crowdin, etc). (or you can find me, we are both in #extensions:gnome.org, I'm @dlandau:matrix.org)

**Comment by andyholmes** [comment]
@daniellandau that sounds good to me. If you want to create the organization, I can transfer the repository. We'll probably have to do that to see how much gets automatically ported over like webhooks and stuff.

**Comment by daniellandau** [comment]
Now created: https://github.com/GSConnect

**Comment by andyholmes** [comment]
Looks like you need to give me permission so I can transfer the repository.

**Comment by daniellandau** [comment]
You should now have an invitation

**Comment by andyholmes** [comment]
Okay transferred. It looks like [crowd.in](https://crowdin.com/project/gsconnect) automatically updated too. If you open an account or sign-in with github I can make you owner of that.

I put in a [request to transfer](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/128) the e.g.o permissions so you can upload new versions. I'm not sure about the CI yet, but it should keep working for now.

**Comment by daniellandau** [comment]
I made an [account](https://crowdin.com/profile/daniellandau) at crowdin with GitHub .

**Comment by andyholmes** [comment]
> I made an account at crowdin with GitHub .

It looks like open source projects can't transfer ownership yet, but if you join the project I can make you a manager that can do everything except delete the project.

**Comment by andyholmes** [comment]
Transfer on [ego](https://extensions.gnome.org/extension/1319/gsconnect/) is complete.

**Comment by daniellandau** [comment]
Updated the description and URL on ego. I just joined the the crowdin project.

**Comment by andyholmes** [comment]
I still haven't figured out how to mod you on the matrix channel, but someone reminded me you might want to join/introduce yourself on the KDE Connect [developer channel](https://gnome.element.io/#/room/#freenode_#kdeconnect:matrix.org) and possibly watch the [kdeconnect-android](https://invent.kde.org/network/kdeconnect-android) repo.

**Comment by mcl21014** [comment]
Glad to see someone picked up the project. This extension should be bundled in every GNOME based distro, or at least an optional component during install. I will try and reproduce the bug later when everything is settled. I honestly thought the project was toast.

**Comment by andyholmes** [comment]
Sorry, I also forgot about the WebExtensions. If you add an account on https://addons.mozilla.org and https://chrome.google.com/webstore/ I can transfer those as well :)

**Comment by daniellandau** [comment]
Hmm.

Firefox: This is the URL I have for my profile when logged in, but it gives a 404 when opened in a private window https://addons.mozilla.org/en-US/firefox/user/6420147/. I'm not totally sure what I need to do there.

Chrome: I'll make the account, but it's asking me to read a bunch of legalese and put in my credit card details so I'll try to get to that ASAP.

**Comment by andyholmes** [comment]
> I'm not totally sure what I need to do there.

I think now you have an account I just need the email address you registered it with. You can just PM me that on matrix or something when you get time.

That's weird that Chrome wants credit info, but it definitely doesn't cost money to do :)

**Comment by daniellandau** [comment]
Apparently it's a [new thing since March 2020](https://chromeunboxed.com/chrome-web-store-developer-dashboard-update-registration-fee/) that the Chrome store does want a 5 USD mandatory registration fee. I'll send you the email addresses of the accounts in Matrix.

**Comment by andyholmes** [comment]
> Apparently it's a new thing since March 2020 that the Chrome store does want a 5 USD mandatory registration fee.

Well, you can always sell it later. Sketchy companies are always trying to buy that off me :wink: 

> I'll send you the email addresses of the accounts in Matrix.

Okay, transfers initiated.

**Comment by daniellandau** [comment]
Mozilla extension came through. Nothing yet about he Chrome extension.

I think I can survive the $5 dent without selling to sketchy companies :joy:

**Comment by daniellandau** [comment]
@ferdnyc, @sonnyp: Are you in the Matrix channel with some nicknames? Do you want to join so we can coordinate that way?

**Comment by daniellandau** [comment]
I now see the Chrome extension in my dashboard. I think that concludes the technical transfer!

Thank you @andyholmes for developing this great extension! Feel free to stay involved as much as feels fun to you, no pressure either way. Anything you still want to do is much appreciated.

**Comment by daniellandau** [comment]
ffs google

![Kuvakaappaus - 2021-01-07 11-02-55](https://user-images.githubusercontent.com/1044056/103873150-0a3f2300-50d8-11eb-92a7-f3a3e6cddbf1.png)

**Comment by andyholmes** [comment]
I sent them an email about this. Their developer dashboard duplicated GSConnect and then removed them both :( Hopefully they will respond to the e-mail and re-instate the extension I transferred to you.

**Comment by daniellandau** [comment]
Reinstated.

**Comment by kahing** [comment]
does the README need to be updated to reflect the fact that there's a new maintainer?
